### ISSUE TITLE
Shares created and destroy with account names - double Locator in the resource name

### ISSUE THREAD

**Issue by funes79** [Snowflake-Labs/terraform-provider-snowflake#1075] opened 2022-06-24 11:09 UTC
**Provider Version**

"~>0.25.0"

**Terraform Version**

1.0.9

**Describe the bug**

Shares are being created with account name (or Snowflake locator) in the name and then terraform fails to destroy the object because it fails with:

The name of the share is `ABC.MYSHARE` 

```
Error: error dropping this does not seem to be used ACCOUNT_ID.ABC.MYSHARE: 002003 (02000): SQL compilation error:
Share '"ACCOUNT_ID.ACCOUNT_ID.ABC.MYSHARE"' does not exist or not authorized.
```

In the Query history we see a query coming from the provider trying to drop a share with double quoted account_id + name

```
DROP SHARE "ACCOUNT_ID.ABC.MYSHARE"
```

Note: we tested it also with a simple share name `MYSHARE` (without any dot in the name)

**Expected behavior**

The module should handle the create and drop correctly. 

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

```
resource "snowflake_share" "dev_share" {
  name     = "ABC.MYSHARE"
  comment  = "Testing out share."
  accounts = []
}
```

**Additional context**

**Comment by frankhetlandtelia** [comment] 2022-06-24 11:56
have the same issue here as well

**Comment by Anatoli-deBRADKE** [comment] 2022-06-24 14:39
I observe exactly the same behavior.

**Comment by simonepm** [comment] 2022-06-24 15:20
This is happening to me as well.

When creating a share like follows:

resource "snowflake_share" "<share_name>" {
  name     = "<share_name>"
}

The share is correctly created, but on the next terraform iteration, terraform performs a:

SHOW SHARES IN DATABASE;

in which the share names are displayed as fully qualified names <org_id>.<account_name>.<share_name>

This lead to failure as <share_name> is not found as terraform looks for <org_id>.<account_name>.<share_name>.

A simple solution would be for the provider to take only the last token by splitting the name on "."

Given it happend to us today I think on Snowflake side updated the output of:

SHOW SHARES IN DATABASE;

from <share_name> to <org_id>.<account_name>.<share_name>

As until yesterday was not happening to me.

**Comment by Anatoli-deBRADKE** [comment] 2022-06-24 15:24
I think this is related to snowflake bundle 2022_03 which has been activated by default in version 6.21 (June 22-23).
[https://community.snowflake.com/s/article/Pending-Behavior-Change-Log](https://community.snowflake.com/s/article/Pending-Behavior-Change-Log)

**Comment by simonepm** [comment] 2022-06-24 15:30
https://community.snowflake.com/s/article/show-shares-command-ui-data-sharing-changes

**Comment by simonepm** [comment] 2022-06-24 17:21
I see there is a pull request on the go to solve this issue:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1072

**Comment by gouline** [comment] 2022-06-29 08:27
Should be resolved in 0.37.0

**Comment by foresterr** [comment] 2023-05-09 14:07
What is the status of this, seeing how it's not closed although last comment says it should be resolved? 

We seem to be experiencing similar issue, in 0.63 version of the provider. Difference is, we are importing the share instead of creating it first, but after it is successfully imported, on the next run terraform reports share must be replaced due to change of name from <share_id> to <account_id>.<share_id>. Not sure if this would be the same issue or a new one. 

We are currently testing with a pretty ancient version of terraform (upgrade coming soon), but I don't think this is something that could be impacted by terraform version?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:45
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:45 UTC
Labels: bug
