### ISSUE TITLE
creating schema with for_each meta argument fails because array passed to 'DATA_RETENTION_TIME_IN_DAYS'

### ISSUE THREAD

**Issue by louis-vines** [Snowflake-Labs/terraform-provider-snowflake#611] opened 2021-07-20 10:08 UTC
**Provider Version**
0.25.10

**Terraform Version**
0.15

**Describe the bug**
When defining multiple schemas in one go using the `for_each` meta argument as so:

```
locals {
  schemas = [
    {
      database     = snowflake_database.databases["db_a"].name
      schema       = "schema_a"
      comment      = "a schema"
      is_transient = true
      data_retention_days = 14
    },
    {
      database     = snowflake_database.databases["db_b"].name
      schema       = "schema_b"
      comment      = "another schema"
      is_transient = true
      data_retention_days = 14
    },
  ]
}

resource "snowflake_schema" "schemas" {
  for_each = { for schema in local.schemas : schema.schema => schema }

  provider            = snowflake.sysadmin
  name                = each.value.schema
  database            = each.value.database
  is_transient        = each.value.is_transient
  data_retention_days = each.value.data_retention_days
  comment             = each.value.comment
  is_managed          = false
}
```
I'm getting the following error:
```
Error: error creating schema dw: 001008 (22023): SQL compilation error:
invalid value [14] for parameter 'DATA_RETENTION_TIME_IN_DAYS'
```

It appears that the go code is inadvertently passing an array of length 1 to the SQL code, as oppose to passing an integer, for the `data_retention_days` argument.

The same error occurs if I use a number directly in the resource decleration, i.e.:

```
resource "snowflake_schema" "schemas" {
  for_each = { for schema in local.schemas : schema.schema => schema }
  ...
  data_retention_days = 14
  ...
}
```
Am I doing something dumb or does this look like a bug?

**Expected behavior**
I should be able to define multiple schemas in one go using `snowflake_schema` resource in conjunction with the `for_each` meta argument - the value for `data_retention_days` should be correctly passed to the SQL declarations as an integer.

**Code samples and commands**

See above

**Comment by alldoami** [comment] 2021-07-20 21:05
Could you try this format:

```
locals {
  schema_map = {
    schema_a = {
      database     = snowflake_database.databases["db_a"].name
      schema       = "schema_a"
      comment      = "a schema"
      is_transient = true
      data_retention_days = 14
    },
    schema_b = {
      database     = snowflake_database.databases["db_b"].name
      schema       = "schema_b"
      comment      = "another schema"
      is_transient = true
      data_retention_days = 14
    },
  }
}

resource "snowflake_schema" "schema" {
  for_each          = local.schema_map

  provider            = snowflake.sysadmin
  name                = upper(each.key)
  database            = lookup(each.value, "database", null)
  is_transient        = lookup(each.value, "is_transient", null)
  data_retention_days = lookup(each.value, "data_retention_days", null)
  comment             = lookup(each.value, "comment", null)
  is_managed          = false
}
```

This is how we do it in our repo 😄

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:56
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:56 UTC
Labels: bug
