### ISSUE TITLE
[snowflake_account_grant] snowflake permission grant doesn't work as expected 

### ISSUE THREAD

**Issue by TienPham-Epi** [Snowflake-Labs/terraform-provider-snowflake#1462] opened 2023-01-10 04:15 UTC
**Provider Version**

v0.53.0

**Terraform Version**

v1.2.3

**Describe the bug**

For resource "snowflake_account_grant", it doesn't work when "privilege" is set to "CREATE DATABASE"

**Expected behavior**

Permission "CREATE DATABASE" doesn't apply to the snowflake role even terraform plan has confirmed this resource will be created

**Code samples and commands**

```
provider "snowflake" {
  alias = "security_admin"
  role  = "SECURITYADMIN"
}

resource "snowflake_role" "admin_conf_role" {
  provider = snowflake.security_admin
  name     = "test"
}

resource "snowflake_account_grant" "admin_conf_create_database" {
  provider          = snowflake.security_admin
  roles             = [snowflake_role.admin_conf_role.name]
  privilege         = "CREATE DATABASE"
  with_grant_option = false
}
```

**Output**
```
# module.snowflake_admin_account.snowflake_account_grant.admin_conf_create_database will be created
  + resource "snowflake_account_grant" "admin_conf_create_database" {
      + enable_multiple_grants = false
      + id                     = (known after apply)
      + privilege              = "CREATE DATABASE"
      + roles                  = [
          + "EDATA_ADMIN_CONF",
        ]
      + with_grant_option      = false
    }
```

**Comment by Relativity74205** [comment] 2023-02-22 08:54
@TienPham-Epi 
We had into the same problem. The solution for us was to create the resource with the account admin role, which is needed to create account grants.
The problem is actually Snowflake here. When running `GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE FOO`, the query is successful in Snowflake. You only get the message `Grant not executed: Insufficient privileges.`.

**Comment by sfc-gh-jcieslak** [comment] 2024-04-04 15:55
Hey 👋
Closing the issue as it's referring to the deprecated resource and we're not supporting them. Please, try to use the latest provider version with the non-deprecated resources (e.g. snowflake_grant_privileges_to_account_role). If the issue persists on the non-deprecated resource (or the feature is present in Snowflake, but not in the provider), please create a new GitHub issue. The [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) may help during migration to the latest resources. Here's a list of the latest, non-deprecated, grant resources:

Resources
[snowflake_grant_privileges_to_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_database_role)
[snowflake_grant_privileges_to_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_account_role)
[snowflake_grant_account_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_account_role)
[snowflake_grant_database_role](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_database_role)
snowflake_grant_application_role (coming soon)
[snowflake_grant_privileges_to_share](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_privileges_to_share)
snowflake_grant_ownership (coming soon)

Data sources
[snowflake_grants](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/grants)

**Closed by sfc-gh-jcieslak** 2024-04-04 15:55 UTC
Labels: bug
