### ISSUE TITLE
Cannot Import snowflake view with "terraform-provider-snowflake_v0.25.30"

### ISSUE THREAD

**Issue by kylasam** [Snowflake-Labs/terraform-provider-snowflake#970] opened 2022-04-11 20:09 UTC
**terraform-provider-snowflake_v0.25.30**

**Terraform v1.1.7**

**Plugin crashed when I'm trying to import a view from infrastructure**

**Should be able to successfully Import the view**

**terraform import -var snowflake_private_key=${SNOWFLAKE_INFRA_BOT_PRIVATE_KEY} -var snowflake_private_key_passphrase=${SNOWFLAKE_INFRA_BOT_PRIVATE_KEY_PASSPHRASE} snowflake_view.example 'dbName|schemaName|viewName'

Detailed Error:
snowflake_view.XXXXXXXXX: Importing from ID 'dbName|schemaName|viewName'...
snowflake_view.XXXXXXXXX: Import prepared!
  Prepared snowflake_view for import
snowflake_view.XXXXXXXXX: Refreshing state... [id='dbName|schemaName|viewName']
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.25.30 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 14 [running]:
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.(*ViewSelectStatementExtractor).consumeToken(0xc0007e3838, {0x1cdc8aa, 0x1cfc86a})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/parser.go:96 +0x148
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.(*ViewSelectStatementExtractor).Extract(0xc0007e3838)
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/parser.go:30 +0x9b
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadView(0xc000718a80, {0x1cc8880, 0xc00039a000})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/view.go:181 +0x52d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1cdc43c, {0x1ecf318, 0xc000318640}, 0x24, {0x1cc8880, 0xc00039a000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:335 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0007676c0, {0x1ecf318, 0xc000318640}, 0xc00071ac30, {0x1cc8880, 0xc00039a000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:624 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000716090, {0x1ecf318, 0xc000318640}, 0xc000318680)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00070c6e0, {0x1ecf3c0, 0xc0007a01e0}, 0xc000522120)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x1fb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1c93f00, 0xc00070c6e0}, {0x1ecf3c0, 0xc0007a01e0}, 0xc0005220c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00071e700, {0x1ee15b0, 0xc0000d4000}, 0xc000736000, 0xc0004ca510, 0x261aa70, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00071e700, {0x1ee15b0, 0xc0000d4000}, 0xc000736000, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-snowflake_v0.25.30 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Could you please confirm is this an expected behaviour?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:47
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:47 UTC
Labels: bug
