### ISSUE TITLE
snowflake share does not work

### ISSUE THREAD

**Issue by drop-wisdom** [Snowflake-Labs/terraform-provider-snowflake#679] opened 2021-09-13 18:39 UTC
**Provider Version**

0.25.17

**Terraform Version**

1.0.2

**Describe the bug**
In snowflake_share, accounts are optional. accounts (List of String) A list of accounts to be added to the share.  But I never will be able to run through this if I add the accounts parameter, it says query format error.  When I checked the snowflake share document https://docs.snowflake.com/en/sql-reference/sql/create-share.html, create share does not accept accounts when create.  Looks like it requires create_share first and alter share to add accounts.  So does that mean that the resource snowflake_share needs to do both create and alter share so that I can add accounts?

**Comment by philkpler** [comment] 2021-11-24 13:17
Any updates on that ?
I'm experiencing also some difficulties with shares configuration through terraform...

**Comment by VickyWinner** [comment] 2023-06-08 12:45
Just came here while searching.  is this resolved?

**Comment by danieladams456** [comment] 2023-06-30 16:03
I found that the accounts had to be added uppercase `ORG.ACCT` instead of `org.acct`.  Account locator `ORG_ACCT` works in SQL but not allowed in TF.

@drop-wisdom it looks like the TF resource creates and alters the share.  It also creates and assigns a temporary database since having an attached DB seems to be a requirement for modifying.

**Comment by rumbin** [comment] 2023-07-31 16:21
Maybe a bit off-topic, but I think this is still the best resource to ask:
How do we assign grants on DBs/schemas,... (or a role which bundles these) to a TF-managed share? I haven't found anything on this in the docs.

**Comment by philkpler** [comment] 2023-07-31 16:35
> Maybe a bit off-topic, but I think this is still the best resource to ask: How do we assign grants on DBs/schemas,... (or a role which bundles these) to a TF-managed share? I haven't found anything on this in the docs.
It's up to the user importing your share to define his role/grants logic, unless I miss understood the question? 

I don't know if it can help you but we eventually managed some small parts of our infra manually (ie: reference_usage for some DBs, list of accounts in a share), but still "declaring" it in the .tf to keep everything in sync, so terraform doesn't complain when applying : the "least worst" solution

**Comment by rumbin** [comment] 2023-07-31 19:17
@philkpler Thank you for replying to my question.
In essence, I am looking for how we can grant access on objects to the share on the account where the share is created.
Here is an example of how we may do this in plain SQL:

```
create share lake;
-- these grants don't seem to be covered in Terraform:
grant usage on database lake to share lake;
grant usage on all schemas in database lake to share lake;
grant select on table lake.driving.telemetry to share lake;
-- this one is covered in Terraform:
alter share lake add accounts=GX12345;
```

It would be so great if you could point me to how I can achieve this.

**Comment by philkpler** [comment] 2023-08-01 08:37
Share definition

```
resource "snowflake_share" "my_share" {
  name     = "MY_SHARE"

  accounts = [
    "TOTO.ABCD123",                          
    "TITI.GHJ456",
    "TUTU.IUP147
  ]
}
```
 
Grants on my main db and one of its schema to the share

```
resource "snowflake_database_grant" "my_share_db_grants" {

  database_name = snowflake_database.my_db.name (1)

  privilege = "USAGE"

  shares = [
    snowflake_share.my_share.name,
  ]

  depends_on = [
    snowflake_share.my_share,
    snowflake_database.my_db,
  ]
}

resource "snowflake_schema_grant" "my_share_schema_grants" {

  database_name = snowflake_database.my_db.name
  schema_name   = snowflake_schema.my_schema.name (2)

  privilege = "USAGE"

  shares = [
    snowflake_share.my_share.name,
  ]

  depends_on = [
    snowflake_share.my_share,
    snowflake_database.my_db,
    snowflake_schema.my_schema,
  ]
}
```

Grants on an other db (just in case you'd need it)
Here you must grant REFERENCE_USAGE, because a share can only have one db granted with "USAGE" 
https://docs.snowflake.com/en/user-guide/data-sharing-mutiple-db.html#sharing-data-from-multiple-databases
```
resource "snowflake_database_grant" "my_share_other_db_grants" {

  database_name = snowflake_database.my_other_db.name (3)

  privilege = "REFERENCE_USAGE"

  shares = [
    snowflake_share.my_share.name,
  ]

  depends_on = [
    snowflake_share.my_share,
    snowflake_database.my_other_db,
  ]
}
```

(1), (2), (3) are defined in an other files

You might need to define a provider (in my case I have a default one and when the share are created on replicas I have alternatives ones that specify to override the default one).

As I said in my previous message, some things don't work out of the box with the terraform plugin (at least with the version I use), hence the need to run some command manually.
ie :  adding an account to an existing share, especially when more than 3 or 4 (I don't remember). In this case, I run manually the same command as you (alter share...) and then I update my tf. file in order to keep the terraform resource in sync.

Hope it helped.

**Comment by rumbin** [comment] 2023-08-01 11:02
@philkpler This is so great! Thank you for sharing your knowledge with me and the community :-)

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:54
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:54 UTC
Labels: bug
