### ISSUE TITLE
[Bug] SNOW-1865901: Error: 260000: account is empty with usage auth with profile. snowflake provider v1.0.0

### ISSUE THREAD

**Issue by Zarubenko** [Snowflake-Labs/terraform-provider-snowflake#3308] opened 2024-12-19 21:33 UTC
### Terraform CLI Version

1.8.2

### Terraform Provider Version

1.0.0

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "1.0.0"
    }
  }
}
provider "snowflake" {
    profile = "myprofile"
}
```

### Category

category:provider_config

### Expected Behavior

working "terraform apply" command

### Actual Behavior

│ Error: 260000: account is empty
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on versions.tf line 19, in provider "snowflake":
│   19: provider "snowflake" {
│ 

### Steps to Reproduce

1. create config file  ~/.snowflake/config
```
[myprofile]
account = 'accountname'
user = 'username'
password = 'password'
role = 'rolename'
```

2. setup provider:
```
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "1.0.0"
    }
  }
}
provider "snowflake" {
    profile = "myprofile"
}
```

### How much impact is this issue causing?

Medium

### Additional Information

I also tried using the variables "account_name" and "accountname" in the profile.
In version 0.100.0 and oldest all work fine with this setup.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-dszmolka** [comment] 2024-12-20 12:06
hi - thanks for reporting this issue. reproduced it and it seems to happen because we seem to have removed the possibility of using account locators (`xy12345.eu-central-1`) as an account identifier, and now exclusively allow only for the regionless notation (`myorg-myaccount`) . 

in this sense, your issue is the same as https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3198

using this profile
```
[myprofile]
organizationname = 'MYORG'
accountname = 'MYACCOUNT'
user = 'admin'
password = 'password'
role = 'role'
```

seems to work for me, can you please test ? To get your organization name and account (alias) name to use in the config, please  execute `SELECT CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT_NAME();` in your Snowflake GUI.

**Comment by sfc-gh-asawicki** [comment] 2024-12-20 12:14
Adding for visibility: deprecation and later removal were both concluded in the migration guide [here](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#behavior-change-deprecated-fields) and [here](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#removed-deprecated-objects).

**Comment by Zarubenko** [comment] 2024-12-23 00:46
Thanks @sfc-gh-dszmolka @sfc-gh-asawicki for speedily answer.
`[myprofile]
organizationname = 'MYORG'
accountname = 'MYACCOUNT'
user = 'admin'
password = 'password'
role = 'role'`
it's work

**Comment by sfc-gh-dszmolka** [comment] 2024-12-23 07:44
sounds good ! we also extended the FAQ a little bit with this specific error message. closing this issue now.

**Closed by sfc-gh-dszmolka** 2024-12-23 07:44 UTC
Labels: general-usage, category:provider_config, status-triage_done, category:migration

**Comment by rjminchuk** [comment] 2025-02-03 18:51
I am also getting the `260000: account is empty` error, and I am using the account locator format (xy12345.us-east-1.aws) RE: https://docs.snowflake.com/en/user-guide/admin-account-identifier#format-2-account-locator-in-a-region

I previously had SNOWFLAKE_ACCOUNT and SNOWFLAKE_REGION set in my environment.

I've tried setting SNOWFLAKE_ACCOUNT_NAME="xy12345" and SNOWFLAKE_ORGANIZATION_NAME="ASDFGHJ" but am getting a failure: 

```
open snowflake connection: 261004 (08004): failed to auth for unknown reason. HTTP: 404, URL: https://<REDACTED>-<REDACTED>.snowflakecomputing.com:443
```

**Comment by rjminchuk** [comment] 2025-02-03 19:54
> I am also getting the `260000: account is empty` error, and I am using the account locator format (xy12345.us-east-1.aws) RE: https://docs.snowflake.com/en/user-guide/admin-account-identifier#format-2-account-locator-in-a-region
> 
> I previously had SNOWFLAKE_ACCOUNT and SNOWFLAKE_REGION set in my environment.
> 
> I've tried setting SNOWFLAKE_ACCOUNT_NAME="xy12345" and SNOWFLAKE_ORGANIZATION_NAME="ASDFGHJ" but am getting a failure:
> 
> ```
> open snowflake connection: 261004 (08004): failed to auth for unknown reason. HTTP: 404, URL: https://<REDACTED>-<REDACTED>.snowflakecomputing.com:443
> ```

Ignore me! Resolved in another issue. https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3369
