### ISSUE TITLE
0.56.4 crashes on grants

### ISSUE THREAD

**Issue by bennylu2** [Snowflake-Labs/terraform-provider-snowflake#1547] opened 2023-02-17 18:04 UTC
**Provider Version**

`0.56.4`

**Terraform Version**

`1.3.4`

**Describe the bug**
Provider crashes for any states with grants

```
Stack trace from the terraform-provider-snowflake_v0.56.4 plugin:
panic: runtime error: index out of range [1] with length 1
goroutine 995 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.parseProcedureGrantID({0xc0009fa0c0, 0x3a})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/procedure_grant.go:362 +0x5e6
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadProcedureGrant(0xc0003fab00, {0x12edfc0, 0xc0007b8f70})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/procedure_grant.go:190 +0xd1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x155da80?, {0x155da80?, 0xc0007c0ae0?}, 0xd?, {0x12edfc0?, 0xc0007b8f70?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00083afc0, {0x155da80, 0xc0007c0ae0}, 0xc0007b8a90, {0x12edfc0, 0xc0007b8f70})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00082c348, {0x155da80?, 0xc0007c09c0?}, 0xc0005b8240)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00040f9a0, {0x155da80?, 0xc000766780?}, 0xc00093a540)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x12ba500?, 0xc00040f9a0}, {0x155da80, 0xc000766780}, 0xc0005b23f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000834000, {0x1563720, 0xc0006029c0}, 0xc0007c6000, 0xc000461aa0, 0x1d03e90, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000834000, {0x1563720, 0xc0006029c0}, 0xc0007c6000, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
Error: The terraform-provider-snowflake_v0.56.4 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**

No crash

Appears to have been released in #1519 and #1522

**Comment by sfc-gh-swinkler** [comment] 2023-02-17 22:59
@bennylu2 can you please provide more information? Specifically I would like the result of `terraform state show` on this resource, and your current configuration code for how you are using the procedure grant resource. This is most likely a problem of the IDs having changed, and it is not able to correctly read the old IDs any longer.

The changes in the last PR were to fix import issues with grant resources, and also to have each grant resource manage its own IDs rather than using a single shared ID method. So if there is a problem with this one particular grant resource then I am confident we can fix it without having cascading effects on other grant resources, which was a huge problem in the past.

**Comment by bennylu2** [comment] 2023-02-17 23:54
state show
```
tf state show 'module.martech_schema.snowflake_procedure_grant.this["USAGE"]'                                                                                     
# module.martech_schema.snowflake_procedure_grant.this["USAGE"]:
resource "snowflake_procedure_grant" "this" {
    argument_data_types    = []
    database_name          = "TDM_MARTECH"
    enable_multiple_grants = true
    id                     = "TDM_MARTECH|MARTECH||USAGE|TDM_MARTECH__MARTECH__WRITE|false"
    on_future              = true
    privilege              = "USAGE"
    roles                  = [
        "TDM_MARTECH__MARTECH__WRITE",
    ]
    schema_name            = "MARTECH"
    with_grant_option      = false
}
```

config
```
resource "snowflake_procedure_grant" "this" {
  for_each = transpose(local.grants_procedure)

  database_name          = snowflake_schema.this.database
  schema_name            = snowflake_schema.this.name
  privilege              = each.key
  roles                  = each.value
  on_future              = true
  with_grant_option      = false
  enable_multiple_grants = true # needed until we sunset database migrations
}
```

**Comment by bennylu2** [comment] 2023-02-17 23:55
Getting these errors on all grants as well

```
│ Error: Request cancelled
│ 
│   with module.tdm_martech.module.public_schemas["MODELED"].module.stage_this["READ"].snowflake_stage_grant.this,
│   on .terraform/modules/tdm_martech/tdm/modules/stage-grant/main.tf line 1, in resource "snowflake_stage_grant" "this":
│    1: resource "snowflake_stage_grant" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.tdm_martech.module.public_schemas["MODELED"].module.stage_this["USAGE"].snowflake_stage_grant.this,
│   on .terraform/modules/tdm_martech/tdm/modules/stage-grant/main.tf line 1, in resource "snowflake_stage_grant" "this":
│    1: resource "snowflake_stage_grant" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.tdm_martech.module.public_schemas["SUMMARIZED"].module.stage_this["READ"].snowflake_stage_grant.this,
│   on .terraform/modules/tdm_martech/tdm/modules/stage-grant/main.tf line 1, in resource "snowflake_stage_grant" "this":
│    1: resource "snowflake_stage_grant" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

...
```

**Comment by sfc-gh-swinkler** [comment] 2023-02-18 00:16
Thank you. I will look into this now.

**Comment by sfc-gh-swinkler** [comment] 2023-02-18 00:41
Okay so i have a fix for the first issue in pr #1550 

As for the other issue, i will need additional information on that as well. If you could please provide the state and configuration information like you did with the procedure grant resource, that would be most helpful.

**Comment by bennylu2** [comment] 2023-02-18 00:57
They are essentially the same config and state but different grant resource so you should be able to infer them. I can provide if still needed but will be till next week

**Comment by sfc-gh-swinkler** [comment] 2023-02-18 01:01
Okay i will try, and if there are any issues then we can resolve next week.

**Comment by bennylu2** [comment] 2023-02-18 18:03
Here's two more resource states and configs, again they are all very similar so should be able to be inferred

state show

```
tf state show 'module.martech_schema.snowflake_stream_grant.this["SELECT"]' 
# module.martech_schema.snowflake_stream_grant.this["SELECT"]:
resource "snowflake_stream_grant" "this" {
    database_name          = "TDM_MARTECH"
    enable_multiple_grants = true
    id                     = "TDM_MARTECH|MARTECH||SELECT|TDM_MARTECH__MARTECH__READ|false"
    on_future              = true
    privilege              = "SELECT"
    roles                  = [
        "TDM_MARTECH__MARTECH__READ",
    ]
    schema_name            = "MARTECH"
    with_grant_option      = false
}

tf state show 'module.martech_schema.snowflake_task_grant.this["MONITOR"]'                                                             
# module.martech_schema.snowflake_task_grant.this["MONITOR"]:
resource "snowflake_task_grant" "this" {
    database_name          = "TDM_MARTECH"
    enable_multiple_grants = true
    id                     = "TDM_MARTECH|MARTECH||MONITOR|TDM_MARTECH__MARTECH__READ|false"
    on_future              = true
    privilege              = "MONITOR"
    roles                  = [
        "TDM_MARTECH__MARTECH__READ",
    ]
    schema_name            = "MARTECH"
    with_grant_option      = false
}
```


config

```
resource "snowflake_stream_grant" "this" {
  for_each = transpose(local.grants_stream)

  database_name          = snowflake_schema.this.database
  schema_name            = snowflake_schema.this.name
  privilege              = each.key
  roles                  = each.value
  on_future              = true
  with_grant_option      = false
  enable_multiple_grants = true
}

resource "snowflake_task_grant" "this" {
  for_each = transpose(local.grants_task)

  database_name          = snowflake_schema.this.database
  schema_name            = snowflake_schema.this.name
  privilege              = each.key
  roles                  = each.value
  on_future              = true
  with_grant_option      = false
  enable_multiple_grants = true
}
```

**Comment by idiaz-at-globant** [comment] 2023-02-21 15:19
Hello Snowflake team, I've same reporte error:
```
│   on role_grant.tf line 11, in resource "snowflake_role_grants" "role_grants":
│   11: resource "snowflake_role_grants" "role_grants" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with snowflake_role_grants.role_grants["EXAMPLE"],
│   on role_grant.tf line 11, in resource "snowflake_role_grants" "role_grants":
│   11: resource "snowflake_role_grants" "role_grants" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│ 
│   with snowflake_schema.schema["EXAMPLEDB"],
│   on [schemas.tf](http://schemas.tf/) line 19, in resource "snowflake_schema" "schema":
│   19: resource "snowflake_schema" "schema" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-snowflake_v0.56.4 plugin:
panic: runtime error: index out of range [4] with length 1
goroutine 351 [running]:
[github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.parseRoleGrantsID](http://github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.parseRoleGrantsID)({0xc000403968, 0x14})
	[github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_grants.go:324](http://github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_grants.go:324) +0x2fa
[github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadRoleGrants](http://github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadRoleGrants)(0xc000642500, {0x12edfc0?, 0xc000191860})
	[github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_grants.go:110](http://github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_grants.go:110) +0x107
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource)).read(0x155da80?, {0x155da80?, 0xc000c20b40?}, 0xd?, {0x12edfc0?, 0xc000191860?})
	[github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712) +0x178
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource)).RefreshWithoutUpgrade(0xc00050f180, {0x155da80, 0xc000c20b40}, 0xc0009bc0d0, {0x12edfc0, 0xc000191860})
	[github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015) +0x585
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer)).ReadResource(0xc000494360, {0x155da80?, 0xc000c20a20?}, 0xc000815c40)
	[github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613) +0x4a5
[github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server](http://github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server)).ReadResource(0xc0004079a0, {0x155da80?, 0xc000c20450?}, 0xc00059fbc0)
	[github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748](http://github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748) +0x4b1
[github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler](http://github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler)({0x12ba500?, 0xc0004079a0}, {0x155da80, 0xc000c20450}, 0xc00082ad90, 0x0)
	[github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349](http://github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349) +0x170
[google.golang.org/grpc.(*Server](http://google.golang.org/grpc.(*Server)).processUnaryRPC(0xc00050c000, {0x1563720, 0xc000102b60}, 0xc0009fbd40, 0xc000517560, 0x1d03e90, 0x0)
	[google.golang.org/grpc@v1.50.1/server.go:1340](http://google.golang.org/grpc@v1.50.1/server.go:1340) +0xd23
[google.golang.org/grpc.(*Server](http://google.golang.org/grpc.(*Server)).handleStream(0xc00050c000, {0x1563720, 0xc000102b60}, 0xc0009fbd40, 0x0)
	[google.golang.org/grpc@v1.50.1/server.go:1713](http://google.golang.org/grpc@v1.50.1/server.go:1713) +0xa2f
[google.golang.org/grpc.(*Server](http://google.golang.org/grpc.(*Server)).serveStreams.func1.2()
	[google.golang.org/grpc@v1.50.1/server.go:965](http://google.golang.org/grpc@v1.50.1/server.go:965) +0x98
created by [google.golang.org/grpc.(*Server](http://google.golang.org/grpc.(*Server)).serveStreams.func1
	[google.golang.org/grpc@v1.50.1/server.go:963](http://google.golang.org/grpc@v1.50.1/server.go:963) +0x28a
Error: The terraform-provider-snowflake_v0.56.4 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
time=2023-02-17T17:50:36Z level=error msg=1 error occurred:
	* exit status 1
```

**Comment by sfc-gh-swinkler** [comment] 2023-02-21 18:15
So current fix will be released within a few hours as part of 0.56.5. My apologies, I forgot that Monday was an American holiday.

@bennylu2 regarding the other error you reported for stream and task grants, i was not able to replicate. My process was 1) deploy resources using 0.56.1, then upgrade to 0.56.5 (not yet released). No issues were encountered. I believe the source cause of the problem is the procedure grant that then force cancels all other resources that are currently running. Since it is not a gracefully exiting error, after all. Anyhow, once 0.56.5 is released, please test and let me know if the other error persists.

**Comment by joshtree41** [comment] 2023-02-21 20:19
Hi Snowflake team, I've been noticing some similar errors:

(Using snowflake 0.56.5, terraform 1.3.9)

```
Stack trace from the terraform-provider-snowflake_v0.56.5 plugin:

panic: runtime error: index out of range [4] with length 1

goroutine 778 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.parseRoleGrantsID({0xc00059c1b0, 0x11})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_grants.go:324 +0x2fa
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadRoleGrants(0xc00019a400, {0x1eb5c80?, 0xc00056cd00})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_grants.go:110 +0x107
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x211cce0?, {0x211cce0?, 0xc00052b140?}, 0xd?, {0x1eb5c80?, 0xc00056cd00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000fcfc0, {0x211cce0, 0xc00052b140}, 0xc000826410, {0x1eb5c80, 0xc00056cd00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00045a3c0, {0x211cce0?, 0xc00052b020?}, 0xc00074e280)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0003a0a00, {0x211cce0?, 0xc00052a360?}, 0xc000ca61e0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1e829c0?, 0xc0003a0a00}, {0x211cce0, 0xc00052a360}, 0xc00023a0e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00046c000, {0x2122800, 0xc000602820}, 0xc000c065a0, 0xc00046e210, 0x28a6c90, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00046c000, {0x2122800, 0xc000602820}, 0xc000c065a0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-snowflake_v0.56.5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintain
```

**Comment by PedroMartinSteenstrup** [comment] 2023-02-23 15:35
As soon as we merged the update from 0.56.3 to 0.56.5 we started having the same error.

terragrunt version v0.43.1
Terraform v1.3.7 on darwin_arm64
+ provider registry.terraform.io/aidanmelen/snowsql v1.3.0
+ provider registry.terraform.io/hashicorp/aws v4.55.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/snowflake-labs/snowflake v0.56.5

```
...
snowflake_role_grants.this_user_role_grant["ORGADMIN"]: Refreshing state... [id=ORGADMIN]
snowflake_role_grants.this_user_role_grant["DEVELOPER"]: Refreshing state... [id=DEVELOPER]
╷
│ Error: Plugin did not respond
│ 
│   with snowflake_role_grants.this_user_role_grant["DEVELOPER"],
│   on main.tf line 56, in resource "snowflake_role_grants" "this_user_role_grant":
│   56: resource "snowflake_role_grants" "this_user_role_grant" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
[...50 more like this...]
╷
│ Error: Request cancelled
│ 
│   with snowflake_role_grants.this_user_role_grant["TRANSFORMER"],
│   on main.tf line 56, in resource "snowflake_role_grants" "this_user_role_grant":
│   56: resource "snowflake_role_grants" "this_user_role_grant" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-snowflake_v0.56.5 plugin:

panic: runtime error: index out of range [4] with length 1

goroutine 1009 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.parseRoleGrantsID({0x14000855bd0, 0xb})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_grants.go:324 +0x2bc
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadRoleGrants(0x14000536880, {0x1011907a0?, 0x14000845450})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_grants.go:110 +0xd8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1011ba660?, {0x1011ba660?, 0x140005ff440?}, 0xd?, {0x1011907a0?, 0x14000845450?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140003b2d20, {0x1011ba660, 0x140005ff440}, 0x140005abd40, {0x1011907a0, 0x14000845450})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140000d4228, {0x1011ba660?, 0x140005ff290?}, 0x140007fde80)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400041a1e0, {0x1011ba660?, 0x140005fec30?}, 0x14000d05b60)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x10115d4e0?, 0x1400041a1e0}, {0x1011ba660, 0x140005fec30}, 0x14000524f50, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000d6000, {0x1011c00a0, 0x14000502b60}, 0x14000928360, 0x140003adf20, 0x10191cab0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x140000d6000, {0x1011c00a0, 0x14000502b60}, 0x14000928360, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x290

Error: The terraform-provider-snowflake_v0.56.5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0030] Terraform invocation failed in /Users/martin/terraform/snowflake/users/human-users/.terragrunt-cache/PmK8GB8ZHXmo7bJa0ie4O0MmrS0/owk-vZqk2A7kkcmQTQa3Asf7qCo/modules/users  prefix=[/Users/martin/terraform/snowflake/users/human-users] 
ERRO[0030] 1 error occurred:
        * exit status 1
```

**Comment by sfc-gh-swinkler** [comment] 2023-03-01 00:50
This has been fixed, please open follow up PR if there is still an issue.

**Closed** 2023-03-01 00:49 UTC
Labels: bug

**Comment by PedroMartinSteenstrup** [comment] 2023-03-01 12:05
> This has been fixed, please open follow up PR if there is still an issue.

https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1588
