### ISSUE TITLE
[Bug]: snowflake_grant_database_role doesn't grant to database roles

### ISSUE THREAD

**Issue by bkimjin** [Snowflake-Labs/terraform-provider-snowflake#3309] opened 2024-12-19 22:08 UTC
### Terraform CLI Version

1.9.5

### Terraform Provider Version

0.99.0

### Terraform Configuration

```terraform
resource "snowflake_database_role" "database_role" {
  database = var.database
  name     = var.database_role_name
}

resource "snowflake_database_role" "parent_database_role" {
  database = var.database
  name     = var.parent_database_role_name
}

resource "snowflake_grant_database_role" "g" {
  database_role_name        = "\"${var.database}\".\"${snowflake_database_role.database_role.name}\""
  parent_database_role_name = "\"${var.database}\".\"${snowflake_database_role.parent_database_role.name}\""
}
```

### Category

category:resource

### Object type(s)

resource:grant_database_role

### Expected Behavior

Create a Snowflake query that follows this format:
```GRANT DATABASE ROLE "DATABASE_NAME"."CHILD_DATABASE_ROLE" TO DATABASE ROLE "DATABASE_NAME"."PARENT_DATABASE_ROLE";```

### Actual Behavior

```GRANT DATABASE ROLE "DATABASE_NAME"."CHILD_DATABASE_ROLE" TO ROLE "DATABASE_NAME.PARENT_DATABASE_ROLE";```

### Steps to Reproduce

1. copy the configuration
2. run terraform apply

### How much impact is this issue causing?

Medium

### Additional Information

Current workaround is to use snowflake_unsafe_executes 

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment] 2024-12-20 11:40
Hi @bkimjin 👋 

I can't reproduce this issue. Please provide logs with `TF_LOG=DEBUG`.

Also, `fully_qualified_name` field is now recommended, like this:
```
resource "snowflake_grant_database_role" "g" {
  database_role_name        = snowflake_database_role.database_role.fully_qualified_name
  parent_database_role_name = snowflake_database_role.parent_database_role.fully_qualified_name
}
```
We'll update the docs.

**Comment by bkimjin** [comment] 2024-12-20 16:36
It looks like this was a user error. I mistakenly used `parent_role_name` instead of `parent_database_role_name`.

**Comment by sfc-gh-asawicki** [comment] 2024-12-23 17:04
Great to hear that @bkimjin. Is there anything left to solve in this issue or can we close it? :)

**Comment by bkimjin** [comment] 2024-12-23 17:40
I'll go ahead and close, thanks!

**Closed** 2024-12-23 17:41 UTC
Labels: general-usage
