### ISSUE TITLE
[Feature]: Grant DATASETS usage to a role through terraform

### ISSUE THREAD

**Issue by GomathiMa** [Snowflake-Labs/terraform-provider-snowflake#2807] opened 2024-05-15 16:09 UTC
### Use Cases or Problem Statement

Unable to see the terraform script/syntax for below snowflake grants

GRANT USAGE ON FUTURE DATASETS IN SCHEMA IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);
GRANT USAGE ON ALL DATASETS IN IDENTIFIER($SCHEMA_FQN) TO ROLE IDENTIFIER($FS_ROLE_CONSUMER);

### Category

category:grants

### Object type(s)

resource:grant_privileges_to_account_role

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jcieslak** [comment] 2024-05-16 08:27
Hey @GomathiMa 👋 
I'm not familiar with dataset objects, also couldn't find them in the documentation. Is that a preview feature?

**Comment by GomathiMa** [comment] 2024-05-16 12:16
I think, that is a preview feature

**Comment by sfc-gh-jcieslak** [comment] 2024-05-21 10:14
Hey, I'll try to add it with some other changes. I'll let you know when it will be released.

**Comment by sfc-gh-jcieslak** [comment] 2024-09-05 09:49
Hey @Covid-taskforce-veneficus 👋
Yesterday, we released a new provider version ([v0.95.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.95.0)). Please upgrade and let us know if now you can grant privileges on future datasets.

**Comment by sfc-gh-jcieslak** [comment] 2024-10-15 14:21
Closing due to long inactivity. Please, create another issue if you think the problem is still not resolved.

**Closed by sfc-gh-jcieslak** 2024-10-15 14:21 UTC
Labels: feature-request, category:grants
