### ISSUE TITLE
snowflake_warehouse fails when creating warehouse with lowercase name and underscores

### ISSUE THREAD

**Issue by dpp23** [Snowflake-Labs/terraform-provider-snowflake#774] opened 2021-11-30 19:22 UTC
**Provider Version**
```
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.25.28"
    }
```
The provider version you are using.

**Terraform Version**

1.0.6

**Describe the bug**

When creating a warehouse with a resource like this:

```
resource "snowflake_warehouse" "main_warehouse" {
  name           = "test_test"
  size              = "small"
```
I get the following error:

```
│ Error: 002003 (02000): SQL compilation error:
│ Warehouse 'TEST_TEST' does not exist or not authorized.
```

The warehouse is actually getting created, but I think the failure is when trying to query the status of it after.

**Expected behavior**

Either the name validation stops from creating a warehouse the provider can manage or ensure that the capitalization is adhered to when checking the status of the warehouse.

**Comment by alldoami** [comment] 2021-12-16 23:51
Is there a reason why you're naming it with lowercase? All snowflake objects are uppercase so this will cause issues if you try and query it with lowercase to begin with.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:51
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:51 UTC
Labels: bug
