### ISSUE TITLE
Plugin crash on any version >= 0.86.0

### ISSUE THREAD

**Issue by deanmorin** [Snowflake-Labs/terraform-provider-snowflake#2694] opened 2024-04-10 21:25 UTC
### Terraform CLI and Provider Versions

```
2024-04-10T14:18:34.750-0700 [INFO]  Terraform version: 1.7.5
2024-04-10T14:18:34.750-0700 [DEBUG] using github.com/hashicorp/go-tfe v1.41.0
2024-04-10T14:18:34.750-0700 [DEBUG] using github.com/hashicorp/hcl/v2 v2.19.1
2024-04-10T14:18:34.750-0700 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-04-10T14:18:34.750-0700 [DEBUG] using github.com/zclconf/go-cty v1.14.1
2024-04-10T14:18:34.750-0700 [INFO]  Go runtime version: go1.21.8
2024-04-10T14:18:34.750-0700 [INFO]  CLI args: []string{"/usr/local/Cellar/tfenv/3.0.0/versions/1.7.5/terraform", "version"}
2024-04-10T14:18:34.750-0700 [TRACE] Stdout is a terminal of width 119
2024-04-10T14:18:34.750-0700 [TRACE] Stderr is a terminal of width 119
2024-04-10T14:18:34.750-0700 [TRACE] Stdin is a terminal
2024-04-10T14:18:34.750-0700 [DEBUG] Attempting to open CLI config file: /Users/dean/.terraformrc
2024-04-10T14:18:34.750-0700 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2024-04-10T14:18:34.750-0700 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-04-10T14:18:34.750-0700 [DEBUG] ignoring non-existing provider search directory /Users/dean/.terraform.d/plugins
2024-04-10T14:18:34.750-0700 [DEBUG] ignoring non-existing provider search directory /Users/dean/Library/Application Support/io.terraform/plugins
2024-04-10T14:18:34.750-0700 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2024-04-10T14:18:34.751-0700 [INFO]  CLI command args: []string{"version"}
Terraform v1.7.5
on darwin_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.88.0
```

### Terraform Configuration

```terraform
terraform {
  backend "s3" {
    bucket         = "my-bucket"
    dynamodb_table = "my-bucket-lock"
    encrypt        = true
    key            = "snowflake.tfstate"
    region         = "us-east-1"
    profile        = "my-profile"
  }

  required_providers {
    snowflake = {
      source = "Snowflake-Labs/snowflake"
    }
  }
}

provider "snowflake" {
  role          = "ACCOUNTADMIN"
  account       = "my-account"
  authenticator = "ExternalBrowser"
  warehouse     = "TERRAFORM"
}
```

### Expected Behavior

Can apply terraforms as normal.

### Actual Behavior

The plugin crashes when trying to run the plan.

This happens in all versions >= 0.86.0. I'm running on an intel mac, but got someone on an M1 mac to confirm they're also seeing the same issue.

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Warning: Deprecated Resource
│
│   with module.snowflake.snowflake_schema_grant.my_db_my_schema_usage,
│   on ../../../modules/snowflake/my_db.tf line 31, in resource "snowflake_schema_grant" "my_db_my_schema_usage":
│   31: resource "snowflake_schema_grant" "my_db_my_chema_usage" {
│
│ This resource is deprecated and will be removed in a future major version release. Please use
│ snowflake_grant_privileges_to_account_role instead.
│
│ (and 212 more similar warnings elsewhere)
╵
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The
│ plugin logs may contain more details.
╵

THESE 2 ABOVE ERRORS ARE REPEATED MANY TIMES

Stack trace from the terraform-provider-snowflake_v0.88.0 plugin:

panic: interface conversion: interface {} is bool, not string

goroutine 313 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.v085ExternalFunctionStateUpgrader({0x0?, 0x0?}, 0xc000c9f860, {0x0?, 0x0?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/external_function_state_upgraders.go:72 +0x5d7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).upgradeJSONState(0xc000bfe540, {0x102036848, 0xc000e8df80}, 0xd?, 0x101cc0ba4?, 0x14?)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:487 +0x75
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).UpgradeResourceState(0xc000bfe540, {0x102036848?, 0xc000e8de60?}, 0xc0016973c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:363 +0x3fa
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.UpgradeResourceState({{0x10204c5a0?, 0xc000bfe540?}}, {0x102036848?, 0xc000e8de60?}, 0xc001697360?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:198 +0x142
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).UpgradeResourceState(0x102036880?, {0x102036848?, 0xc000e8db60?}, 0xc001697360)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_UpgradeResourceState.go:36 +0x19f
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).UpgradeResourceState(0xc000c5e3c0, {0x102036848?, 0xc000e8d350?}, 0xc0016a3130)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:755 +0x258
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_UpgradeResourceState_Handler({0x101c10c20?, 0xc000c5e3c0}, {0x102036848, 0xc000e8d350}, 0xc000147000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:431 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000144d20, {0x102036848, 0xc000e8d020}, {0x102047880, 0xc000557860}, 0xc0008e87e0, 0xc000aab140, 0x1030301b8, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc000144d20, {0x102047880, 0xc000557860}, 0xc0008e87e0)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 33
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x115

Error: The terraform-provider-snowflake_v0.88.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-asawicki** [comment] 2024-04-11 06:00
Hey @deanmorin. Thanks for reaching out to us.

It looks like one of the cases of state migration is mishandled. I will try to reproduce it today, and if I'm right, the fix will be pretty straightforward and will be released with the next version of the provider.

**Comment by sfc-gh-asawicki** [comment] 2024-04-18 13:11
Hey @deanmorin. We have released a new version with a fix: https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.89.0. Please bump and confirm.

**Comment by deanmorin** [comment] 2024-04-18 16:20
@sfc-gh-asawicki Confirmed, thank you!

**Closed** 2024-04-18 16:22 UTC
Labels: bug
