### ISSUE TITLE
Failure Adding Expression Column to Existing Table

### ISSUE THREAD

**Issue by crowemi** [Snowflake-Labs/terraform-provider-snowflake#865] opened 2022-02-18 16:32 UTC
**Provider Version**

registry.terraform.io/chanzuckerberg/snowflake v0.25.36

**Terraform Version**

Terraform v1.1.6

**Describe the bug**

When adding an expression column to an existing table the following error occurs: 

`Failed to add column ROW_ID => Only adding a column as a constant is supported by Snowflake`

[Issue: table.go#L643](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/table.go#L642-L644) : looks like this piece is hardcoded to filter out anything but `constant`.

Where `ROW_ID` is:

```
  column {
    name     = "ROW_ID"
    type     = "VARCHAR"
    nullable = false
    default {
      expression = "MD5('hash-me')"
    }
  }
```

**Expected behavior**

The provider should generate the appropriate DDL to add the expression column. 
The provider should update the terraform state to represent this expression column.

**Code samples and commands**

```
resource "snowflake_table" "table" {
  database            = "database_name"
  schema              = "schema_name"
  name                = "table_name"
  data_retention_days = 10
  change_tracking     = true
  cluster_by          = []

  column {
    name     = "column1"
    type     = "VARCHAR(16777216)"
    nullable = false
  }

  column {
    name     = "column2"
    type     = "TIMESTAMP_TZ(9)"
    nullable = false
  }

  column {
    name     = "column3"
    type     = "VARIANT"
    nullable = false
  }

  column {
    name     = "column4"
    type     = "VARCHAR"
    nullable = false
    default {
      expression = "MD5('hash-me')"
    }
  }

}
```

**Comment by crowemi** [comment] 2022-02-18 16:52
I've [forked](https://github.com/crowemi/terraform-provider-snowflake) a fix that generates the necessary SQL to add the `expression` column and passes all tests. However, when running locally the terraform state doesn't update as expected, the `expression` column is left out of the state even though the tables are updated within the database and I can't seem to pinpoint where the issue is.

**Comment by dalebradman** [comment] 2023-07-12 14:11
Bump on this one ?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:49
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:49 UTC
Labels: bug
