### ISSUE TITLE
Warehouse creation fails due to quoted identifiers in the `SHOW PARAMETERS IN WAREHOUSE` query.

### ISSUE THREAD

**Issue by sshah90** [Snowflake-Labs/terraform-provider-snowflake#844] opened 2022-02-02 22:29 UTC
**Provider & Terraform Version**

❯ terraform version                                                
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/chanzuckerberg/snowflake **v0.25.36**
+ provider registry.terraform.io/hashicorp/random v3.0.1

**Describe the bug**
I am trying to create a warehouse using `snowflake_warehouse` resource which fails during terraform apply command with ` Warehouse 'TEST' does not exist or not authorized.`

It does create a warehouse in Snowflake but it's not able to update terraform state files while running `SHOW PARAMETERS IN WAREHOUSE test`.

Query History from Snowflake side:

![Screen Shot 2022-02-02 at 5 09 01 PM](https://user-images.githubusercontent.com/26821376/152247679-0a689d81-b07a-4e29-a856-6cb12c44cf73.png)

All other queries do have quotes but not with warehouse one.

**Expected behavior**

`terraform apply` command should create a warehouse and successfully exit.

**Code samples and commands**

```terraform
resource "snowflake_warehouse" "warehouse" {
    for_each       = var.warehouses
    name           = each.key
    comment        = each.value.comment
    warehouse_size = each.value.size
}
```

variable file :

```terraform
warehouses = {
    test = {
      comment = "test warehouse"
      size    = "X-Small"
    }
}
```

**Additional context**

After debugging, I found this [discussion](https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/558) and given suggestion works fine but it stores all object names as the upper case so in the next run it forces changes on other resources like schema or role.

example:

![Screen Shot 2022-02-02 at 5 26 06 PM](https://user-images.githubusercontent.com/26821376/152247956-6e902e0c-fcbe-4f57-b187-91c0b574aec2.png)

**Comment by sshah90** [comment] 2022-02-03 15:57
looks like PR #745 introduced `show parameter` query in the warehouse resource.

@sonmezonur any thoughts?

**Comment by sonmezonur** [comment] 2022-02-03 16:24
Did you try to change your variable file to:

```
warehouses = {
    TEST = {
      comment = "test warehouse"
      size    = "X-Small"
    }
}
```

If you don't have any special reason for using case-sensitive warehouses, I recommend trying uppercase characters in your warehouse setup.

**Comment by sshah90** [comment] 2022-02-03 16:28
Hi Sonmezonur, thanks for the suggestion.

With upper case, it works fine. Ideally, it should work with case-insensitive naming standards as the provider allows that.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:49
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:49 UTC
Labels: bug
