### ISSUE TITLE
snowflake_role_ownership_grant import bug

### ISSUE THREAD

**Issue by XiaotuZhang** [Snowflake-Labs/terraform-provider-snowflake#1061] opened 2022-06-15 17:15 UTC
**Provider Version**
terraform-provider-snowflake_v0.33.1 

**Terraform Version**
Terraform v1.2.1

**Describe the bug**
When trying to import a snowflake_role_ownership_grant by running:
`terraform import snowflake_role_ownership_grant.grants 'EA_ROLE'` while in resource definition I prepared:
```
resource "snowflake_role_ownership_grant" "grants" {
    role_name = "EA_ROLE"
}
``` 

**Expected behavior**
Expecting resource "snowflake_role_ownership_grant" "grants" to be filled up with role or user grants.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:46
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:46 UTC
Labels: bug
