### ISSUE TITLE
SQL compilation error when single quotes are present in snowflake_role comments

### ISSUE THREAD

**Issue by joestepp** [Snowflake-Labs/terraform-provider-snowflake#2425] opened 2024-01-25 16:54 UTC
### Terraform CLI and Provider Versions

Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.33.0
+ provider registry.terraform.io/snowflake-labs/snowflake v0.84.1

### Terraform Configuration

```terraform
resource "snowflake_role" "sandbox_test_user_role" {
  provider = snowflake.security_admin
  name     = "SANDBOX_TEST_USER_ROLE"
  comment  = "A role granting access to test_user's sandbox."
}

resource "snowflake_schema" "sandbox_test_user_schema" {
  database = snowflake_database.sandbox_db.name
  name     = "TEST_USER"
  comment  = "test_user's sandbox managed access schema."

  is_managed = true
}
```

### Expected Behavior

The role comment is created/changed without issue.

### Actual Behavior

│ Error: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 89 unexpected 'sandbox'.
│ syntax error line 1 at position 96 unexpected '.'.
│
│   with snowflake_role.sandbox_test_user_role,
│   on sandbox.tf line 231, in resource "snowflake_role" "sandbox_test_user_role":
│  231: resource "snowflake_role" "sandbox_test_user_role" {

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Low

### Additional Information

The comment for the snowflake_schema can be created/changed to include the single quote without issue, but doing the same for the role for some reason causes the error. The generated SQL isn't escaping the single quote for the role. From the debug logs:

```
2024-01-25T13:41:06.525-0300 [DEBUG] provider.terraform-provider-snowflake_v0.84.1: 2024/01/25 13:41:06 [DEBUG] sql-conn-exec: [query ALTER SCHEMA "SANDBOX"."TEST_USER" SET COMMENT = 'test_user\'s sandbox managed access schema.' err <nil> duration 265.117584ms args {}] ()
```

vs. 

```
2024-01-25T13:41:06.971-0300 [DEBUG] provider.terraform-provider-snowflake_v0.84.1: 2024/01/25 13:41:06 [DEBUG] sql-conn-exec: [query ALTER ROLE "SANDBOX_TEST_USER_ROLE" SET COMMENT = 'A role granting access to test_user's sandbox.' err 001003 (42000): SQL compilation error:
2024-01-25T13:41:06.971-0300 [DEBUG] provider.terraform-provider-snowflake_v0.84.1: syntax error line 1 at position 89 unexpected 'sandbox'.
2024-01-25T13:41:06.971-0300 [DEBUG] provider.terraform-provider-snowflake_v0.84.1: syntax error line 1 at position 96 unexpected '.'. duration 514.861625ms args {}] (%!s(<nil>))
```

**Comment by sfc-gh-asawicki** [comment] 2024-01-25 17:04
Hey @joestepp. Thanks for reaching out to us.

Closing it as a duplicate of #2411.

**Closed by sfc-gh-asawicki** 2024-01-25 17:04 UTC
Labels: bug
