### ISSUE TITLE
grants on snow pipes requires pipes to be in paused state

### ISSUE THREAD

**Issue by astanfel** [Snowflake-Labs/terraform-provider-snowflake#660] opened 2021-08-23 20:42 UTC
**Provider Version**

v0.25.17

**Terraform Version**

v1.0.2

**Describe the bug**

When attempting to deploy a snowflake_pipe_grant to an existing pipe. There is a deployment error stating that the pipe is not in a paused state. 

**Expected behavior**

During the deployment of the grants, the pipe is paused and after the grants are created/modified the pipe is resumed. 

**Code samples and commands**

```terraform 

resource "snowflake_pipe" "pipe" {

  provider = my-provider

  database       = upper(var.my_database)
  schema         = upper(var.my_schema)
  name           = upper(var.pipe_name)
  comment        = var.pipe_comment
  copy_statement = var.copy_statement
  auto_ingest    = var.auto_ingest
}

resource "snowflake_pipe_grant" "operate_grant" {

  database_name = upper(var.my_database)
  schema_name   = upper(var.my_schema)
  pipe_name     = upper(var.pipe_name)

  privilege = "OPERATE"
  roles = [
    upper("${var.role1}"),
    upper("${var.role2}")
  ]

  on_future         = false
  with_grant_option = false
}

```

**Additional context**

When I run 

```sql 

ALTER PIPE my_database.my_schema.my_pipe SET PIPE_EXECUTION_PAUSED=true;
```

Then run the terraform deployment the resources are created. I also had to run a system command to resume the pipe: 

```sql
select SYSTEM$PIPE_FORCE_RESUME('my_database.my_schema.my_pipe');
```

I was also able to see that my pipe was in a running state with this system command: 

```sql 
select SYSTEM$PIPE_STATUS('my_database.my_schema.my_pipe');
```

**Comment by 1kazuki1** [comment] 2022-07-07 23:56
Any updates on this one?
I have the same issue.

**Comment by breathe** [comment] 2022-07-28 15:03
I also am running into this issue as well.  

There's no way to change ownership of a pipe without first manually pausing it (outside of terraform)

**Comment by jbcom** [comment] 2023-02-21 18:25
Still a problem. Any chance of an update?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:55
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:55 UTC
Labels: bug
