### ISSUE TITLE
GRANT SELECT TO ALL 

### ISSUE THREAD

**Issue by aaronsteers** [Snowflake-Labs/terraform-provider-snowflake#284] opened 2020-10-25 20:09 UTC
**Is your feature request related to a problem? Please describe.**

I'm not sure how to replicate my existing snowflake grants into terraform without access to an option for `ALL TABLES IN SCHEMA/DATABASE`.

**Describe the solution you'd like**

Just as "future" tables/views are supported in grants, the request would be to support granting access to "all" tables/views.

**Describe alternatives you've considered**

I considered creating a "task" resource to manually declare the grants - however, that "task" resource appears to be missing an "undo_sql_statement" to provide an "undo"/"destroy" capability, for instance when permission is changed/revoked.

**Additional context**

**Comment by tnightengale** [comment] 2020-10-27 00:49
Would love to help implement this!

**Comment by JimFawkes** [comment] 2020-11-11 21:39
It would be great to have this!

**Comment by a2m1** [comment] 2020-11-18 17:14
Would be great to have `GRANT ON ALL TABLES/VIEWS/SCHEMAS`

**Comment by JavierLopezT** [comment] 2021-02-01 13:34
Having this would be awesome

**Comment by juangesino** [comment] 2021-05-19 16:47
+1 on the awesomeness of having something like this 👍

**Comment by gnilrets** [comment] 2021-06-29 21:25
+1 - I can specify that I want to grant select on all future tables, but not all existing ones!

**Comment by aidanmelen** [comment] 2021-08-30 00:02
Hey @tnightengale, @JimFawkes, @a2m1, @JavierLopezT, @juangesino , and @gnilrets...  I just created a provider that allows us to declare `GRANT ALL` statements in Terraform! Here is a code snippet from the [terraform-provider-snowsql/examples/simple/main.tf](https://github.com/aidanmelen/terraform-provider-snowsql/blob/main/examples/simple/main.tf#L66-L84).

```hcl
resource "snowsql_exec" "dcl" {
  name = local.name

  create {
    statements = <<-EOT
    GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
    GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
    EOT
  }

  delete {
    statements = <<-EOT
    REVOKE ALL PRIVILEGES ON ALL TABLES IN DATABASE ${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
    REVOKE ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
    EOT
  }

  delete_on_create = true
}
```

Check out the [terraform-provider-snowsql snowsql_exec resource documentation](https://registry.terraform.io/providers/aidanmelen/snowsql/latest/docs/resources/exec) for more information.

**Comment by zack-klein** [comment] 2021-08-30 15:24
+1 this would be fantastic

**Comment by aidan-melen** [comment] 2021-08-30 22:53
> Hey @tnightengale, @JimFawkes, @a2m1, @JavierLopezT, @juangesino , and @gnilrets... I just created a provider that allows us to declare `GRANT ALL` statements in Terraform! Here is a code snippet from the [terraform-provider-snowsql/examples/simple/main.tf](https://github.com/aidanmelen/terraform-provider-snowsql/blob/main/examples/simple/main.tf#L66-L84).
> 
> ```terraform
> resource "snowsql_exec" "dcl" {
>   name = local.name
> 
>   create {
>     statements = <<-EOT
>     GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
>     GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
>     EOT
>   }
> 
>   delete {
>     statements = <<-EOT
>     REVOKE ALL PRIVILEGES ON ALL TABLES IN DATABASE ${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
>     REVOKE ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
>     EOT
>   }
> 
>   delete_on_create = true
> }
> ```
> 
> Check out the [terraform-provider-snowsql snowsql_exec resource documentation](https://registry.terraform.io/providers/aidanmelen/snowsql/latest/docs/resources/exec) for more information.

CC @zack-klein

**Comment by ricardobf** [comment] 2022-07-05 12:51
Any news about this one?

**Comment by vlucas-caylent** [comment] 2022-08-09 00:14
@ 

> Hey @tnightengale, @JimFawkes, @a2m1, @JavierLopezT, @juangesino , and @gnilrets... I just created a provider that allows us to declare `GRANT ALL` statements in Terraform! Here is a code snippet from the [terraform-provider-snowsql/examples/simple/main.tf](https://github.com/aidanmelen/terraform-provider-snowsql/blob/main/examples/simple/main.tf#L66-L84).
> 
> ```terraform
> resource "snowsql_exec" "dcl" {
>   name = local.name
> 
>   create {
>     statements = <<-EOT
>     GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
>     GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${snowflake_database.database.name} TO ROLE ${snowflake_role.role.name};
>     EOT
>   }
> 
>   delete {
>     statements = <<-EOT
>     REVOKE ALL PRIVILEGES ON ALL TABLES IN DATABASE ${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
>     REVOKE ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${snowflake_database.database.name} FROM ROLE ${snowflake_role.role.name};
>     EOT
>   }
> 
>   delete_on_create = true
> }
> ```
> 
> Check out the [terraform-provider-snowsql snowsql_exec resource documentation](https://registry.terraform.io/providers/aidanmelen/snowsql/latest/docs/resources/exec) for more information.

There is no possible use a list ? Like in null_resources with for_each and triggers? I want to use the snowsql with more than 130 commands.

**Comment by aidanmelen** [comment] 2022-08-09 01:50
> There is no possible use a list ? 

You could define you tables in a list. But that doesn't seem fun to manage. Also you would have to manually update the list for newly created tables.

> Like in null_resources with for_each and triggers? 

The local_exec null_resource would work to run Snowsql commands. However, in addition to having terraform installs, operators would also have to ensure that Snowsql is install and configured correctly. You would also not have any logic for deletion, so all the snowflake objects created with the null resource would have to be manually destroyed.

> I want to use the snowsql with more than 130 commands.

The snowsql provider uses the same [golang lib](https://golangexample.com/snowflake-implemented-in-go-golang/) as the snowflake provider. I not familiar with any limits on how many statements you provide for a single transaction.

Cheers! hope that helps

**Comment by vlucas-caylent** [comment] 2022-08-09 03:11
Yea, i'm using null_resource with local-exec snowsql commands, i receive a **list** using **for_each** and **formalitlist** for  **db,schema,roles**. My guess is about your provider, i'm trying to create a list and for_each to run in sequence in create statements. But its seems its not possible.

**Comment by vlucas-caylent** [comment] 2022-08-09 03:11
> > There is no possible use a list ?
> 
> You could create snowflake tables using a `list` and a `for_each` loop. But that doesn't seem fun to manage. Also you would have to manually update the list for newly created tables.
> 
> > Like in null_resources with for_each and triggers?
> 
> The local_exec null_resource would work to run Snowsql commands. However, in addition to having terraform installs, operators would also have to ensure that Snowsql is install and configured correctly. You would also not have any logic for deletion, so all the snowflake objects created with the null resource would have to be manually destroyed.
> 
> > I want to use the snowsql with more than 130 commands.
> 
> The snowsql provider uses the same [golang lib](https://golangexample.com/snowflake-implemented-in-go-golang/) as the snowflake provider. I not familiar with any limits on how many statements you provide for a single transaction.
> 
> Cheers! hope that helps

Yea, i'm using null_resource with local-exec snowsql commands, i receive a list using for_each and formalitlist for db,schema,roles. My guess is about your provider, i'm trying to create a list and for_each to run in sequence in create statements. But its seems its not possible.

**Comment by aidanmelen** [comment] 2022-08-09 03:29
> According the documentation is not possible

no it is definitely supported and encouraged. Could you please [create an issue in the snowsql provider](https://github.com/aidanmelen/terraform-provider-snowsql/issues)? I would be have to help more over there. Somebody else might have the same question as you and I would like scope this to the snowsql project if possible.

**Comment by vlucas-caylent** [comment] 2022-08-09 03:42
@aidanmelen Done. Thanks bro

**Comment by iamontheinet** [comment] 2022-12-13 01:12
Can we close this issue?

**Comment by cybdeen** [comment] 2023-01-03 04:55
+1, currently working around this using data sources + for_each loops and it's quite tedious

**Comment by kamilamarcinekpgs** [comment] 2023-01-16 13:33
> Can we close this issue?

No, please, we want the feature, not workarounds.

**Comment by tursid** [comment] 2023-03-01 08:01
Hi what is the status of this issue? 
Snowflake documentation supports using grant ALL privileges, it would be great if terraform worked with this aswell.

**Comment by francescomucio** [comment] 2023-03-10 15:13
same here, all will just solve the issue and it's a documented feature in Snowflake

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:02
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:02 UTC
Labels: feature-request
