### ISSUE TITLE
Crash when trying to refresh, plan or apply a drifted snowflake_procedure.

### ISSUE THREAD

**Issue by mithunsl** [Snowflake-Labs/terraform-provider-snowflake#806] opened 2022-01-05 22:23 UTC
**Provider Version**

v0.25.32

**Terraform Version**

v1.1.2

**Describe the bug**

When a snowflake_procedure has drifted, trying to do a state refresh, plan or apply causes the provider to crash.
Stack trace from the terraform-provider-snowflake_v0.25.32 plugin:

```
panic: runtime error: index out of range [1] with length 0

goroutine 54 [running]:
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadProcedure(0xc000720280, {0x10cc0c0, 0xc000466dd0})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/procedure.go:258 +0x111d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x10dffc2, {0x12d37d8, 0xc00046e180}, 0x24, {0x10cc0c0, 0xc000466dd0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:335 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0002995e0, {0x12d37d8, 0xc00046e180}, 0xc000176750, {0x10cc0c0, 0xc000466dd0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:624 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00044a0a8, {0x12d37d8, 0xc00046e180}, 0xc00046e1c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00031cd60, {0x12d3880, 0xc00011a480}, 0xc0005760c0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x1fb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x10979a0, 0xc00031cd60}, {0x12d3880, 0xc00011a480}, 0xc000576060, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00051c700, {0x12e5b30, 0xc000164000}, 0xc0005e2000, 0xc000386660, 0x1a1a930, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00051c700, {0x12e5b30, 0xc000164000}, 0xc0005e2000, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-snowflake_v0.25.32 plugin crashed!
```

**Expected behavior**

I would expect the state to be reconciled if there is drift.

**Code samples and commands**

N/A

**Additional context**

This happens with a specific stored procedure in my infrastructure. I am not sure what is special about it except that it is big. Is there is a limitation on the size of the procedure?

**Comment by yohei1126** [comment] 2022-03-25 08:40
Might be the same issue. After I remove a stored procedure from terraform, the error does not happen. https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/949

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:50
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:50 UTC
Labels: bug
