### ISSUE TITLE
Data source for databases

### ISSUE THREAD

**Issue by jmrobles** [Snowflake-Labs/terraform-provider-snowflake#859] opened 2022-02-14 12:20 UTC
**Is your feature request related to a problem? Please describe.**

For some projects it's necessary to retrieve the databases in snowflake account. For example, to create service account for some kind of databases.

**Describe the solution you'd like**

A data source called "databases" that returns a list of databases (string[]).

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:49
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:49 UTC
Labels: feature-request
