### ISSUE TITLE
Stage - providing url and copy_options causes resource to update

### ISSUE THREAD

**Issue by armaciej** [Snowflake-Labs/terraform-provider-snowflake#218] opened 2020-06-29 15:19 UTC
I am using `snowflake_stage` resource and have observed the following behavior.

While providing the following parameters:

- url
- copy_options

in the resource each time I run `terraform apply` without modifying those attributes terraform updates the resource in place with the following message:
```
  ~ resource "snowflake_stage" "stages" {
        comment             = "My comment"
      + copy_options        = "ON_ERROR = ABORT_STATEMENT ENFORCE_LENGTH = TRUE"
        database            = "MY_DATABASE"
        id                  = "MY_DATABASE|MY_SCHEMA|MY_STAGE"
        name                = "MY_STAGE"
        schema              = "MY_SCHEMA"
        storage_integration = "MY_STORAGE_INTEGRATION"
      + url                 = "s3://my-bucket/"
```
which indicates that the provided does not pick those attributes from Snowflake.

**Comment by zanthorn** [comment] 2022-04-27 03:37
I am seeing this as well, on `copy_options`. Using the latest 0.32.0 version.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:04
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:04 UTC
Labels: bug
