### ISSUE TITLE
Support for grant ownership on role

### ISSUE THREAD

**Issue by ericmjalbert** [Snowflake-Labs/terraform-provider-snowflake#460] opened 2021-02-19 23:00 UTC
**Is your feature request related to a problem? Please describe.**

I'm setting up my Snowflake account with a [Vault Database Engine](https://github.com/Snowflake-Labs/sfguide-vault-snowflakepasswords) to manage the user passwords for applications. As part of this solution I need to `grant ownership on role ROLENAME to role VAULTROLE`.

I don't think there is a way to currently do this with the terraform snowflake provider.

**Describe the solution you'd like**

I'd like to see a new resource that lets you define role ownership to a specific user. Maybe something like a new resource named `snowflake_ownership_grant` that covers the functionality of https://docs.snowflake.com/en/sql-reference/sql/grant-ownership.html.

It might looks something like:
```
resource snowflake_role_ownership_grant grant {
  on_role = "ROLENAME"
  to_role = "VAULTROLE"

  current_grants = "COPY|REVOKE"
}
```

**Describe alternatives you've considered**

I haven't thought of any alternatives yet. I think I'll be able to solve this using unrelated automation scripts, but those exist outside the terraform ecosystem.

**Additional context**

NA

**Comment by yohei1126** [comment] 2021-03-03 00:18
Have you try `role_grants`? https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/role_grants

**Comment by ericmjalbert** [comment] 2021-03-03 14:14
I don't think that `role_grants` can do this since it only does the [`GRANT ROLE ...`](https://docs.snowflake.com/en/sql-reference/sql/grant-role.html) type sql (see [source code](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/565c8c6991f7959f207645d97837de7bed1b9d0c/pkg/snowflake/role_grant.go#L36)) . This feature request is specifically for the granting of `OWNERSHIP`.

**Comment by malonsocasas** [comment] 2021-03-15 15:14
I have a similar issue here. 

An alternative proposal, although I don't know if this completely fixes ericmjalbert's problem: would it be possible to specify parent role when creating a new role with `snowflake_role` 

Something like :
```
resource snowflake_role role {
  name    = "role1"
  comment = "A role."
  parent_role = "parentrole1"
}
```

**Comment by PChambino** [comment] 2021-04-28 10:05
My use case for this is that I want role A (created by terraform) to be own by role B so that role B can grant role A to users without having to give MANAGE GRANTS at the account level to role B.

The lack of support for the GRANT OWNERSHIP ON ROLE A TO ROLE B statement prevents to do this with terraform.

**Comment by KulkarniAbhishek** [comment] 2021-09-24 13:38
I have a similar request to give the ownership of one role to another in Snowflake. 

The query looks like this:
grant ownership on role ROLE_1 to role ROLE_2;

Is there a way to do this in Terraform?

**Comment by aidanmelen** [comment] 2022-03-12 01:29
as pointed out by @chrisluedtke, the [snowsql provider](https://registry.terraform.io/providers/aidanmelen/snowsql/latest/docs/resources/exec) can be used as a workaround solution.

```hcl
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = ">= 0.25.18"
    }

    snowsql = {
      source  = "aidanmelen/snowsql"
      version = ">= 0.3.0"
    }
    random = ">= 2.1"
  }
}

provider "snowflake" {}
provider "snowsql" {}

resource "snowflake_role" "provisioner" {
  name = "PROVISIONER"
}

resource "snowflake_role" "vault" {
  name = "VAULT"
}

resource "snowsql_exec" "grant_ownership_on_aad_roles_to_aad_provisioner" {
  name = "grant_ownership_on_aad_roles_to_aad_provisioner"

  create {
    statements = <<-EOT
    GRANT OWNERSHIP ON ROLE ${snowflake_role.vault.name} TO ROLE ${snowflake_role.provisioner.name};
    EOT
  }

  delete {
    statements = <<-EOT
    GRANT OWNERSHIP ON ROLE ${snowflake_role.vault.name} TO ROLE ACCOUNTADMIN;
    EOT
  }
}
```

**Comment by aidanmelen** [comment] 2022-03-12 01:36
I think @ericmjalbert has the right idea. A new `snowflake_role_ownership_grant` resource would make the most sense. The `snowflake_role` resource is for granting roles to other roles and not role ownership.

**Comment by aidanmelen** [comment] 2022-03-12 05:24
P.S. I tried making a PR but didn't get very far https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/916/files

**Comment by aidanmelen** [comment] 2022-03-12 19:41
new PR: https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/917

**Comment by aidanmelen** [comment] 2022-03-15 00:31
This PR https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/917 should be ready to go

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:00
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:00 UTC
Labels: feature-request
