### ISSUE TITLE
Passing empty roles list to snowflake_schema_grant

### ISSUE THREAD

**Issue by alex-96-eng** [Snowflake-Labs/terraform-provider-snowflake#275] opened 2020-10-13 14:20 UTC
_NOOB here, first post sorry if I break rules._

I was wondering if there is a way to pass roles with a list i.e `roles = []` in the `snowflake_schema_grant`. Currently, I have a `snowflake_schema_grant` resource for granting `ALL` and one for granting `USAGE` which I'm driving from a locals structure. Following something like this: 
```hcl
locals {
  schemas = {
    "schema1" = {
      database    = var.snowflake_database_name
      usage_roles = ["ROLE1"]
      all_roles   = ["ROLE1"]
    }
    "schema2" = {
      database    = var.snowflake_database_name
      usage_roles = ["ROLE2"]
      all_roles   = ["ROLE2"]
    }
  }
}

resource snowflake_schema_grant schema_grant_usage {
  for_each      = local.schemas
  schema_name   = each.key
  database_name = each.value.database
  privilege     = "USAGE"
  roles         = each.value.roles
}

resource snowflake_schema_grant schema_grant_all {
  for_each      = local.schemas
  schema_name   = each.key
  database_name = each.value.database
  privilege     = "ALL"
  roles         = each.value.roles
```

If I wanted `schema2` to have no roles that have `ALL` privileges, ideally it would be nice to just set `schema2.all_roles = []`. However, I am prevented by the following: 

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/70bf4423b68ac4aed526cf08edcb5a66f6ea930a/pkg/resources/grant_helpers.go#L180

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:02
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:02 UTC
Labels: feature-request
