### ISSUE TITLE
snowflake_procedures (Data Source) doesn't provide argument name

### ISSUE THREAD

**Issue by rsubudhi** [Snowflake-Labs/terraform-provider-snowflake#1267] opened 2022-10-11 08:25 UTC
**Provider Version**

The provider version you are using. : 0.25.19

**Terraform Version**

The version of Terraform you were using when the bug was encountered.: 1.0.0

**Describe the bug**

on data source (snowflake_procedures ) doesn't provide argument name 
(https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/procedures)

as we are not able to pass argument names on resource snowflake_procedure_grant through datasource

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/procedure_grant#nestedblock--arguments

is there a way we can pass arguments name on resource snowflake_procedure_grant  by fetching data from datasource?

**Expected behavior**

is there a way we can pass arguments name on resource snowflake_procedure_grant  by fetching data from datasource?

**Code samples and commands**

procedure_arg_type = tolist([
    for procedure in data.snowflake_procedures.this.procedures :
    procedure.argument_types
    if contains(local.object_types, "procedure")
  ])

resource "snowflake_procedure_grant" "this" {
  for_each      = local.proc_final
  database_name = var.database_name
  schema_name   = var.schema_name  
  procedure_name    = each.key
  return_type = each.value

arguments {
      type = each.value
  
  } 
  privilege = var.privilege

  roles  = var.roles
  shares = var.shares

  depends_on = [
    data.snowflake_procedures.this
  ]

  lifecycle {
    ignore_changes = [
      # Ignore changes to roles as there could be potential updates to this resource role elsewhere.
      roles
    ]
    }
   
}

error:
 Error: Missing required argument
│
│   on ..\_modules\grant_on_all\main.tf line 97, in resource "snowflake_procedure_grant" "this":
│   97: arguments {
│
│ The argument "name" is required, but no definition was found.

**Additional context**

how to add arguments name ?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:45
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:45 UTC
Labels: bug
