### ISSUE TITLE
Stream metadata retrieval ignores db/schema

### ISSUE THREAD

**Issue by zarez** [Snowflake-Labs/terraform-provider-snowflake#586] opened 2021-06-23 03:58 UTC
**Provider Version**

0.25.8

**Terraform Version**

1.0.0

**Describe the bug**

If you have a stream with the same name across different schemas, on every plan/apply the provider tries to change the on_table and append_only parameters. 

![image](https://user-images.githubusercontent.com/772740/123033222-64e1e800-d3b5-11eb-92e9-c84835e70a3b.png)

**Expected behavior**

When reading metadata from a dictionary should always consider full hierarchy(db->schema->object), not just the object name. In this example, having streams with the same name across different schemas should give back a single stream per schema.

**Code samples and commands**
```
# snowflake_stream.stream_cdc2["rpps_client"] must be replaced
-/+ resource "snowflake_stream" "stream_cdc2" {
      ~ append_only       = false -> true # forces replacement
      ~ id                = "SBOX_RAW|CDC2|RPPS_CLIENT_STREAM" -> (known after apply)
        name              = "RPPS_CLIENT_STREAM"
      ~ on_table          = "SBOX_RAW.CDC1.RPPS_CLIENT_STG" -> "SBOX_RAW.CDC2.RPPS_CLIENT_STG" # forces replacement
      ~ owner             = "BUILDER" -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```
**Additional context**

The same bug was encountered with tasks. Can workaround with prefix/suffix object names with the db/schema name to make the name unique.

**Comment by alldoami** [comment] 2021-06-23 17:41
Can you provide the terraform you're writing that is making this change?

**Comment by zarez** [comment] 2021-06-24 20:04
I am not making any changes in my terraform file. Just upgrade from 0.25.6 to 0.25.8 created this problem. 

Here is example:

`resource "snowflake_stream" "stream_cdc1" {
  depends_on = [
    snowflake_table.tables_cdc1,
    snowflake_table.tables_cdc2
  ]
  name     = "${upper(each.key)}_STREAM"
  database = snowflake_database.databases["RAW"].name
  schema   = snowflake_schema.schemas["CDC1"].name

  on_table    = "${snowflake_database.databases["RAW"].name}.${snowflake_schema.schemas["CDC1"].name}.${upper(each.key)}_STG"
  append_only = true

  for_each = {
 "rpps_client"                    = {}
 ...
 ...
 }
resource "snowflake_stream" "stream_cdc2" {
  depends_on = [
    snowflake_table.tables_cdc1,
    snowflake_table.tables_cdc2
  ]
  name     = "${upper(each.key)}_STREAM"
  database = snowflake_database.databases["RAW"].name
  schema   = snowflake_schema.schemas["CDC2"].name

  on_table    = "${snowflake_database.databases["RAW"].name}.${snowflake_schema.schemas["CDC2"].name}.${upper(each.key)}_STG"
  append_only = true

  for_each = {
   "rpps_client"                    = {}
   ...
   ...
   ..
  }
  `

**Comment by zarez** [comment] 2021-06-25 14:06
As I mentioned earlier, the same type of bug with tasks:

[https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/522](url)

**Comment by zarez** [comment] 2021-07-06 18:49
Same problem with file objects:

[https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/594#issue-937923069](url)

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:57
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:57 UTC
Labels: bug
