### ISSUE TITLE
file_format error when i exec terraform apply a second time without any change

### ISSUE THREAD

**Issue by waterdo** [Snowflake-Labs/terraform-provider-snowflake#897] opened 2022-03-09 09:07 UTC
**Provider Version**

+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.28

**Terraform Version**

Terraform v1.1.7

**Describe the bug**

when I exec "terraform apply" a second time without any change of my code, return an error.

Plan: 0 to add, 1 to change, 0 to destroy.
snowflake_file_format.external_storage: Modifying... [id=TF_DAF2|LOG|TFMYCSVFORMAT2]
╷
│ Error: error updating file format compression on TF_DAF2|LOG|TFMYCSVFORMAT2: 001008 (22023): SQL compilation error:
│ invalid value [''] for parameter 'COMPRESSION'
│
│   with snowflake_file_format.external_storage,
│   on storagefileformat.tf line 3, in resource "snowflake_file_format" "external_storage":
│    3: resource "snowflake_file_format" "external_storage" {
│
╵
![image](https://user-images.githubusercontent.com/26116632/157408911-c2aacca8-9c7e-4d8a-9f0b-33bcbaf3c1c2.png)

**Expected behavior**

Not return this error

**Code samples and commands**

resource "snowflake_file_format" "external_storage" {
  name            = "TFMYCSVFORMAT2"
  database        = "TF_DAF2"
  schema          = "LOG"
  format_type     = "csv"
  depends_on = [
    snowflake_schema.schemaparatablas
  ]
}

**Additional context**

**Comment by baugarcia** [comment] 2022-06-22 11:57
I am having the same issue. Has anyone found a workaround or a fix for this issue?

**Comment by Kannedhara** [comment] 2022-09-28 15:29
Any work around this issue, we are having the same issue.

**Comment by baugarcia** [comment] 2022-09-28 15:37
@Kannedhara I fixed this for our environment by adding "compression = 'NONE'" in the file format terraform resource creation.

I am guessing the documentation is not really up to date and some parameters are mandatory for different format_types, so even if my parameter does not fix it for you, check the error and try to add a value for whatever parameter it complains.

**Comment by crowemi** [comment] 2022-10-07 22:10
Here is a listing of the "required" fields (with what I believe are the default values) to get the file_format resource to work as expected:

```
  validate_utf8 = true
  compression = "AUTO"
  record_delimiter = "\n"
  binary_format = "HEX"
  escape = "NONE"
  time_format = "AUTO"
  timestamp_format = "AUTO"
  date_format = "AUTO"
  encoding = "UTF8"
  escape_unenclosed_field = "\\"
  field_optionally_enclosed_by = "NONE"
```

**Comment by icornett** [comment] 2022-11-02 00:28
This still seems to be occurring on 0.49.0 as of today.   I'm having the same problem even passing default values as shown above.

**Comment by jakobfloe** [comment] 2022-11-10 08:58
Same issue here.

**Comment by funes79** [comment] 2022-12-19 14:55
As @crowemi  pointed out, the escape_unenclosed_field needs to be explicitly defined in the resource definition, otherwise it will fail (or will trigger a change every time).

```
...
  escape_unenclosed_field        = "\\"
...
```
This is the default setting, what works for me. Provider version 0.52

**Comment by kstradinfs** [comment] 2023-01-06 17:20
Issue still occurring at the moment - Correction by @crowemi worked like a charm

**Comment by aliceinnorway** [comment] 2023-02-23 14:35
Same issue here.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:48
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:48 UTC
Labels: bug
