### ISSUE TITLE
Error: 002043 (02000): SQL compilation error: Object does not exist, or operation cannot be performed

### ISSUE THREAD

**Issue by hugh-nguyen** [Snowflake-Labs/terraform-provider-snowflake#892] opened 2022-03-08 20:51 UTC
**Provider Version**
0.22.0/0.25.36
**Terraform Version**
1.1.7

**Describe the bug**
Hi there, I had the following code running fine.
```
terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.22.0"
    }
  }
}

provider "snowflake" {
  alias = "sys_admin"
  role  = "SYSADMIN"
  username = "tf-snow"
  private_key_path = "..."
  region = "ap-southeast-2"
  account = "..."

}

resource "snowflake_warehouse" "star_warehouse" {
  provider       = snowflake.sys_admin
  name           = "STAR_WAREHOUSE"
  warehouse_size = "XSmall"

  auto_suspend = 60
}

resource "snowflake_database" "STAR_DB" {
  provider = snowflake.sys_admin
  name     = "STAR_DB"
}

resource "snowflake_schema" "public" {
  provider            = snowflake.sys_admin
  database            = "STAR_DB"
  name                = "public"
  data_retention_days = 1
}

resource "snowflake_table" "sales" {
  provider            = snowflake.sys_admin
  database            = "STAR_DB"
  schema              = "public"
  name                = "sales"

  column {
    name     = "id"
    type     = "int"
  }
}
```

Then I decided to rename "STAR_DB" to the lower case version "star_db".

It then started giving me these errors.
```
Error: 002043 (02000): SQL compilation error: Object does not exist, or operation cannot be performed.
with snowflake_schema.public
on snowflake.tf line 33, in resource "snowflake_schema" "public":
```

```
Error: 002043 (02000): SQL compilation error: Object does not exist, or operation cannot be performed.
with snowflake_table.sales
on snowflake.tf line 40, in resource "snowflake_table" "sales":
```

I tried reverting the code, removing the code, removing the underlying assets, rebuilding the underlying assets manually, I tried deleting the file and I even tried running a terraform destroy!

**Additional context**
I have a bunch of AWS assets in the state as well and now I will need to remove them all manually, this is a big deal breaker any production environment.
Please let me know if you have any advise.

I was initially using 0.22.0, but it also failed for 0.25.36

Note: I am using terraform cloud.

**Comment by thenaturalist** [comment] 2022-03-08 21:31
Hi @hugh-nguyen lowercasing names in Terraform does generally not work nicely, as Snowflake's naming convention is uppercase for some resources. 

When writing SQL in the Snowflake GUI this is not an issue, but it is an issue when writing Terraform code. 
The SQL executed by the provider tries to execute the query with a plain lowercase name and this, in fact, does not resolve against Snowflake's internal resource mapping. 

You need to keep some names uppercase explicitly or at least pass them with the TF `upper()` function.

**Comment by hugh-nguyen** [comment] 2022-03-08 21:39
Hi the @thenaturalist, that's good to know. So I've been playing around and I found that adding

depends_on = [snowflake_schema.public] to the snowflake_table removes the table level error!

But placing

depends_on = [snowflake_database.STAR_DB] on the snowflake_schema did not fix the issue.

I also tried,
depends_on = [snowflake_warehouse.star_warehouse, snowflake_database.STAR_DB]
depends_on = [snowflake_warehouse.star_warehouse]

and also put
depends_on = [snowflake_warehouse.star_warehouse] on the database resource

but no luck.

Any advice?

**Comment by thenaturalist** [comment] 2022-03-08 22:08
Hi @hugh-nguyen, it's not possible to exactly tell what is going on without seeing your exact code, but here is my guess. 

You mention `Then I decided to rename "STAR_DB" to the lower case version "star_db".` but without specifying whether you renamed the TF resource name or the Snowflake internal name. 

For example: 

This should work & is conventional TF resource naming: 
``` 
resource "snowflake_database" "star_db" {
  provider = snowflake.sys_admin
  name     = "STAR_DB"
}
```

This should work but isn't conventional TF resource naming:
``` 
resource "snowflake_database" "STAR_DB" {
  provider = snowflake.sys_admin
  name     = "STAR_DB"
}
```

This should not work due to Snowflake's internal resource naming:
```
resource "snowflake_database" "star_db" {
OR
resource "snowflake_database" "STAR_DB" {
  provider = snowflake.sys_admin
  name     = "star_db"
}
```

So when you add `depends_on = [snowflake_database.STAR_DB]` but the Snowflake name in `snowflake_database.STAR_DB` is still lowercase, the same problem persists.

Generally, I would advise you to minimize using strings and assign values with resource data tags. If you do that, TF can automatically infer resource dependencies and `depends_on` is obsolete. For example:

```
resource "snowflake_database" "star_db" {
  provider = snowflake.sys_admin
  name     = "STAR_DB"
}

resource "snowflake_schema" "public" {
  provider            = snowflake.sys_admin
  database          = snowflake_database.star_db.name
  name                = "public"
}

resource "snowflake_table" "sales" {
  provider            = snowflake.sys_admin
  database          = snowflake_database.star_db.name
  schema            = snowflake_schema.public.name
  name                = "sales"
```

**Comment by hugh-nguyen** [comment] 2022-03-08 22:16
I changed it to use resource data tags, and can confirm that 
select * from star_db."public"."sales";
works

But I'am still getting the error.

**Comment by hugh-nguyen** [comment] 2022-03-08 22:19
I find it interesting that when defining the database resource, you do not need to specify the data warehouse, I wonder how it know which data warehouse to target.

**Comment by hugh-nguyen** [comment] 2022-03-08 23:06
I ended up removing the resources from the state file and it works now.

**Comment by simeonpilgrim** [comment] 2022-03-09 03:21
not sure how it "sits" in the terraform mindset, but in Snowflake, you really should avoid wrapping object names in double quotes unless by default you want spaces or case sensitive handling of your object names. 

Without double quotes all strings are cast to upper case. so `bob`, `Bob` , and `BOB` are the same as each other, but `"BOB"` is not the same as `"bob"`. There is a session parameter to ignore the case of quoted strings [QUOTED_IDENTIFIERS_IGNORE_CASE](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#controlling-case-using-the-quoted-identifiers-ignore-case-parameter). 

But if tools/users can avoid double quotes, then things work safer (until you put spaces and such, or try use object names as presentation tokens).

**Comment by DustinMoriarty** [comment] 2022-11-30 22:46
I noticed this as well. It is easy to accidentally get a broken terraform state which is a lot of work to clean up if lowercase names of objects are used. This can easily happen if you are concatenating other things onto the names in order to build them out of other strings. If lowercase names are not supported, then the provider should include a regex validator for all object names to assure that they conform with the expected format so that the user finds out earlier. However, I don't see a technical reason why the provider should be using case sensitive matching.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:48
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:48 UTC
Labels: bug
