### ISSUE TITLE
private_key authentication attribute conflicts with SNOWFLAKE_PASSWORD environment variable

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#1161] opened 2022-08-02 13:28 UTC
**Provider Version**

`0.25.36`

**Terraform Version**

`1.2.0`

**Describe the bug**

The `private_key` authentication attribute, when set explicitly as part of a `provider "snowflake {...}` config, conflicts with the `SNOWFLAKE_PASSWORD` environment variable.

**Expected behavior**

Perhaps this is an unrealistic expectation, but I would expect them not to conflict with each other.

**Code samples and commands**

`export SNOWFLAKE_PASSWORD=foo` (which I need for non-Terraform automation and scripts which run against my Snowflake resources)

```
provider "snowflake" {
  # See https://guides.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#2
  # for instructions on how to set up a user account to be used by Terraform.
  // required
  username    = "someuser"
  account     = "ABC123456"
  region      = "us-east-1"
  private_key = data.aws_kms_secrets.snowflake_private_key.plaintext["snowflake_private_key"]

  // optional
  role = "ACCOUNTADMIN"
}
```

Export the above environment variable and then use the above provider config and you'll get a conflict. 

If something is explicitly defined in Terraform config, as a private key is here, it should take precedence over an environment variable.

Note that I also got the same experience with the snowsql provider, so this conflict is almost surely coming from the snowflake golang SDK. But it would be nice if this provider could handle this situation.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:45
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:45 UTC
Labels: bug
