### ISSUE TITLE
External Table Partitions

### ISSUE THREAD

**Issue by Jacob-Holland-CKO** [Snowflake-Labs/terraform-provider-snowflake#448] opened 2021-02-16 16:19 UTC
**Provider Version**

0.23.2

**Terraform Version**

12

**Describe the bug**

When attempting to create an external table with partitions, TF crashes with an error code: 
`Error: rpc error: code = Unavailable desc = transport is closing`

**Expected behavior**

An external table to be created with appropriate partitions.

**Code samples and commands**

```terraform
resource snowflake_external_table example_table {
  database          = var.database
  schema            = var.schema
  name              = "table_name"
  file_format       = "type = json"
  location          = "@${var.database}.${var.schema}.${var.stage}"
  refresh_on_create = true

  column {
    name = "file_name"
    type = "text"
    as   = "metadata$filename"
  }

  partition_by = [
    1
  ]
}

```

**Additional context**

**Comment by nkacirek1** [comment] 2021-03-10 17:04
Running into this same issue. I think it's possibly due to a mis-spelling of **PARTITION** here 

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/fe55bbaf4eb2b0ac4f5949e8adff85bdec32701f/pkg/snowflake/external_table.go#L122

**Comment by fcraposo** [comment] 2021-05-14 14:55
Same issue, here. 

Any ETA on the fix? 

Has anybody managed to partition an external table using this resource, somehow?

**Comment by fcraposo** [comment] 2021-05-14 15:19
Any particular reason for the "two or more" partitions condition?

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/590c22ec40ed28c7d280192ed66c4d93623e32fd/pkg/snowflake/external_table.go#L121-L124

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:00
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:00 UTC
Labels: bug
