### ISSUE TITLE
Map Snowflake alias data types to actual data types

### ISSUE THREAD

**Issue by doino-gretchenliev** [Snowflake-Labs/terraform-provider-snowflake#1033] opened 2022-05-30 16:50 UTC
**Provider Version**

0.34.0

**Terraform Version**

0.14.2

**Describe the bug**

When you create a table with columns using alias data types like SMALLINT, Snowflake replaces those aliases with the actual data type used. In this case NUMBER(38,0). That causes changes to the table each time you apply. It would be nice if those TF recognize the usage of an alias.

**Comment by sfc-gh-ngaberel** [comment] 2023-06-22 00:25
Duplicate of https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/494

**Closed by sfc-gh-ngaberel** 2023-06-22 00:25 UTC
Labels: bug
