### ISSUE TITLE
Add an "undo" SQL command option in the task resource

### ISSUE THREAD

**Issue by aaronsteers** [Snowflake-Labs/terraform-provider-snowflake#285] opened 2020-10-25 20:20 UTC
**Is your feature request related to a problem? Please describe.**

If I use the sql "task" resource, there doesn't appear to be a way to create an "undo/destroy" command to run when changing/removing the resource. For instance, I'm considering using "tasks" for specialized grants and also for column masking, but I don't see a way to manage the deletion if/when the resource changes or is removed from my configuration.

**Describe the solution you'd like**

I'd like to have a way to specify a SQL command to run during destroy.

**Describe alternatives you've considered**

None

**Additional context**

* I imagine there could be some difficulty if the destroy_command fails - in case of simple sql syntax error or the affected resource being deleted/changed in a way that the destroy command can't succeed. For this case, it would probably need to print a warning with the SQL command that failed (hopefully along with the error message from snowflake) and perhaps still succeed the delete (or fail based on a config setting?).

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:02
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:02 UTC
Labels: feature-request
