### ISSUE TITLE
Boolean session parameters are not handled properly

### ISSUE THREAD

**Issue by aryann** [Snowflake-Labs/terraform-provider-snowflake#741] opened 2021-10-29 01:02 UTC
**Provider Version**

0.25.22

**Terraform Version**

1.0.3

**Describe the bug**

snowflake_task supports setting session parameters. For example, one can specify:

```
session_parameters = {
      "ODBC_QUERY_RESULT_FORMAT" = "ARROW",
}
```

Some Snowflake session parameters require a boolean value. However, the provider always coerces the value to a string. Consider this example:

```
session_parameters = {
      "ERROR_ON_NONDETERMINISTIC_MERGE" = false,  # This parameter is of type BOOLEAN in Snowflake.
}
```

The generated SQL is:

```
ALTER TASK "my_db"."my_schema"."my_task" SET ERROR_ON_NONDETERMINISTIC_MERGE = "false"
```

Note the quotes around false.

**Expected behavior**

The correct SQL should be:

```
ALTER TASK "my_db"."my_schema"."my_task" SET ERROR_ON_NONDETERMINISTIC_MERGE = false
```

**Comment by sfc-gh-asawicki** [comment] 2023-10-30 15:58
Hey @aryann. Thanks for creating the issue.

The task resource has been dramatically reworked since v.0.25.22. Can you confirm if the problem persists after upgrading to the newest provider version?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:52
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:52 UTC
Labels: bug
