### ISSUE TITLE
Task names clash when creating same task in different schema

### ISSUE THREAD

**Issue by EamonKeane** [Snowflake-Labs/terraform-provider-snowflake#522] opened 2021-04-22 11:09 UTC
**Provider Version**
0.24.0

**Terraform Version**
0.13.0

**Describe the bug**

There appears to be issue with the namespacing of tasks. When creating the same two tasks in two separate schemas in the same database, when terraform refreshes it attempts to over-write the tasks. The tasks successfully execute the first time. On a re-plan, the following appears:

```hcl
schema             = "schema1" -> "schema2" # forces replacement
```

**Expected behavior**
Creating the same tasks e.g. TASK_1, TASK_2 in two different schemas in the same database would lead to no terraform diff on the second apply.

**Code samples and commands**
```hcl
resource snowflake_task schema1 {
    name        = lookup(each.value, "name", null)
    database    = "DATABASE"
    schema      = schema1
    comment     = lookup(each.value, "comment", null)
    warehouse   = "WAREHOUSE"
    schedule    = lookup(each.value, "schedule", null)
    enabled     = lookup(each.value, "enabled", false)
    sql_statement = lookup(each.value, "sql_statement", false)
    session_parameters = {ODBC_QUERY_RESULT_FORMAT = "ARROW"}
    for_each = {
      "TASK_1" = {
        name = "TASK_1"
        schedule = "USING CRON 0 */2 * * * UTC"
        sql_statement = "COPY intO .."
        enabled = true
      },
      "TASK_2" = {
        name = "TASK_2"
        schedule = "USING CRON 0 */2 * * * UTC"
        sql_statement = "COPY intO .."
        enabled = true
      }
    }  
}

resource snowflake_task schema2 {
    name        = lookup(each.value, "name", null)
    database    = "DATABASE"
    schema      = schema2
    comment     = lookup(each.value, "comment", null)
    warehouse   = "WAREHOUSE"
    schedule    = lookup(each.value, "schedule", null)
    enabled     = lookup(each.value, "enabled", false)
    sql_statement = lookup(each.value, "sql_statement", false)
    session_parameters = {ODBC_QUERY_RESULT_FORMAT = "ARROW"}
    for_each = {
      "TASK_1" = {
        name = "TASK_1"
        schedule = "USING CRON 0 */2 * * * UTC"
        sql_statement = "COPY intO .."
        enabled = true
      },
      "TASK_2" = {
        name = "TASK_2"
        schedule = "USING CRON 0 */2 * * * UTC"
        sql_statement = "COPY intO .."
        enabled = true
      }
    }  
}
```

Add a schema prefix to the task names fixes the problem.

```hcl
resource snowflake_task schema1 {
    name        = lookup(each.value, "name", null)
    database    = "DATABASE"
    schema      = schema1
    comment     = lookup(each.value, "comment", null)
    warehouse   = "WAREHOUSE"
    schedule    = lookup(each.value, "schedule", null)
    enabled     = lookup(each.value, "enabled", false)
    sql_statement = lookup(each.value, "sql_statement", false)
    session_parameters = {ODBC_QUERY_RESULT_FORMAT = "ARROW"}
    for_each = {
      "TASK_1_schema1" = {
        name = "TASK_1_schema1"
        schedule = "USING CRON 0 */2 * * * UTC"
        sql_statement = "COPY intO .."
        enabled = true
      },
      "TASK_2_schema1" = {
        name = "TASK_2_schema1"
        schedule = "USING CRON 0 */2 * * * UTC"
        sql_statement = "COPY intO .."
        enabled = true
      }
    }  
}

resource snowflake_task schema2 {
    name        = lookup(each.value, "name", null)
    database    = "DATABASE"
    schema      = schema2
    comment     = lookup(each.value, "comment", null)
    warehouse   = "WAREHOUSE"
    schedule    = lookup(each.value, "schedule", null)
    enabled     = lookup(each.value, "enabled", false)
    sql_statement = lookup(each.value, "sql_statement", false)
    session_parameters = {ODBC_QUERY_RESULT_FORMAT = "ARROW"}
    for_each = {
      "TASK_1_schema2" = {
        name = "TASK_1_schema2"
        schedule = "USING CRON 0 */2 * * * UTC"
        sql_statement = "COPY intO .."
        enabled = true
      },
      "TASK_2_schema2" = {
        name = "TASK_2_schema2"
        schedule = "USING CRON 0 */2 * * * UTC"
        sql_statement = "COPY intO .."
        enabled = true
      }
    }  
}
```

**Comment by andrewdafonseca** [comment] 2021-12-20 13:23
This was fixed in https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/709

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:58
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:58 UTC
Labels: bug
