### ISSUE TITLE
Pipes and stages fail to recreate/modify on schema name change

### ISSUE THREAD

**Issue by andrewcylaw** [Snowflake-Labs/terraform-provider-snowflake#1042] opened 2022-06-06 18:31 UTC
**Provider Version**

```
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.32.0"
    }
  }
}
```

**Terraform Version**

```
$ terraform -v
Terraform v0.13.7
```

**Describe the bug**

I am currently working in a scenario where database objects (database, schema, tables, sequences, roles, users) are created and maintained by a different service, while data ingestion pieces are created using Terraform Snowflake (pipes, stages, integrations).

This works fine, but we recently renamed the schema and cannot redeploy our data ingestion infrastructure. Our project is setup where a module reads the schema name from AWS secrets manager, and passes it to a Snowflake module. 

The Snowflake module then manages resources for ingestion, but fails because the schema has been renamed, is not managed by Terraform, and errors out when attempting to `plan` or `apply`:

```
(...)
module.snowflake.snowflake_stage.snowflake_external_s3_stage: Refreshing state... [id=MY_DB|MY_OLD_SCHEMA|MY_STAGE]
module.snowflake.aws_iam_role_policy_attachment.snowpipe_s3_role_attachment: Refreshing state... [id=(...)]
module.snowflake.snowflake_pipe.snowpipe: Refreshing state... [id=MY_DB|MY_OLD_SCHEMA|MY_PIPE_NAME]

Error: 002003 (02000): SQL compilation error:
Schema 'MY_DB.MY_OLD_SCHEMA' does not exist or not authorized.
```

**Expected behavior**

I would expect the `pipe` to pick up a change in schema name, and recreate/modify it accordingly.

**Code samples and commands**

```
# This runs on my machine, but some sensitive info and pieces are missing so this snippet can't be run as-is
locals {
  region_code = substr(var.snowflake_credentials.snowflake_region, 0, 2)
  database    = var.snowflake_credentials.database
  schema      = var.snowflake_credentials.schema
}

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.32.0"
    }
  }
}

resource "snowflake_storage_integration" "snowflake_s3_integration" {
  name                 = upper("S3_INTEGRATION_${var.environment}")
  # (...)
}

resource "snowflake_stage" "snowflake_external_s3_stage" {
  name                = upper("SNOWPIPE_S3_STAGE_${var.environment}")
  url                 = "s3://${aws_s3_bucket.snowpipe_data_bucket.bucket}/folder/"
  database            = local.database
  schema              = local.schema
  storage_integration = snowflake_storage_integration.snowflake_s3_integration.name
}

resource "snowflake_pipe" "snowpipe" {
  name              = upper("SNOWPIPE_${var.environment}")
  database          = local.database
  schema            = local.schema
  comment           = "Pipe is managed by the Terraform stack."
  copy_statement    = <<-EOF
    COPY INTO ${local.database}.${local.schema}.MY_TABLE
        (...)
        FROM ((...), ${local.database}.${local.schema}.MY_SEQ.NEXTVAL
              FROM @${local.database}.${local.schema}.${snowflake_stage.snowflake_external_s3_stage.name} stg)
        FILE_FORMAT = (
          TYPE = 'CSV'
          COMPRESSION = 'GZIP'
        );
  EOF
  auto_ingest       = true
  aws_sns_topic_arn = aws_sns_topic.snowpipe_sns_topic.arn
}

```

**Additional context**

Seems related to https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/845

Something isn't working when an unmanaged object is renamed - it seems like the `plan` steps aren't picking up the change in name to modify or recreate the resource. I'd also like to avoid doing an entire `destroy` on my stack to change this.

I've considered doing a `destroy` to tear down the entire stack and rebuild it in the new schema. I've also considered importing the `schema` to be managed by Terraform, but that is not currently a viable solution for us.

Since we have separate environments for dev, qa, prod, I am also trying to avoid manually managing resources for each env if I could somehow get this to resolve using just automated `plan` and `apply` steps.

**Attempted workaround**
After renaming the schema, I tried to create an empty schema with the same before-rename name, and grant monitor and usage privileges to the executing Terraform role. Instead of getting errors on the pipe refresh, I'm now getting it on the stage refresh.

I hope I didn't miss anything obvious! Thanks for the help in advance!

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:46
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:46 UTC
Labels: bug
