### ISSUE TITLE
Cannot grant references privilege on materialized views via the provider

### ISSUE THREAD

**Issue by benoitgoujon** [Snowflake-Labs/terraform-provider-snowflake#738] opened 2021-10-27 13:03 UTC
Hi there,

Thank you for the awesome work. Here is the description of a bug I encountered.

**Provider Version**

0.25.19

**Terraform Version**

v1.0.7

**Describe the bug**

When I try to grant the `REFERENCES` privilege on a materialized view to a role, the plan fails with this error:

```
Error: expected privilege to be one of [OWNERSHIP SELECT], got REFERENCES
```

**Expected behavior**

I would expect this to be possible as described in the [official doc](https://docs.snowflake.com/en/user-guide/security-access-control-privileges.html#view-privileges).

**Code samples and commands**

Code:

```
resource "snowflake_materialized_view_grant" "materialized_view_grant" {
  database_name = "db"

  privilege = "REFERENCES"
  roles     = ["myrole"]

  on_future         = true
  with_grant_option = false
}
```

Command:

```
terraform plan
```

**Comment by yuan-glu** [comment] 2022-01-20 19:18
Met with the same issue here

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:52
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:52 UTC
Labels: bug
