### ISSUE TITLE
ROLE assign not working in Snowflake with terraform

### ISSUE THREAD

**Issue by ganpatp** [Snowflake-Labs/terraform-provider-snowflake#470] opened 2021-02-23 14:32 UTC
Hello Everyone,
I am new in terraform.
In TF file contains ROLE creation, USER creation, and Assign a role to USER when we run that file the first time its create USERS and ROLE successfully and throw an error like that ROLE does not exist
But when we run that file a second time it’s run successfully. So it assigns that role to a particular USER.

I attached the TF file as text.
![Capture](https://user-images.githubusercontent.com/19201030/108858029-b9e13d80-7611-11eb-99e3-595b29a82bc8.JPG)
[a.txt](https://github.com/chanzuckerberg/terraform-provider-snowflake/files/6029502/a.txt)

**Comment by chriskuchin** [comment] 2021-03-19 15:26
The problem here is that you are not telling terraform that the grants depend on the role creation. You either need to add a [depends_on clause](https://www.terraform.io/docs/language/meta-arguments/depends_on.html) or use the attributes on the role resource itself so that terraform can see the actual dependency tree rather than hard coded strings

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:00
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:00 UTC
Labels: bug
