### ISSUE TITLE
Not all roles in a schema grant get picked up after running terraform import

### ISSUE THREAD

**Issue by ahuynh3** [Snowflake-Labs/terraform-provider-snowflake#288] opened 2020-10-27 18:04 UTC
**Provider Version**
0.17.1

**Terraform Version**
0.13.5

**Describe the bug**
When trying to run a `terraform import` against an existing schema grant, not all of the existing roles are getting picked up. This issue only seems to occur on one of my schemas (all other schema grants were imported correctly). Not really sure why it's this specific schema where not all the roles are getting picked up for a particular grant. 

Not too sure if this example below will be useful, but let's say in Snowflake I have the `USAGE` privilege granted to roles `R1` and `R2` in `DB1.SCHEMA1`. Here's the import command I ran

```
terraform import "snowflake_schema_grant.db1__schema1__usage" "DB1|SCHEMA1|SCHEMA1|USAGE|False"
```

This imports successfully and in the terraform state, this is what the entry might look like

```
    {
      "mode": "managed",
      "type": "snowflake_schema_grant",
      "name": "db1__schema1__usage",
      "provider": "provider[\"registry.terraform.io/chanzuckerberg/snowflake\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "database_name": "DB1",
            "id": "DB1|SCHEMA1|SCHEMA1|USAGE|False",
            "on_future": false,
            "privilege": "USAGE",
            "roles": [
              "R1"
            ],
            "schema_name": "SCHEMA1",
            "shares": [],
            "with_grant_option": false
          },
          "private": "..."
        }
      ]
    }
```

I was expecting to see both "R1" and "R2" in the list of roles above. 

My terraform resource block looks something like this

```
resource "snowflake_schema_grant" "db1__schema1__usage" {
  database_name     = "DB1"
  on_future         = null
  privilege         = "USAGE"
  roles             = ["R1", "R2"]
  schema_name       = "SCHEMA1"
  shares            = null
  with_grant_option = false
}
```

And because the resource block and the state are not aligned, after running a `terraform plan`, I see this

```
  # snowflake_schema_grant.db1__schema1__usage must be replaced
-/+ resource "snowflake_schema_grant" "db1__schema1__usage" {
        database_name     = "DB1"
      ~ id                = "DB1|SCHEMA1|SCHEMA1|USAGE|False" -> (known after apply)
        on_future         = false
        privilege         = "USAGE"
      ~ roles             = [ # forces replacement
            "R1",
          + "R2",
        ]
        schema_name       = "SCHEMA1"
      - shares            = [] -> null
        with_grant_option = false
    }
```

After running a `terraform apply`, it looks like the state picks up the additional role, but a subsequent `terraform plan` thinks that it still wants to add `R2` to the list of roles in the resource.

My final thoughts are that I'm not entirely sure if this is a bug in the provider or a misconfiguration of my existing Snowflake resources, but just wanted to see if the community had any ideas. How does the Snowflake provider capture existing schema grants in the backend?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:02
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:02 UTC
Labels: bug
