### ISSUE TITLE
Cannot Create/Update Stage with File Format

### ISSUE THREAD

**Issue by mhconradt** [Snowflake-Labs/terraform-provider-snowflake#1067] opened 2022-06-20 19:56 UTC
**Provider Version**

```
Terraform v1.2.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.2.0
+ provider registry.terraform.io/snowflake-labs/snowflake v0.33.0
```

**Describe the bug**

I cannot create a stage object with a file format. This is optional but quite useful.

**Expected behavior**

I should be able to create a stage object with a file format.

**Code samples and commands**

```
resource "snowflake_file_format" "default" {
  name        = "EXAMPLE_FILE_FORMAT"
  database    = "EXAMPLE_DB"
  schema      =  "EXAMPLE_SCHEMA"
  format_type = "PARQUET"
  compression = "AUTO"
}

resource "snowflake_stage" "default" {
  name        = "EXAMPLE_STAGE"
  url         = "s3://EXAMPLE-BUCKET/"
  database    =  "EXAMPLE_DB"
  schema      =  "EXAMPLE_SCHEMA"
  file_format = snowflake_file_format.default.name
}
```

**Additional context**

This is actually fairly simple, the provider is just wrapping the file format name in parentheses and Snowflake interprets this as a list of length one, which is actually a syntax error.
```
CREATE STAGE "EXAMPLE_DB"."EXAMPLE_SCHEMA"."EXAMPLE_STAGE" URL = 's3://BUCKET/' FILE_FORMAT = (DEFAULT_FILE_FORMAT)
```

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:45
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:45 UTC
Labels: bug
