### ISSUE TITLE
Error: Failed to install provider Error while installing chanzuckerberg/snowflake v0.25.19

### ISSUE THREAD

**Issue by caiolauro** [Snowflake-Labs/terraform-provider-snowflake#800] opened 2021-12-27 16:27 UTC
**Provider Version**

0.25.19 / 0.25.29 / 0.25.31

**Terraform Version**

0.14.10

**Describe the bug**

After running `terraform init` I get this error:
`Error: Failed to install provider
Error while installing chanzuckerberg/snowflake v0.25.19: could not query
provider registry for registry.terraform.io/chanzuckerberg/snowflake: failed
to retrieve authentication checksums for provider: the request failed after 2
attempts` 

**Expected behavior**

chanzuckerberg/snowflake v0.25.19 (or 0.25.29, 0.25.31)  to be installed successfully

**Code samples and commands**

Example of the providers and terraform block informed in the main.tf files.
Note: I've tried with other chanzuckerberg/snowflake versions (0.25.29, 0.25.31) as well.

```
provider "aws" {
  region = var.region
  assume_role {
    role_arn = var.assume_role_arn
  }
}

provider "snowflake" {
  username         = var.SYSTEM_TEST_USER
  account          = var.SYSTEM_TEST_ACCOUNT
  region           = var.SYSTEM_TEST_REGION
  private_key_path = var.SYSTEM_TEST_PRIVATE_KEY_PATH
  role             = "SYSADMIN"
}

terraform {
  required_version = "~> 0.14.10"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.35.0"
    }
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.25.19"
    }
  }

```
**Additional context**

-

**Comment by pen-sadiq** [comment] 2022-01-07 00:49
I'm getting the same using Terraform cloud and trying to init (terraform logged in, using CLI workspace):

**Provider Version: 0.25.32**
**Terraform Version: 1.1.2**

│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider chanzukerberg/snowflake: provider registry
│ registry.terraform.io does not have a provider named registry.terraform.io/chanzukerberg/snowflake
│
│ All modules should specify their required_providers so that external consumers will get the correct providers when
│ using a module. To see which modules are currently depending on chanzukerberg/snowflake, run the following command:
│     terraform providers

```
terraform {
  cloud {
    organization = "my-organization"
    workspaces {
      name = "my-cloud-workspace"
    }
  }

  required_version = "~> 1.1.2"
  required_providers {
    snowflake = {
      source  = "chanzukerberg/snowflake"
      version = "0.25.32"
    }
 }
}
```
Other versions of Snowflake were tested, same error.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:50
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:50 UTC
Labels: bug
