### ISSUE TITLE
snowflake_table change_tracking enables when not set (to different value than default)

### ISSUE THREAD

**Issue by depowell** [Snowflake-Labs/terraform-provider-snowflake#723] opened 2021-10-17 23:05 UTC
**Provider Version**
     source  = "chanzuckerberg/snowflake"
      version = "0.25.21" when upgrading from "0.25.12"

**Terraform Version**

latest

**Describe the bug**

https://registry.terraform.io/providers/chanzuckerberg/snowflake/0.25.21/docs/resources/table#optional
change_tracking was set to false on tables where we did not specify this parameter in terraform
change_tracking was set to false (when default is false) on resources where this parameter was not specified

we already created tables and had streams on them, but this update broke the change tracking on those tables since before there was no default value

**Expected behavior**

default value is not changed if parameter is not set, or any paramater in snowflake is not changed from terraform provider updates in minor versions (especially for optional parameters).

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:53
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:53 UTC
Labels: bug
