### ISSUE TITLE
null_if with backslash will always have changes when applying

### ISSUE THREAD

**Issue by deanmorin** [Snowflake-Labs/terraform-provider-snowflake#781] opened 2021-12-08 02:05 UTC
**Provider Version**

`registry.terraform.io/chanzuckerberg/snowflake v0.25.29`

**Terraform Version**

`Terraform v1.0.10`

**Describe the bug**

I want to create a file format using the `snowflake_file_format` resource. 

If I use `null_if = ["\\\\N"]`, and apply, it creates a file format in snowflake with `"NULL_IF":["\\N"]`. This is what I want, but the next time I run `terraform apply` I see:

```
 # module.snowflake.snowflake_file_format.meltano_csv will be updated in-place
  ~ resource "snowflake_file_format" "my_format" {
        id                             = "MYDB|FILE_FORMATS|CSV"
        name                           = "CSV"
      ~ null_if                        = [
          - "\\N",
          + "\\\\N",
        ]
        # (32 unchanged attributes hidden)
    }
```

Even if I apply these changes, I'll see the exact same thing the next time I run `terraform apply`.

**Expected behavior**

It should consider `"\\\\N` in the `.tf` file to be equivalent to `\\N` in the state file, or have `\\\\N` in the state file.

**Code samples and commands**

```
resource "snowflake_database" "test" {
  provider = snowflake.sysadmin
  name     = "TEST"
}

resource "snowflake_schema" "test_file_formats" {
  provider = snowflake.sysadmin
  database = snowflake_database.test.name
  name     = "FILE_FORMATS"
}

resource "snowflake_file_format" "csv" {
  provider = snowflake.sysadmin
  name        = "CSV"
  database    = snowflake_database.test.name
  schema      = snowflake_schema.test_file_formats.name
  format_type = "CSV"
  null_if     = ["\\\\N"]

  lifecycle {
    ignore_changes = [
      binary_format,
      compression,
      date_format,
      encoding,
      escape,
      escape_unenclosed_field,
      field_delimiter,
      field_optionally_enclosed_by,
      record_delimiter,
      time_format,
      timestamp_format,
    ]
  }
}
```

Run `terraform apply` twice in a row to see the issue.

**Comment by jacobcrp** [comment] 2023-05-14 21:42
I'm also having this issue. Guessing it's not a priority?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:51
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:51 UTC
Labels: bug
