### ISSUE TITLE
Enabling Multiple Grants Still Revokes Existing Grants

### ISSUE THREAD

**Issue by davidov541** [Snowflake-Labs/terraform-provider-snowflake#1845] opened 2023-05-31 18:31 UTC
**Provider Version**

0.65.0

**Terraform Version**

1.4.6

**Describe the bug**

If you have a role grant that has allow_multiple_grants set to false, and then other roles or users are granted to that role, the next time that the resource is deployed, it will revoke those grants, which follows. But if I then set allow_multiple_grants to true, it will still try to revoke those roles or users, even while it is setting allow_multiple_grants to true. This doesn't make sense, and causes a situation where you have to either handle the revocation immediately, or you have to remove the grant from the state and then reimport it to avoid revoking users and roles that you are trying to not revoke anymore.

**Expected behavior**

No revocations occur when allow_multiple_grants is switching from false to true.

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

This particular issue was brought up due to the upgrade to version 0.65.0. We were using the default value for allow_multiple_grants, so when the upgrade happened, the values were changed to true, which is fine with us, but it also caused the resource to be redeployed, revoking alot of users and roles that had been granted to the roles since we had deployed that resource.

**Comment by jcourteau** [comment] 2023-06-01 00:15
Oddly, rolling back to 0.64 after running into this is hard. If the state has the refreshed role grants, they'll have IDs that contain _all_ the grantees (instead of just the ones that I want to manage), and even version 0.64 will try to revoke those "extra" grants.

I ended up having to `terraform state delete <x>; terraform import <x> 'role|<the one role I wanted to manage>|'`

**Comment by davidov541** [comment] 2023-06-01 00:17
@jcourteau sadly I think this is what we'll have to do too. I deployed to 2/3 environments before realizing what was going on so thankfully it'll just be the one. Good to know this approach works though!

**Comment by dmeskis** [comment] 2023-06-02 20:24
Ran into this today as well on 0.65

**Comment by chhsiung** [comment] 2023-06-06 19:32
We are also experiencing issues around `enable_multiple_grants`... we don't manage all our roles/grants in terraform so cannot have `snowflake_role_grants` revoke everything not explicitly listed

**Comment by aka-ao** [comment] 2023-06-07 02:16
> We are also experiencing issues around `enable_multiple_grants`... we don't manage all our roles/grants in terraform so cannot have `snowflake_role_grants` revoke everything not explicitly listed

We have the same problem.
It seems to be caused by the fact that the default value used to be false, but now it is true

**Comment by jcourteau** [comment] 2023-06-07 16:27
> It seems to be caused by the fact that the default value used to be false, but now it is true

It's a little deeper than that unfortunately. The old feature was actually broken, and acted like it was set to "true" all the time. But in fixing the feature, it broke the other way.

**Comment by bennylu2** [comment] 2023-06-07 16:37
This is occurring for us as well and made provider unusable once again. Pinning to `<=0.64` has resolved it for the time being but we are not confident in the provider with new breaking changes constantly being introduced

**Comment by christyvp** [comment] 2023-06-07 22:29
Seeing this issue on 0.66, which we are trying to update to, after having issues on previous versions that made us pin to 0.56.2

**Comment by jakemingolla** [comment] 2023-06-09 20:16
This breaks using Okta to manage user provisioning as a SAML provider

**Comment by Relativity74205** [comment] 2023-06-12 05:55
The same for us, it breaks our AzureAD setup.

**Comment by liamjamesfoley** [comment] 2023-06-13 00:09
Following, B/C I need to upgrade our provider version b/c of this:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1868
But cannot do to this issue.

**Comment by willwooten** [comment] 2023-06-13 16:25
Similar problems for me after update to 0.66. Described here: #1877

**Comment by gu-xie** [comment] 2023-06-15 02:27
+1 here as we're trying to resolve #1868 by upgrading but this destroys all of our roles and grants.

**Comment by milanrm** [comment] 2023-06-15 07:15
I am also facing the issue and reported in the discussion.  
https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/1879.

Its blocking us. Can someone suggest any working version as of now?

**Comment by dlouseiro** [comment] 2023-06-15 17:53
Same issue here. Just noticed that terraform was prepared to revoke the permissions of all users!

**Comment by milanrm** [comment] 2023-06-16 06:08
FYI, To make things work now I pinned down the provider version to
**`0.64`**

https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1816#issuecomment-1586994126

 and run the workaround in snowflake UI like its mentioned in the above URL.

**Comment by merlixo** [comment] 2023-06-16 10:14
As temporary workaround, we added this lifecycle config to our grant resources:
```
resource "snowflake_schema_grant" "schema_grant" {
  database_name     = "my_db"
  schema_name       = "my_schema"
  privilege         = "USAGE"
  roles             = ["my_role"]
  lifecycle {
    ignore_changes = [roles]
  }
}

resource "snowflake_role_grants" "role_grant" {
  role_name         = "my_role_1"
  roles             =  ["my_role_2"]
  lifecycle {
    ignore_changes = [roles, users]
  }
}
```

**Comment by walarue** [comment] 2023-06-16 15:31
running into this as well -- we are "working around" it by using `lifecycle` with `ignore_changes` like @merlixo, but this means that we can't control grants from that point on in terraform. This is a difficult situation given that we can't assume all grants will come from terraform (if using some external identity provider or other auth service)

**Comment by sfc-gh-dschonberg** [comment] 2023-06-20 18:10
Please see https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/1890 for discussion of how we are thinking about this issue.

**Comment by ppo-38** [comment] 2023-07-10 08:50
I also have this problem with version > 0.64.0 and I would like to have an advice before upgrading to 0.67.0 or higher which seems to be resolved in #1898. For Information, I need to manage users grants outside of terraform.

Observed behaviors :

- If I plan with 0.67.0 version (or higher) without changing anything in the code, the plan doesn't show any change => `No changes. Your infrastructure matches the configuration`. So it seems to be ok for an upgrade without impacts.
- But if I plan with 0.67.0 version and if I add enable_multiple_grants = true in the snowflake_role_grants resources in the code, the plan shows hundreds of changes like `~ enable_multiple_grants = false -> true` or + `enable_multiple_grants = true`

So what would be the process to keep current and future grants managed outside of terraform ? Do we have to set the enable_multiple_grants attribute value to true in the code as the same time as upgrading to 0.67.0 or not ?

**Comment by Nakulbajaj101** [comment] 2024-01-16 09:22
I want to know the same.
On database role grants we added some roles we wanted to manage, but applied with enable multiple grants as False.
We now want to change that, but the plan with multiple grants True, still want to destroy roles not managed in Terraform.
Do I have to add all the roles and apply, and then remove those roles and re apply, and manually add privileges after the reapply?

**Comment by sfc-gh-jcieslak** [comment] 2024-02-08 15:44
Hi all, please use the newest grant resources. They have "implicitly set" `enable_multiple_grants` to true and should be more stable than old `snowflake_x_grant` resources. Recently we prepared [a short guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/technical-documentation/resource_migration.md) on migrating any deprecated resource to their new counter-part (grants were chosen as an example). Closing the issue as we are not planning on supporting deprecated resources.

**Closed by sfc-gh-jcieslak** 2024-02-08 15:44 UTC
Labels: bug
