### ISSUE TITLE
Create resource snowflake_user_grant

### ISSUE THREAD

**Issue by xlagg5** [Snowflake-Labs/terraform-provider-snowflake#973] opened 2022-04-14 12:01 UTC
**Is your feature request related to a problem? Please describe.**

Query like `GRANT MONITOR ON USER "SNOWFLAKE" to role "DEVELOPER";` has to be executed to grant privilege's to see query history.
Currently this SQL cannot be done by terraform because resource like snowflake_grant_user is not available.

**Describe the solution you'd like**

I would like to have resource similar to https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/user_ownership_grant 
but with option to grant MONITOR privilege's . Because currently only OWNERHSHIP option is possible.
Something like snowflake_user_grant where I can specify what type of grants should be added. 

Example of code I'd like to implement: 

```
resource "snowflake_user_grant" "airflow" {

  on_user_name = snowflake_user.user.snowflake
  privilege      = "MONITOR"

  roles = [
    snowflake_role.developer.name,
  ]
}
```

**Comment by hragarwal** [comment] 2022-07-12 08:23
Any updates when this can be available ?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:47
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:47 UTC
Labels: feature-request
