### ISSUE TITLE
Add Description+Example for snowflake_function 

### ISSUE THREAD

**Issue by ds-slohr** [Snowflake-Labs/terraform-provider-snowflake#1029] opened 2022-05-30 06:45 UTC
**Is your feature request related to a problem? Please describe.**

Please add a description+example for snowflake_function. Its always hard to implement something just with the basic information of the parameters. 

**Describe the solution you'd like**

An example with a basic javascript if/else function would be great to understand how your script works.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:46
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:46 UTC
Labels: feature-request
