### ISSUE TITLE
Create database from share fails

### ISSUE THREAD

**Issue by bob-zarkoob** [Snowflake-Labs/terraform-provider-snowflake#2712] opened 2024-04-15 19:05 UTC
### Terraform CLI and Provider Versions

Provider: 0.88.0
CLI: 1.8.0

### Terraform Configuration

```terraform
resource "snowflake_database" "UAT_INBOUND" {
  comment                     = "db shared by ABC"
  data_retention_time_in_days = 0
  name                        = "UAT_INBOUND"
  from_share                  = {
    provider = "ORGNAME.AUTO_FULFILLMENT$PUBLIC_AWS_US_EAST_1"
    share    = "SANDBOX"
  }
}
```

### Expected Behavior

Create the database

### Actual Behavior

fails with this weeror: 
Share '"ORGNAME.AUTO_FULFILLMENT$PUBLIC_AWS_US_EAST_1.SANDBOX"' does not exist or not authorized.

but when I run the sql command I can create the share, the problem is when terraform is generating the SQL statement, the statement is incorrect. I pull it from query history and it is like this:
```sql
CREATE DATABASE UAT__INBOUND FROM SHARE "ORGNAME.AUTO_FULFILLMENT$PUBLIC_AWS_US_EAST_1"."SANDBOX";
```

while it should be like this:
```sql
CREATE DATABASE UAT__INBOUND FROM SHARE "ORGNAME"."AUTO_FULFILLMENT$PUBLIC_AWS_US_EAST_1"."SANDBOX";
```
if you see, the quote marks around (.) in the share name after the orgname is missing.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-jcieslak** [comment] 2024-04-16 06:42
Hey 👋 
Please, take a look [here](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#behavior-change-external-object-identifier-changes). We expect <account_locator> in the `provider` field instead of <org_name>.<accout_name>. Try, replacing the provider field value with the account locator, and let me know if that works.

**Comment by bob-zarkoob** [comment] 2024-04-16 16:18
Hi @sfc-gh-jcieslak ,
Account locator is consisting of: <org_name> and <accout_name> seperated by a dot.
If I copy paste the account locator from interface same thing gets copied. 
Conclusion: I am putting account locator in the provider.

**Comment by bob-zarkoob** [comment] 2024-04-16 16:31
Hi @sfc-gh-jcieslak ,

If you look at this article:
https://docs.snowflake.com/en/sql-reference/sql/create-database#:~:text=Shared%20Database%20(from%20a%20Share)
it shows that the SQL should be like this:
```sql
CREATE DATABASE <name> FROM SHARE <provider_account>.<share_name>;
```
Since this is a cross cloud share, snowflake did an auto fulfilment and replicated data to the destination account's cloud provider.

I did extract the sql that terraform provider is generating and put it up there, if you run it, it will fail. 
If you change it like the second one, it will work. 

And this used to work before, because I just removed that DB from state file and added it again and it is not running, the only change was that I my provider version got updated to the latest, I am not sure when I ran it first which version I was on.

I checked my history of executions, and realized this behavior has been changed, because the last time I created a share DB, Terraform created an script like the second one (which works).

One way to make it work always is to change the generated SQL to look like this:

```sql
CREATE DATABASE identifier('UAT__INBOUND') FROM SHARE identifier('ORGNAME.AUTO_FULFILLMENT$PUBLIC_AWS_US_EAST_1.SANDBOX');
```
this will always work.

**Comment by sfc-gh-jcieslak** [comment] 2024-04-17 12:35
Hey 👋 , 
I know that the documentation is proposing this format `<provider_account>.<share_name>`, but `<account_locator>` should also be acceptable as it's a deprecated format we're supporting right now ([check the difference here](https://docs.snowflake.com/en/user-guide/admin-account-identifier)). In the migration notes I linked previously, you can see the format `<provider_account>.<share_name>` won't work, because previously the provider was quoting the identifier in the wrong way (with the right way the new format is not possible as it worked previously "by accident"). We will be migrating to the new format, but for the time being, please use the account locator that can be retrieved with the [CURRENT_ACCOUNT](https://docs.snowflake.com/en/sql-reference/functions/current_account) query.

**Comment by bob-zarkoob** [comment] 2024-04-17 16:29
Hi 👋,
I have tried what you suggested but it fails. I think the reason is overlooked, The shared database I am creating is a special kind, it is from a share in a different cloud provider, and I cannot just use the `<provider_account>`. To give you more details:

select current_account() returns:  `the_abc_account` 
Share Name is: `PL_TEST`

We are using is new feature that Snowflake will replicate your data to the destination cloud provider without you needing to create an account and replicate your data (it is call create listing for specific customers).
For example, our snowflake is in `AWS_US_EAST_1`, but data that is being shared with us is in Azure, and snowflake automatically created an area and replicated data in AWS and the address to access it is: `the_abc_account.AUTO_FULFILLMENT_ABC$PUBLIC_AWS_US_EAST_1` 

if I use `the_abc_account`, it will fail, because I cannot see that account in the current cloud provider.
what I have to use is `the_abc_account.AUTO_FULFILLMENT_ABC$PUBLIC_AWS_US_EAST_1` which `AUTO_FULFILLMENT_ABC$PUBLIC_AWS_US_EAST_1` is the replicated copy of data in AWS that I can use.



When the provider is generating the SQL, puts a quote around `the_abc_account.AUTO_FULFILLMENT_ABC$PUBLIC_AWS_US_EAST_1` which makes it like this:

```sql
CREATE DATABASE SHARED_DB FROM SHARE "the_abc_account.AUTO_FULFILLMENT_ABC$PUBLIC_AWS_US_EAST_1".PL_TEST
```
but it should be like this: 
```sql
CREATE DATABASE SHARED_DB FROM SHARE "the_abc_account"."AUTO_FULFILLMENT_ABC$PUBLIC_AWS_US_EAST_1".PL_TEST
```
or it should be like this:
```sql
CREATE DATABASE SHARED_DB FROM SHARE  identifier('the_abc_account.AUTO_FULFILLMENT_ABC$PUBLIC_AWS_US_EAST_1.PL_TEST')
```

your suggestion is not working for reason I explained, and I couldn't find any work around for it.

**Comment by sfc-gh-jcieslak** [comment] 2024-04-18 07:58
Ok, now I can see the issue, thanks for the detailed explanation. I'll try to reproduce the issue and see if we can propose anything as a workaround for now.

**Comment by sfc-gh-jcieslak** [comment] 2024-04-18 11:26
Ok, I dug deeper into the codebase behind creating a database from share and I think the workaround that may work would be to quote only inside the provider field like this:
```
resource "snowflake_database" "UAT_INBOUND" {
  comment                     = "db shared by ABC"
  data_retention_time_in_days = 0
  name                        = "UAT_INBOUND"
  from_share                  = {
    provider = "ORGNAME\".\"AUTO_FULFILLMENT$PUBLIC_AWS_US_EAST_1"
    share    = "SANDBOX"
  }
}
```
Then it should result in SQL similar to this:
```sql
CREATE DATABASE SHARED_DB FROM SHARE "the_abc_account"."AUTO_FULFILLMENT_ABC$PUBLIC_AWS_US_EAST_1"."PL_TEST"
```
It's a workaround for now, but later on, we would like to fix this issue and make it work for every type of identifier (it's on our roadmap; [identifiers redesign](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#identifiers-rework)).

**Comment by bob-zarkoob** [comment] 2024-04-18 15:21
awesome, this is a great workaround, do you think you can change the label of this ticket to bug too so it would be in the radar? Right now, it is general-usage.

**Comment by sfc-gh-jcieslak** [comment] 2024-07-11 12:18
Hey 👋 
Yesterday we published a new provider version with the new shared_database resource that should not have this issue anymore. Closing as this is something strongly connected how the old database resource was working underneath. Right now, the recommended account identifier is a must in the new resource and this issue shouldn't occur. Please migrate whenever you can and let us know (create another issue) if the issue still persists with your case. 
Thank You for reporting the issue.

**Closed by sfc-gh-jcieslak** 2024-07-11 12:18 UTC
Labels: bug, resource:database, category:identifiers
