### ISSUE TITLE
[bug] spurious diff on snowflake_table column

### ISSUE THREAD

**Issue by ryanking** [Snowflake-Labs/terraform-provider-snowflake#410] opened 2021-01-08 18:02 UTC
Suppress diffs like this–

```
~ resource "snowflake_table" "c7n_metadata" {
    ...
    ~ column {
          name = "RECORDED_AT"
        ~ type = "TIMESTAMP_LTZ(9)" -> "TIMESTAMP_LTZ"
      }
	...
    }
```

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:01
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:01 UTC
Labels: bug
