### ISSUE TITLE
Snowflake provider produced an invalid new value for output when used in a for_each loop

### ISSUE THREAD

**Issue by gmirsky** [Snowflake-Labs/terraform-provider-snowflake#568] opened 2021-06-10 13:05 UTC
**Provider Version**

0.25.5

**Terraform Version**

Terraform v1.0.0

**Describe the bug**

Error encountered when using snowflake_stage in a for_each loop in a module and referencing the output values by another module.
 ```
 Error: Provider produced inconsistent final plan
 │
 │ When expanding the plan for module.snowflake_cloud_stage_grant.snowflake_stage_grant.stage_grant["snowflake_test_data/avro/"] to include new values
 │ learned so far during apply, provider "registry.terraform.io/chanzuckerberg/snowflake" produced an invalid new value for .stage_name: was
 │ cty.StringVal("snowflake_test_data_avro"), but now cty.StringVal("SNOWFLAKE_TEST_DATA_AVRO").
 │
 │ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
 Workaround was to add an upper() function to the output statement from the module that contained the resource snowflake_stage.
 
```
 output "name" {
  value = {
    for k, v in snowflake_stage.stage : k => upper(v.name)
  }
}
```
**Expected behavior**

Case of the name output to remain the same (or at least predictable).

**Code samples and commands**

See above.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:57
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:57 UTC
Labels: bug
