### ISSUE TITLE
[bug] suppress file_format field diffs

### ISSUE THREAD

**Issue by ryanking** [Snowflake-Labs/terraform-provider-snowflake#409] opened 2021-01-08 18:00 UTC
Suppress diffs like this–

```
# snowflake_stage.c7n_metadata will be updated in-place
~ resource "snowflake_stage" "c7n_metadata" {
	...
    ~ file_format        = "TYPE = JSON NULL_IF = []" -> "TYPE=JSON"
    ...
  }
```

**Comment by iserko** [comment] 2021-01-19 12:51
@ryanking have another example for you (running provider version 0.20.0)

Given TF like:
```
  file_format = <<EOT
FIELD_DELIMITER = ' '  FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = GZIP
EOT
```

I get the following diff:
```
      ~ file_format         = <<~EOT
          - FIELD_DELIMITER =   FIELD_OPTIONALLY_ENCLOSED_BY = \" COMPRESSION = GZIP
          + FIELD_DELIMITER = ' '  FIELD_OPTIONALLY_ENCLOSED_BY = '"' COMPRESSION = GZIP
        EOT
```

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:01
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:01 UTC
Labels: bug
