### ISSUE TITLE
[General Usage]: How to stop replacing schema while migrating

### ISSUE THREAD

**Issue by cyclonstep** [Snowflake-Labs/terraform-provider-snowflake#3015] opened 2024-08-26 02:04 UTC
### Terraform CLI Version

1.9.5

### Terraform Provider Version

0.94.1

### Terraform Configuration

```terraform
resource "snowflake_schema" "test" {
  database                    = snowflake_database.test_db.name
  name                        = "TEST"
  data_retention_time_in_days = 1
  depends_on = [
    snowflake_database.test_db
  ]

  lifecycle {
    prevent_destroy = true
  }
}
```

### Category

category:resource

### Object type(s)

data_source:schemas

### Expected Behavior

The old existing schema will not be replaced by the newest code applications.

### Actual Behavior

It will replaced and all of the data missing.

### Steps to Reproduce

1. Upgrade the provider versions
2. terraform plan / apply
3. we will see that the schema will be replaced.

### How much impact is this issue causing?

High

### Additional Information

Hello, Thank you very much for all hard works in regards to maintaining this terraform providers. 

I've been trying to migrate the terraform (especially grant roles) in these past few days from the old 0.71.0 to the latest 0.94.1.

But when I tried to apply the code, looks like we need to replace all of the schemas. I read in migration_guide that there was some breaking changes and refactoring in the schema resources itself. but is there anything that we can do to prevent the replacement of the object itself while applying? Maybe I'm missing something but I cannot find any way to actually mitigate this situations. 

What we've been tested:
- follow resource migration guide -> Need replacement
- using terraform import -> Need replacement
- prevent destroy on lifecycle -> Error, still need to be replaced.  

I've been testing out the behaviour and if we apply this, it will destroy all of the data in the schema. We understand that we have Undrop and Clone in snowflake to mitigate this situations but in our current state we cannot afford any downtime and complicated side effects because our snowflake environment is being used by myriad of processes in our business. 

As always, thank you very much.

**Comment by sfc-gh-jcieslak** [comment] 2024-08-26 09:02
Hey @cyclonstep 👋 
I tried to migrate the following configuration from v0.71.0 to v0.94.1
```terraform
resource "snowflake_database" "test_db" {
  name = "test_db_schema_upgrade"
}

resource "snowflake_schema" "test" {
  database                    = snowflake_database.test_db.name
  name                        = "TEST"
}
```
and got this plan (a little trimmed, because it's big):
```plain
```

**Comment by cyclonstep** [comment] 2024-08-26 09:37
@sfc-gh-jcieslak Thank you for your answer! 
Indeed when I was adding `is_transient=false` to the code itself, the plan now correctly stops replacing the schema itself. 
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # snowflake_schema.feed will be updated in-place
  ~ resource "snowflake_schema" "feed" {
        id                                            = "TEST_DB|TEST"
        name                                          = "TEST"
      ~ show_output                                   = [
          - {
              - created_on      = "2022-05-23 15:58:32.497 +0900 JST"
              - database_name   = "TEST_DB"
              - dropped_on      = "0001-01-01 00:00:00 +0000 UTC"
              - is_current      = false
              - is_default      = false
              - name            = "TEST"
              - owner           = "SYSADMIN"
              - owner_role_type = "ROLE"
              - retention_time  = "1"
                # (2 unchanged attributes hidden)
            },
        ] -> (known after apply)
      ~ with_managed_access                           = "false" -> "default"
        # (22 unchanged attributes hidden)
    }

```

Let me check this further whether or not is there any other side-effects going on. 
That would be helpful if you can implement the state upgrader in the 0.95.0. Of course I will check what are the breaking changes that will occurred on my end but as for now, I will go with your recommendations for the current version.

**Comment by sfc-gh-jcieslak** [comment] 2024-08-26 12:08
Also, keep in mind that before v1.0, we're introducing many breaking changes, so it would be better to upgrade version by version with the [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md) in mind. Making such a big version jump may break many other resources without proper adjustments.

**Comment by cyclonstep** [comment] 2024-09-05 00:24
@sfc-gh-jcieslak Hello Jan, sorry for replying so late. I see, so there is a limitation on the SDK side right. I saw your documentation commits and thank you for the assistance 👍 . I think this would be quite an issue and it is so easy with one careless terraform apply just to replace everything. If there are things that I could help, please let me know. 

To anyone who will read this, **please read the plan before applying**

**Comment by sfc-gh-jcieslak** [comment] 2024-09-05 08:05
Yeah, in the future, we plan to migrate to the newest Terraform Framework SDK, which should allow for more flexibility, but for now, we are very limited and have to make a lot of workarounds. Thank you for your understanding 🙏. If you have any questions, feel free to ask. Otherwise, I guess we can close this thread (It was closed previously accidentally by GitHub bot).

**Comment by chrisweis** [comment] 2024-10-04 05:43
This thread and the migration guide were immensely helpful.  Gotta say, a year ago a glitch like this would have been so much more painful, consumed hours to troubleshoot, but your detailed reply @sfc-gh-jcieslak was superb, and the rising quality of this Terraform provider is clearly visible.  Thank you!!!

**Comment by sfc-gh-jcieslak** [comment] 2024-10-04 07:45
Hey @chrisweis 👋 
No problem, Thank You for your kind words 🙏

**Comment by sfc-gh-jcieslak** [comment] 2024-10-15 14:43
Closing the thread as the solution was provided, and to be working confirmed.

**Closed by sfc-gh-jcieslak** 2024-10-15 14:43 UTC
Labels: bug
