### ISSUE TITLE
[Bug]: Terraform import snowflake_function Error: object does not exist

### ISSUE THREAD

**Issue by mike-soukup-vividseats** [Snowflake-Labs/terraform-provider-snowflake#3094] opened 2024-09-19 20:14 UTC
### Terraform CLI Version

1.5.7

### Terraform Provider Version

0.95.0

### Terraform Configuration

```terraform
When I follow the docs https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.95.0/docs/resources/function#import
to import a snowflake_function resource, I get an error after the Import was prepared that the object does not exist. This doesn't help resolve the issue in anyway and I am stuck. 

resource "snowflake_function" "flatten_ga_params" {
  name     = "flatten_ga_params"
  provider = snowflake.sys_admin
  database = "LANDING"
  schema   = "GA"
  arguments {
    name = "E"
    type = "VARIANT"
  }
  comment     = "Function to flatten GA4 event params"
  return_type = "VARIANT"
  language    = "javascript"
  statement   = "function code here"
}

Import statement: terraform import snowflake_function.flatten_ga_params 'LANDING.GA.flatten_ga_params(variant)'
```

### Category

category:import

### Expected Behavior

I expect this resource to be imported into the statefile. 

### Actual Behavior

Import is prepared but Error: object does not exist is returned

### Steps to Reproduce

Copy the configuration and run the import provided. 

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment] 2024-09-20 08:02
Hi @mike-soukup-vividseats 👋 

I can't reproduce this issue. Could you share logs with `TF_LOG=DEBUG`? Also, can you confirm in Snowsight that `DESCRIBE FUNCTION "LANDING"."GA"."flatten_ga_params"(VARCHAR)` returns the function you want to import?

**Comment by mike-soukup-vividseats** [comment] 2024-09-24 01:34
Hi @sfc-gh-jmichalak I can confirm that the function does exist in Snowflake. I validated the id from an old statefile to be this:
"\"LANDING\".\"GA\".\"flatten_ga_params\"(VARIANT)"

But even this throws the same error when I try to import it. Due to some sensitive info, I do not wish to share the debug logs. 

Can you give more context where this error message would come from? Can you validate the terraform import syntax is correct?
![image](https://github.com/user-attachments/assets/ef1ee277-7182-4eaf-b304-32a55bcb5f62)
![image](https://github.com/user-attachments/assets/1a88f5b1-3603-495d-91ef-8918e713b3c3)

**Comment by sfc-gh-jmichalak** [comment] 2024-09-24 10:04
I think that the name in Snowflake is upper case, but you try importing with lower case (`flatten_ga_params`). Please try importing with upper case. In Terraform case is sensitive.

**Comment by mike-soukup-vividseats** [comment] 2024-09-24 18:26
Well, I was skeptical, but that worked!

terraform import 'snowflake_function.flatten_ga_params' "\"LANDING\".\"GA\".\"FLATTEN_GA_PARAMS\"(VARIANT)"

Capitalizing the function name led to a successful import!

**Comment by sfc-gh-jmichalak** [comment] 2024-09-25 07:50
Cool, can we close this issue, then?

**Comment by sfc-gh-jmichalak** [comment] 2024-10-15 13:42
Closing the issue due to inactivity.

**Closed by sfc-gh-jmichalak** 2024-10-15 13:42 UTC
Labels: general-usage
