### ISSUE TITLE
data.snowflake_current_account breaks when QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#770] opened 2021-11-26 22:03 UTC
**Provider Version**

```
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.24
```

**Terraform Version**

```
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.24
```

**Describe the bug**

data.snowflake_current_account breaks (returns null) when `QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE`

**Expected behavior**

It should return the same attributes regardless of how QUOTED_IDENTIFIERS_IGNORE_CASE is set.

**Code samples and commands**

```
data "snowflake_current_account" "current" {}

# Use any other random resource which consumes this data source:
resource "aws_ssm_parameter" "snowflake_account" {
  name        = "/staging/snowflake_account"
  type        = "String"
  value       = "${data.snowflake_current_account.current.account}.us-east-1"
}
```

Use this data source when `QUOTED_IDENTIFIERS_IGNORE_CASE` is disabled, it works great.

Then do `ALTER ACCOUNT SET QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE`, either out-of-band from Terraform or using the `snowsql` provider. Then try to use the data source again and it will return null and break your plans/applies.

**Comment by jrobison-sb** [comment] 2021-11-27 20:07
From the debug logs I can see that this data source does `SELECT CURRENT_ACCOUNT() AS "account", CURRENT_REGION() AS "region";`, and when `QUOTED_IDENTIFIERS_IGNORE_CASE` is false the query returns account and region columns in lowercase. But when `QUOTED_IDENTIFIERS_IGNORE_CASE` is true, the query returns ACCOUNT and REGION columns in uppercase. Presumably the data source isn't set up to expect those to be in uppercase.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:52
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:52 UTC
Labels: bug
