### ISSUE TITLE
Unable to connect snowflake with user/password authentication

### ISSUE THREAD

**Issue by anikarunakaran** [Snowflake-Labs/terraform-provider-snowflake#938] opened 2022-03-18 12:45 UTC
### Discussed in https://github.com/chanzuckerberg/terraform-provider-snowflake/discussions/937

<div type='discussions-op-text'>

<sup>Originally posted by **anikarunakaran** March 18, 2022</sup>
Does anyone know why i am getting below given error while using user/password authentication for snowflake?.

terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.28.7"
    }
  }
}

provider "snowflake" {

  # Configuration options
  username = "admin"
  account  = "xxxxxx"
  region   = "east-us-2.azure"
  password = "xxxxxxxx"
}

resource "snowflake_database" "demo_db" {
  name = "demo_db"
}

=====================================

 Error: Conflicting configuration arguments
│
│   with provider["registry.terraform.io/chanzuckerberg/snowflake"],
│   on main.tf line 10, in provider "snowflake":
│   10: provider "snowflake" {
│
│ "private_key_path": conflicts with password</div>

**Comment by danu165** [comment] 2022-03-18 19:09
Check if you have `SNOWFLAKE_PRIVATE_KEY_PATH` in your env variables. That variable is injected into private_key_path

**Comment by sfc-gh-jalin** [comment] 2022-06-07 23:03
Are you still having issues connecting to snowflake?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:48
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:48 UTC
Labels: general-usage
