### ISSUE TITLE
Terraform crash creating external function

### ISSUE THREAD

**Issue by cjhix** [Snowflake-Labs/terraform-provider-snowflake#521] opened 2021-04-21 17:59 UTC
**Provider Version**
```
0.24.0 for linux_amd64 and windows_amd64
```
**Terraform Version**
```
0.12.21 on linux. 0.12.20 and 0.15.0 on windows.
```
**Describe the bug**
```
Terraform crashes when creating an external function. The crash happens after the function is created as **describe function func_name** returns the expected result. The state file is not updated.
```
**Expected behavior**
```
Terraform does not crash. The external function is created and the state file is updated.
```
**Code samples and commands**
```
terraform apply -auto-approve
```
```
provider "snowflake" {
  username = "*****"
  password = "*****"
  account = "*****"
  role = "ACCOUNTADMIN"
  region = "us-east-1"
}

terraform {
  backend "local" {}
  required_providers {
    snowflake = {
      source = "chanzuckerberg/snowflake"
      version = "0.24.0"
    }
  }
}

resource "snowflake_external_function" "log_and_notify" {
  name = "log_and_notify"
  database = "EXTERNAL_FUNCTIONS"
  schema   = "LAMBDA"
  arg {
    name = "v"
    type = "variant"
  }
  return_type = "variant"
  return_behavior = "IMMUTABLE"
  api_integration = "aws_integration"
  url_of_proxy_and_resource = "https://**********.execute-api.us-east-1.amazonaws.com/snowflake-api-stage/snowflake-api"
}
```

**Additional context**
Linux crash log

[crash.log](https://github.com/chanzuckerberg/terraform-provider-snowflake/files/6352969/crash.log)

**Comment by opp-svega** [comment] 2021-05-10 18:43
I am having the same issues. We changed the return_type to `varchar` and everything was okay.

**Comment by sfc-gh-pkommini** [comment] 2021-10-13 00:04
Had this error as well. Is `VARIANT` not a supported return type?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:58
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:58 UTC
Labels: bug
