### ISSUE TITLE
Conflict for streams with same name in separate schemas

### ISSUE THREAD

**Issue by Alpahalaserjet** [Snowflake-Labs/terraform-provider-snowflake#688] opened 2021-09-22 15:09 UTC
As issue #636, i have the same conflict between the streams with same name in separate schemas.
	
If I have a stream foo.bar.stream and another stream foo.baz.stream, the provider is not able to distinguish between them. This causes all sort of issues such as modifying the wrong task, reassigning grants, etc.
	
	Expected full support for identically named stream in separate schemas in a database.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:54
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:54 UTC
Labels: bug
