### ISSUE TITLE
[Feature]: S3 Compatible Stages

### ISSUE THREAD

**Issue by JamieSinn** [Snowflake-Labs/terraform-provider-snowflake#3208] opened 2024-11-19 22:32 UTC
### Company Name

DevCycle

### Use Cases or Problem Statement

We currently are utilizing both S3, and Cloudflare R2 for storage - but we'd like to make use of the snowflake capability to create stages for our data alongside our existing S3 Terraform code.

Snowflake Docs: https://docs.snowflake.com/user-guide/data-load-s3-compatible-storage#creating-an-external-stage-for-s3-compatible-storage

This likely just requires enabling the `ENDPOINT` property to be passed through on the `snowflake_stage` resource.

### Category

category:resource

### Object type(s)

resource:stage

### Proposal

Expose the `ENDPOINT` parameter for creating stages to enable external/non-S3 stages to be created.

### How much impact is this issue causing?

Low

### Additional Information

I'll probably take a swing later on this year to implement this myself - but I currently don't have time on my plate.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment] 2024-11-20 10:16
Hey @JamieSinn. Thanks for reaching out to us.

It seems like a duplicate of https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/3123.

**Comment by JamieSinn** [comment] 2024-11-20 13:52
Yep! I missed that! Thanks!

**Closed** 2024-11-20 13:52 UTC
Labels: feature-request
