### ISSUE TITLE
Database replication does not create database from different account

### ISSUE THREAD

**Issue by Pavel-Millstein** [Snowflake-Labs/terraform-provider-snowflake#952] opened 2022-03-29 11:26 UTC
**Provider Version**

0.29.0

**Terraform Version**

0.13.0

**Describe the bug**

When trying to create database as replica of database from different account in the organization, 
returning error(actual names were changed) :
` error creating a secondary database mydb1 from database myorg.account1.mydb1 : 003901 (55000): Database '"myorg.account1.mydb1"' does not exist or is not authorized.`

**Expected behavior**

Create database as replica of database from different account.

When looking up actual SQL query we get:
`CREATE DATABASE "mydb1" AS REPLICA OF "myorg.account1.mydb1"` - error

When cleaning up the query of apostrophes:
`CREATE DATABASE "mydb1" AS REPLICA OF myorg.account1.mydb1 `- pass

**Additional context**

I'm guessing that the problem is [here](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/f1d0af96bbe8e57558bd3a57808298d8d49fe349/pkg/snowflake/database.go#L76)

`REPLICA OF "%v"` should be in fact `REPLICA OF %v`

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:48
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:48 UTC
Labels: bug
