### ISSUE TITLE
Token Caching does not work

### ISSUE THREAD

**Issue by sfc-gh-cconner** [Snowflake-Labs/terraform-provider-snowflake#2047] opened 2023-09-05 14:08 UTC
**Provider Version**

0.70.1

**Terraform Version**

1.5.4

**Describe the bug**

Even though the terraform provider has a version of the Go Driver that supports Token caching, it does not work in the terraform provider.

The go driver does this automatically out of the box with external browser authentication.  I have tested with go 1.6.19 and it just works.  I tested with the current Snowflake terraform provider that uses Go driver 1.6.19 and it does not try to use the Keychain.  So, I built the terraform provider with go driver 1.6.19 with some extra logging to try and see what's going on and my custom built Snowflake provider does use the Keychain.

**Expected behavior**

The expectation is that the Terraform provider automatically caches the credential token.

**Comment by sadahry** [comment] 2024-03-14 09:45
cc @harukitake

We are facing with this issue, and confirmed:

* Apple Silion (M1 & M2) failed due to the keyring issue
```
Failed to write to keychain. Err: No directory provided for file keyring
```
https://github.com/snowflakedb/gosnowflake/blob/v1.7.1/secure_storage_manager.go#L91-L93

* Windows Subsystem for Linux has been successful 

on terraform 1.7.4 and Provider v0.87.2.

 Does this mean anything to you?

**Comment by sadahry** [comment] 2024-03-14 09:49
@sfc-gh-cconner cc @harukitake

We are facing with this issue, and confirmed:

1. Apple Silion (M1 & M2) failed due to the keyring issue
    ```
    Failed to write to keychain. Err: No directory provided for file keyring
    ```
    ref. https://github.com/snowflakedb/gosnowflake/blob/v1.7.1/secure_storage_manager.go#L91-L93

2. Windows Subsystem for Linux has been successful 

on terraform 1.7.4 and provider v0.87.2.

We are having trouble with not being able to have SSO with token caching.
Does this mean anything to you?

**Comment by sfc-gh-cconner** [comment] 2024-03-14 12:41
@sadahry , we have identified the root cause to be related to the build process.  We are working on a fix, but we do not have a timeframe just yet.

**Comment by sadahry** [comment] 2024-03-19 07:39
@sfc-gh-cconner We've confirmed the issue resolved by `0.87.3-pre` version 🎉 

probably due to this fix https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2613

**Comment by sfc-gh-cconner** [comment] 2024-03-19 14:17
That is great news!!

**Comment by sfc-gh-asawicki** [comment] 2024-03-21 12:03
Hey @sadahry. For which systems have you verified the prerelease version? I want to release this patch as part of the 0.88.0 version officially, but first, I want to confirm that it works for various systems.

**Comment by sadahry** [comment] 2024-03-22 03:34
I've confirmed it on Apple Silion (M1).

**Comment by harukitake** [comment] 2024-04-10 10:28
It has resolved in `v0.88.0`.
https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.88.0

**Comment by DustinMoriarty** [comment] 2024-04-12 02:45
I have tested this on MacOS 14.4.1 with 0.88.0 and token caching worked. I received the OS prompt for my system password. I selected the "always allow" option. Then the browser opened to complete auth with Okta. The Authentication completed with Okta in the browser. After that all future authentication for additional resources in the same process or future processes did not open the browser.

**Comment by sfc-gh-swinkler** [comment] 2024-04-12 22:10
@DustinMoriarty glad my fix helped you

**Closed** 2024-07-03 15:41 UTC
Labels: bug, category:provider_config
