### ISSUE TITLE
version  0.26 missing  in terraform snowflake provider repository

### ISSUE THREAD

**Issue by arunpgmi** [Snowflake-Labs/terraform-provider-snowflake#946] opened 2022-03-22 15:26 UTC
**Provider Version**
terraform-provider-snowflake_v0.26 
The provider version you are using.

**Terraform Version**

The version of Terraform you were using when the bug was encountered.
Terraform v1.0.3

**Describe the bug**

We need this version as it has fixed bugs which we are currently facing.
Looks like 0.26 version was removed recently.

**Expected behavior**

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

**Comment by arunpgmi** [comment] 2022-03-29 06:03
Can  you please help us with an update ?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:48
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:48 UTC
Labels: bug
