### ISSUE TITLE
`snowflake_role_grants` resource name should be singular

### ISSUE THREAD

**Issue by aidan-melen** [Snowflake-Labs/terraform-provider-snowflake#282] opened 2020-10-25 17:49 UTC
**Provider Version**

v0.17.1

**Terraform Version**

v0.13.0

**Describe the bug**

I was looking at the documentation for [snowflake_role_grants](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/role_grants) and I noticed the naming was inconsistent with other grant resources such as:

- [snowflake_database_grant](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/database_grant)
- [snowflake_schema_grant](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/schema_grant)
- [snowflake_table_grant](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/table_grant)

**Expected behavior**

I think `snowflake_role_grants` should be renamed to `snowflake_role_grant` (singular). I understand this would be a breaking change and if backwards compatibility is desired, then we would need to keep both around.

**Comment by ajwootto** [comment] 2021-05-04 14:13
I would actually argue that this grant resource is the only one with the correct name, because all the other resources also create multiple grants (one for each role in the roles array). This actually led me to accidentally wipe out some pre-existing grants on my database because the naming of `snowflake_database_grant` implied it was only going to create a grant, not overwrite the full set of database grants.

**Comment by aidan-melen** [comment] 2021-05-04 19:21
@ajwootto The `database_name` argument from the `snowflake_database_grant` resource is analogous to the `role_name` argument in the `snowflake_role_grants` resource. This grant resource is managing a singular "object" in snowflake. For that reason, it should be renamed to avoid confusion.

**Comment by ajwootto** [comment] 2021-05-04 21:05
Those fields are analogous, but in both cases there's a "roles" array which creates one grant for each entry in the array. The resource doesn't actually correspond to a single "object" in snowflake if you consider a grant an "object". Instead it corresponds to "every grant" for the provided database / role. 

This is the confusion I alluded to above, where I assumed that `snowflake_database_grant` would create one grant, not overwrite the full set of grants for the given database.

I assume the same is true for the `snowflake_role_grants`, though I haven't tested it. If you make more than one `snowflake_role_grants` resource to try and grant the same role to multiple roles / users, the two resources will conflict.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:02
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:02 UTC
Labels: feature-request
