### ISSUE TITLE
[Bug]: Not possible to rename stage - Running into a deadlock

### ISSUE THREAD

**Issue by JESCHO99** [Snowflake-Labs/terraform-provider-snowflake#2972] opened 2024-08-01 11:59 UTC
### Terraform CLI Version

1.5.7

### Terraform Provider Version

0.92.0

### Terraform Configuration

```terraform
provider "snowflake" {
  role  = "SYSADMIN"
}

terraform {
  required_version = "~> 1.5.0"
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.92.0"
    }
  }
}

resource "snowflake_database" "this" {
  name = "LOCAL_TEST_DB"
}

resource "snowflake_schema" "this" {
  name     = "TESTING"
  database = snowflake_database.this.name
}

resource "snowflake_table" "table_v1" {
  database                    = snowflake_database.this.name
  schema                      = snowflake_schema.this.name
  name                        = "TEST_V1"
  change_tracking             = false

  column {
    name     = "ID"
    type     = "INTEGER"
  }

  column {
    name = "NAME"
    type = "VARCHAR(255)"
  }
}

resource "snowflake_table" "table_v2" {
  database                    = snowflake_database.this.name
  schema                      = snowflake_schema.this.name
  name                        = "TEST_V2"
  change_tracking             = false

  column {
    name     = "ID"
    type     = "INTEGER"
  }

  column {
    name = "NAME"
    type = "VARCHAR(255)"
  }
}

resource "snowflake_stage" "stage_v1" {
  name        = "TEST_V1"
  database    = snowflake_database.this.name
  schema      = snowflake_schema.this.name
}

resource "snowflake_stage" "stage_v2" {
  name        = "TEST_V2"
  database    = snowflake_database.this.name
  schema      = snowflake_schema.this.name
}
```

### Category

category:resource

### Object type(s)

resource:stage

### Expected Behavior

When the provided terraform code is applied in Snowflake the Database, Schema, two tables and two named stages can be deployed successful. Everything is working as expected so far. Due to manual changes on Snowflake someone executed a rename command on one of the named stages: `alter stage LOCAL_TEST_DB.TESTING.TEST_V1 rename to POST_TEST_V1;`

When executing a terraform plan now in Terraform the expected behaviour would be that terraform recognizes that the defined stage no longer exists and will show a create stage in the produced plan. When this plan is executed terraform will create a new stage having the "old" name. In Snowflake there will be the renamed "old" stage and the newly created stage with the "old" name.

### Actual Behavior

After a rename of an existing stage the provider runs into an error which does not longer allow for plan, apply or destroy commands. 
![image](https://github.com/user-attachments/assets/5369d636-6e29-47d8-9f22-d9695642e27a)
![image](https://github.com/user-attachments/assets/f02b8016-a77b-4a01-b2e5-cf5b9739fca5)
It seems that it is missing the behaviour that the provider can differ between a describe and a show objects like function. For example for tables the described process is working completely without errors.

### Steps to Reproduce

1. Terraform Apply with the provided code
2. Manually Rename one of the stages inside of Snowflake with the rename command
3. Try to execute terraform plan

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment] 2024-08-01 13:16
Hey @JESCHO99. Thanks for reaching out to us.

We plan to rework stages soon (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/ESSENTIAL_GA_OBJECTS.MD). However, this seems to be an easy fix, i.e. we have to handle this error conditionally like e.g. in the schemas (we are doing it for every resource we redesign).

I should be able to squeeze it in in next week's release (if I can prove that this is really the cause as expected).

**Comment by sfc-gh-asawicki** [comment] 2024-08-28 10:07
Hey @JESCHO99. I have prepared a fix in https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/3020. It will be released as part of v0.95.0 today or tomorrow (we have to wrap a few other pull requests before making the release).

**Comment by JESCHO99** [comment] 2024-08-28 14:07
Hey @sfc-gh-asawicki, huge thanks for the quick fix!

**Comment by sfc-gh-asawicki** [comment] 2024-08-30 11:20
Hey @JESCHO99, we had to postpone the v0.95.0 release to Monday, sorry for the inconvenience.

**Comment by sfc-gh-asawicki** [comment] 2024-10-15 13:07
Hey @JESCHO99. Did you check the fix? If so, can we close the issue?

**Comment by sfc-gh-asawicki** [comment] 2024-11-12 14:48
Closing due to inactivity. Please create a new issue if the problem persists in the newest version.

**Closed by sfc-gh-asawicki** 2024-11-12 14:48 UTC
Labels: bug
