### ISSUE TITLE
Create Share example is not matching with description 

### ISSUE THREAD

**Issue by blian7432** [Snowflake-Labs/terraform-provider-snowflake#514] opened 2021-04-07 00:47 UTC
**Provider Version**
0.24

**Describe the bug**
The share example shows:
resource snowflake_share share {
  database_name = "db"
  schema_name   = "schema"
  stage_name    = "stage"

  privilege = "USAGE"
  roles     = ["role1", "role2"]
  shares    = ["share1", "share2"]

  with_grant_option = false
}
But the actual schema requirement says:

Required : Name

Optional: Accounts, Comment, ID

The schema description is not matching with example.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:59
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:59 UTC
Labels: bug
