### ISSUE TITLE
snowflake_task does not re-set the `QUERY_TAG` value of the session_parameters.

### ISSUE THREAD

**Issue by mganopolsky-rbi** [Snowflake-Labs/terraform-provider-snowflake#825] opened 2022-01-19 21:09 UTC
**Provider Version**

0.25.34

**Terraform Version**

v1.0.3

**Describe the bug**

In using the resource `snowflake_task` setting the `session_parameters` of `QUERY_TAG` does not apply if the value already exists. (Note, the value will be set if it was previously null; but will not change if `QUERY_TAG` already exists, unless it's being removed.) 

**Expected behavior**

The `QUERY_TAG` of an existing `session_parameters` map in a `snowflake_task` is changed from an existing value to the updated value provided in the TF script.

**Code samples and commands**

```
resource "snowflake_task" "copy_from_pitr_s3" {
  for_each = {
    BRAND = {
      destination           = snowflake_table.incoming["BRAND"],
      enabled               = false,
      dynamodb_source_table = local.dynamodb_source_table,
      stage                 = snowflake_stage.s3_pitr_stage,
    },
    LOYALTY = {
      destination           = snowflake_table.incoming["LOYALTY"],
      enabled               = true,
      dynamodb_source_table = "LOYALTY",
      stage                 = snowflake_stage.s3_pitr_loyalty_stage,
    },
  }

  database  = snowflake_schema.ingestion.database
  schema    = snowflake_schema.ingestion.name
  warehouse = "INGESTION"
  name      = "COPY_FROM_PITR_S3_${each.key}"

  schedule = local.ingestion_schedule

  sql_statement = <<-SQL
    // some SQL statement here
  SQL

  enabled = each.value.enabled

  # This is needed in order to eliminate spurious diffs in Terraform.
  session_parameters = {
    "ODBC_QUERY_RESULT_FORMAT" = "ARROW",
    "QUERY_TAG"                = "TASK:COPY_FROM_PITR_S3_${each.key}",
  }
}
```

**Additional context**

The following workflows work as expected:

existing `QUERY_TAG` value is 'x' -> removing `QUERY_TAG` parameter -> the `QUERY_TAG` of the appropriate task is null.
existing `QUERY_TAG` value is null -> setting `QUERY_TAG` parameter to 'x' -> the `QUERY_TAG` of the appropriate task is 'x'.

The following workflow **does not** work as expected:

existing `QUERY_TAG` value is 'x' -> changing `QUERY_TAG` parameter to 'y' -> the `QUERY_TAG` of the appropriate task does not change (stays 'x').

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:50
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:50 UTC
Labels: bug
