### ISSUE TITLE
Unable to set a new value for statement_timeout_in_seconds parameter for a virtual warehouse

### ISSUE THREAD

**Issue by abouhoudayfa** [Snowflake-Labs/terraform-provider-snowflake#411] opened 2021-01-12 12:21 UTC
Provider Version
```

terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "~> 0.20.0"
    }
  }
}

```
Terraform Version

```
terraform --version
Terraform v0.14.4
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.20.0
```

**Describe the bug**

Unable to set a new value for statement_timeout_in_seconds parameter for a virtual warehouse.

**Code samples and commands**
```

locals {
  warehouses = {
    "APPLICATIONS_NAME" = {
      comment = "Dedicated VW for specified applications"
      auto_suspend = 60
      min_cluster = 1
      max_cluster = 2
      scaling = "ECONOMY"
      size = "SMALL"
      statement_timeout_in_seconds = 1800
    }
  }
}


resource "snowflake_warehouse" "virtual_warehouses" {
  provider            = snowflake.SYSADMIN
  for_each            = local.warehouses
  comment             = each.value.comment
  name                = each.key
  auto_resume         = true
  auto_suspend        = each.value.auto_suspend
  initially_suspended = true
  max_cluster_count   = each.value.max_cluster
  min_cluster_count   = each.value.min_cluster
  scaling_policy      = each.value.scaling
  warehouse_size      = each.value.size
  statement_timeout_in_seconds = each.value.statement_timeout_in_seconds
}
```

With the code above all parameters are setted with the good value except statement_timeout_in_seconds, it still with the default value **172800** and level **Account** not **Warehouse**.
Also, if we alter the parameter manually with a SQL command it works and change the level to Warehouse and the value to 1800.
`ALTER WAREHOUSE my_wh SET STATEMENT_TIMEOUT_IN_SECONDS = 1800;`

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:01
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:01 UTC
Labels: bug
