### ISSUE TITLE
Error: The terraform-provider-snowflake_v0.25.19 plugin crashed!

### ISSUE THREAD

**Issue by lilievanellesegnoufotsing** [Snowflake-Labs/terraform-provider-snowflake#1249] opened 2022-10-03 20:22 UTC
**Provider Version**

The provider version you are using.

**Terraform Version**

terraform-0.15.4-1.x86_64

**Describe the bug**

The terraform-provider-snowflake_v0.25.19 plugin crashed when create stored procedure inside configuration file

**Expected behavior**

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

** Error message**

2022-10-03T19:42:22.3069870Z Error: Plugin did not respond
2022-10-03T19:42:22.3070199Z 
2022-10-03T19:42:22.3070777Z   with module.create_database_dv01.snowflake_procedure.grant_role_lec,
2022-10-03T19:42:22.3071571Z   on ../../modules/common/common.tf line 976, in resource "snowflake_procedure" "grant_role_lec":
2022-10-03T19:42:22.3072387Z  976: resource snowflake_procedure grant_role_lec {
2022-10-03T19:42:22.3072743Z 
2022-10-03T19:42:22.3073261Z The plugin encountered an error, and failed to respond to the
2022-10-03T19:42:22.3074113Z plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
2022-10-03T19:42:22.3074701Z more details.
2022-10-03T19:42:22.3074946Z 
2022-10-03T19:42:22.3075345Z Error: Plugin did not respond
2022-10-03T19:42:22.3075657Z 
2022-10-03T19:42:22.3076187Z   with module.create_database_dv01.snowflake_procedure.revoke_role_lec,
2022-10-03T19:42:22.3076982Z   on ../../modules/common/common.tf line 1011, in resource "snowflake_procedure" "revoke_role_lec":
2022-10-03T19:42:22.3077748Z 1011: resource snowflake_procedure revoke_role_lec {
2022-10-03T19:42:22.3078078Z 
2022-10-03T19:42:22.3078595Z The plugin encountered an error, and failed to respond to the
2022-10-03T19:42:22.3079256Z plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
2022-10-03T19:42:22.3079852Z more details.
2022-10-03T19:42:22.3080106Z 
2022-10-03T19:42:22.3081360Z Stack trace from the terraform-provider-snowflake_v0.25.19 plugin:
2022-10-03T19:42:22.3852222Z 
2022-10-03T19:42:22.3855470Z panic: runtime error: index out of range [1] with length 0
2022-10-03T19:42:22.3856192Z 
2022-10-03T19:42:22.3858528Z goroutine 27 [running]:
2022-10-03T19:42:22.3962715Z github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadProcedure(0xc00038d480, 0x12cd4e0, 0xc000388a90, 0x0, 0x0)
2022-10-03T19:42:22.4677876Z 	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/procedure.go:258 +0x1408
2022-10-03T19:42:22.4699963Z github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.CreateProcedure(0xc00038d480, 0x12cd4e0, 0xc000388a90, 0x3, 0xffffffffffffffff)
2022-10-03T19:42:22.4701727Z 	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/procedure.go:184 +0x925
2022-10-03T19:42:22.4703675Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00017f500, 0x14c8cd8, 0xc00035c640, 0xc00038d480, 0x12cd4e0, 0xc000388a90, 0x0, 0x0, 0x0)
2022-10-03T19:42:22.4705092Z 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:318 +0x1ee
2022-10-03T19:42:22.4706642Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00017f500, 0x14c8cd8, 0xc00035c640, 0xc0002f6770, 0xc0008344c0, 0x12cd4e0, 0xc000388a90, 0x0, 0x0, 0x0, ...)
2022-10-03T19:42:22.4711386Z 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:456 +0x67b
2022-10-03T19:42:22.4749186Z github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00027a078, 0x14c8cd8, 0xc00035c640, 0xc00008ee60, 0xc00035c640, 0x128bdc0, 0xc000386600)
2022-10-03T19:42:22.4753100Z 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8ef
2022-10-03T19:42:22.4800014Z github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00097af80, 0x14c8d80, 0xc00035c640, 0xc0002f6540, 0xc00097af80, 0xc000386600, 0xc000676ba0)
2022-10-03T19:42:22.4801409Z 	github.com/hashicorp/terraform-plugin-go@v0.3.1/tfprotov5/server/server.go:332 +0xb5
2022-10-03T19:42:22.4802396Z github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x128bdc0, 0xc00097af80, 0x14c8d80, 0xc000386600, 0xc0002943c0, 0x0, 0x14c8d80, 0xc000386600, 0xc0003cb800, 0x5db)
2022-10-03T19:42:22.4803598Z 	github.com/hashicorp/terraform-plugin-go@v0.3.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
2022-10-03T19:42:22.4804346Z google.golang.org/grpc.(*Server).processUnaryRPC(0xc00055a540, 0x14d3358, 0xc000988900, 0xc0002c8480, 0xc0003b0ea0, 0x1b4c060, 0x0, 0x0, 0x0)
2022-10-03T19:42:22.4804836Z 	google.golang.org/grpc@v1.39.0/server.go:1292 +0x52b
2022-10-03T19:42:22.4805287Z google.golang.org/grpc.(*Server).handleStream(0xc00055a540, 0x14d3358, 0xc000988900, 0xc0002c8480, 0x0)
2022-10-03T19:42:22.4805732Z 	google.golang.org/grpc@v1.39.0/server.go:1617 +0xd0c
2022-10-03T19:42:22.4806203Z google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002de1b0, 0xc00055a540, 0x14d3358, 0xc000988900, 0xc0002c8480)
2022-10-03T19:42:22.4806658Z 	google.golang.org/grpc@v1.39.0/server.go:940 +0xab
2022-10-03T19:42:22.4807054Z created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-10-03T19:42:22.4807436Z 	google.golang.org/grpc@v1.39.0/server.go:938 +0x1fd
2022-10-03T19:42:22.4807672Z 
2022-10-03T19:42:22.4808152Z Error: The terraform-provider-snowflake_v0.25.19 plugin crashed!
2022-10-03T19:42:22.4808394Z 
2022-10-03T19:42:22.4808756Z This is always indicative of a bug within the plugin. It would be immensely
2022-10-03T19:42:22.4809345Z helpful if you could report the crash with the plugin's maintainers so that it
2022-10-03T19:42:22.4809782Z can be fixed. The output above should help diagnose the issue.
2022-10-03T19:42:22.4810007Z 
2022-10-03T19:42:22.5479951Z ##[error]Bash exited with code '1'.

**Comment by tangi-vass** [comment] 2022-10-05 12:21
Try:
```
terraform {

  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "~> 0.25.36"
    }
  }

  required_version = "~> 1.0.3"
}
```

Then `terraform init --upgrade`

**Comment by systematics78** [comment] 2022-10-09 01:46
snowflake_procedure

return_behavior = "VOLATILE"

https://docs.snowflake.com/en/sql-reference/sql/create-procedure.html

VOLATILE | IMMUTABLE
Deprecated

Attention

These keywords are deprecated for stored procedures. These keywords are not intended to apply to stored procedures. In a future release, these keywords will be removed from the documentation.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:45
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:45 UTC
Labels: bug
