### ISSUE TITLE
Unstability of the plan on the resource snowflake_integration_grant

### ISSUE THREAD

**Issue by hibougeek** [Snowflake-Labs/terraform-provider-snowflake#663] opened 2021-08-26 09:30 UTC
**Provider Version**
chanzuckerberg/snowflake versions matching "0.15.0"...

**Terraform Version**
Terraform v0.14.8

**Describe the bug**
When reexecuting a plan,  terraform tries to destroy / create a grant usage on storage integration although it has been already created.

**Expected behavior**

**Code samples and commands**
input : 
```
  storage_integration_grants = [
    {
      storage_integration_name = "snwst_${local.environment}_${local.application}_dwh"
      privilege                = "USAGE"
      roles                    = ["role_${local.environment}_dwh_apps"]
    }
  ]
```
Code : 
```
resource "snowflake_integration_grant" "this" {
  depends_on = [snowflake_role.role]
  for_each = { for item in var.storage_integration_grants : "${item.storage_integration_name}.${item.privilege}" => { integration_name : item.storage_integration_name
    privilege : item.privilege
    roles : [for role in item.roles : upper(role)]
  } }

  integration_name  = upper(each.value.integration_name)
  privilege         = each.value.privilege
  roles             = each.value.roles
  with_grant_option = false
}
```
Plan : 
Resource actions are indicated with the following symbols:
```
-/+ destroy and then create replacement
Terraform will perform the following actions:
  # module.roles.snowflake_integration_grant.this["snwst_dev_xxxxx_dwh.USAGE"] must be replaced
-/+ resource "snowflake_integration_grant" "this" {
      ~ id                = "SNWST_DEV_XXXXX_DWH|||USAGE|false" -> (known after apply)
      ~ roles             = [ # forces replacement
          + "ROLE_DEV_DWH_APPS",
        ]
        # (3 unchanged attributes hidden)
    }
```
Current tfstate 
```
{
      "module": "module.roles",
      "mode": "managed",
      "type": "snowflake_integration_grant",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/chanzuckerberg/snowflake\"]",
      "instances": [
        {
          "index_key": "snwst_dev_xxxxx_dwh.USAGE",
          "schema_version": 0,
          "attributes": {
            "id": "SNWST_DEV_XXXXX_DWH|||USAGE|false",
            "integration_name": "SNWST_DEV_XXXXX_DWH",
            "privilege": "USAGE",
            "roles": [
              "ROLE_DEV_DWH_APPS"
            ],
            "with_grant_option": false
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "module.roles.snowflake_role.role"
          ]
        }
      ]
    },
```
**Additional context**

n/a

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:55
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:55 UTC
Labels: bug
