### ISSUE TITLE
Snowflake Procedure resource creation throws plugin error when "return_type = boolean"

### ISSUE THREAD

**Issue by stkbailey** [Snowflake-Labs/terraform-provider-snowflake#665] opened 2021-08-28 11:08 UTC
**Provider Version**

v0.25.16

**Terraform Version**

v1.0.5

**Describe the bug**

When creating a `snowflake_procedure` resource, specifying a return_type of `BOOLEAN` causes the provider to crash.

**Expected behavior**

Procedure resource is created or fails gracefully.

**Code samples and commands**

I was able to reproduce the bug from my project by taking the example code from the resource documentation and setting `return_type = "BOOLEAN"`. The procedure creation completes successfully when `return_type = "VARCHAR"`.

```
resource "snowflake_database" "db" {
  name                = "MYDB"
}

resource "snowflake_schema" "schema" {
  database            = snowflake_database.db.name
  name                = "MYSCHEMA"
}

resource "snowflake_procedure" "proc" {
  name     = "SAMPLEPROC"
  database = snowflake_database.db.name
  schema   = snowflake_schema.schema.name

  return_type         = "BOOLEAN"

  statement           = <<EOT
var X=1
return true
EOT
}
```

The output I receive is this:

```
snowflake_procedure.proc: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with snowflake_procedure.proc,
│   on main.tf line 99, in resource "snowflake_procedure" "proc":
│   99: resource "snowflake_procedure" "proc" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-snowflake_v0.25.16 plugin:

panic: runtime error: index out of range [1] with length 0

goroutine 85 [running]:
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadProcedure(0xc0001fae00, 0x1ebb9c0, 0xc0003b28f0, 0x0, 0x0)
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/procedure.go:258 +0x1408
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.CreateProcedure(0xc0001fae00, 0x1ebb9c0, 0xc0003b28f0, 0x0, 0xffffffffffffffff)
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/procedure.go:184 +0x925
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002c49a0, 0x20b5ad8, 0xc00027cb00, 0xc0001fae00, 0x1ebb9c0, 0xc0003b28f0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002c49a0, 0x20b5ad8, 0xc00027cb00, 0xc0005e55e0, 0xc0005eaa80, 0x1ebb9c0, 0xc0003b28f0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003ca018, 0x20b5ad8, 0xc00027cb00, 0xc000836960, 0xc00027cb00, 0x1e7a380, 0xc0005d1700)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0005b27a0, 0x20b5b80, 0xc00027cb00, 0xc0005e5490, 0xc0005b27a0, 0xc0005d1770, 0xc000316ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.1/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1e7a380, 0xc0005b27a0, 0x20b5b80, 0xc0005d1770, 0xc00011b4a0, 0x0, 0x20b5b80, 0xc0005d1770, 0xc0005a23c0, 0x1d3)
        github.com/hashicorp/terraform-plugin-go@v0.3.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000616540, 0x20c0238, 0xc000103380, 0xc000562360, 0xc0005d0510, 0x2737920, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.39.0/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000616540, 0x20c0238, 0xc000103380, 0xc000562360, 0x0)
        google.golang.org/grpc@v1.39.0/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003941a0, 0xc000616540, 0x20c0238, 0xc000103380, 0xc000562360)
        google.golang.org/grpc@v1.39.0/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.39.0/server.go:938 +0x1fd

Error: The terraform-provider-snowflake_v0.25.16 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Additional context**

**Comment by alldoami** [comment] 2021-09-07 23:48
@stkbailey where do you see an example for `return_type = "BOOLEAN"`? Even in docs here: https://docs.snowflake.com/en/sql-reference/sql/create-procedure.html, it looks like they only use `VARCHAR`. Were you able to create a procedure with boolean in the UI?

**Comment by stkbailey** [comment] 2021-09-08 00:33
Hey @alldoami ! Yes, I think you can return any valid data type from the procedure. For example:

```
CREATE OR REPLACE PROCEDURE dev_db.public.foo()
RETURNS BOOLEAN
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
    return true;
$$;

call dev_db.public.foo();
```

Will return `TRUE`:
![image](https://user-images.githubusercontent.com/7850417/132426919-54246a3a-8a1d-48d7-8fc3-33d706b05963.png)

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:55
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:55 UTC
Labels: feature-request
