### ISSUE TITLE
snowflake_resource_monitor start_timestamp cannot be in the past

### ISSUE THREAD

**Issue by paul-butcher** [Snowflake-Labs/terraform-provider-snowflake#612] opened 2021-07-20 14:19 UTC
**Provider Version**

0.19.0

**Terraform Version**

0.12.29

**Describe the bug**

When creating a Resource Monitor, the value of start_timestamp (correctly) cannot be in the past.

However, once it has been created (with a future value), and time passes such that the timestamp is now in the past, Terraform determines that the monitor must be destroyed and recreated. This fails.

**Expected behavior**

I would expect that if I make no change to the Terraform code, and no change to the resource itself, then the resources created by applying the terraform will not need to be destroyed and recreated.

I would also expect either:
* If two values are conceptually the same but a different string representation, they should not trigger a replacement
OR
* To be able to use the same string representation to set a timestamp as terraform uses to determine whether it needs to update it.

**Code samples and commands**

With a resource monitor definition like this, run `terraform apply` at 09:55 on 2021-07-21

```
resource "snowflake_resource_monitor" "MY_MONITOR" {
  name         = "MY_MONITOR"
  credit_quota = 5

  start_timestamp = "2021-07-21 10:00"
  frequency       = "DAILY"

}
```

Immediately run `terraform plan`. You will see an entry like this:

```
  # snowflake_resource_monitor.MY_MONITOR must be replaced
-/+ resource "snowflake_resource_monitor" "MY_MONITOR" {
        credit_quota               = 5
        frequency                  = "DAILY"
      ~ id                         = "MY_MONITOR" -> (known after apply)
        name                       = "MY_MONITOR"
      ~ start_timestamp            = "2021-07-21T10:00:00Z" -> "2021-07-21 10:00" # forces replacement
     }
```
The requested time and the actual time are actually the same, conceptually, but because one separates the time from the date with a T and ends with the Z timezone specifier, and the other uses a space and has no timezone, Terraform thinks they are different.  Because this property cannot be edited, Terraform chooses to destroy and recreate the resource.

Now wait until 10:01 and run `terraform apply` again.  It will destroy the resource, then fail because it is trying to create a resource monitor with a timestamp in the past.

**Additional context**

As far as I can tell, only a format like this works for creating the resource.
2021-07-20 00:00

***The following time formats all fail when used to create the resource:***

****It can’t cope with T-separated date-times****
* 2021-07-20T00:00
* 2021-07-20T00:00Z
* 2021-07-20T00:00:00Z

****It can’t cope with Z****

* 2021-07-20 00:00Z

****It can’t cope with numeric timezone offsets****
* 2021-07-20 00:00 +0000

****It can’t cope with seconds****

* 2021-07-20 00:00:00

***Workaround***

I have an unsatisfactory workaround:

1. Set the date using the format that works for creating the resource (2021-07-21 10:00)
2. run `terraform apply`
3. Change the date to match what the server reports (2021-07-20T00:00:00Z)

As long as there is no other change that will invoke the destroy-and-create process for that object, `terraform apply` will complete successfully.

**Comment by jacquiwuc** [comment] 2021-09-16 03:36
met the same issue today, thanks paul for your workaround, already fixed!

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:56
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:56 UTC
Labels: bug
