### ISSUE TITLE
Support id parameter in resource snowflake_database_grant

### ISSUE THREAD

**Issue by Kamitenshi** [Snowflake-Labs/terraform-provider-snowflake#966] opened 2022-04-07 11:28 UTC
**Provider Version**

0.25.36

**Terraform Version**

1.1.7

**Describe the bug**

[In the documentation](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/database_grant), it is indicated that the resource `snowflake_database_grant` has an optional parameter id
However, this parameter is not declared in the [resource code](https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/database_grant.go)

Which result in the following error:
```
Error: Invalid or unknown key
```

**Expected behavior**

Being able to pass the id parameter to the resource `snowflake_database_grant`

**Code samples and commands**

```
resource "snowflake_database_grant" "my_grant" {
  id       = "MY_GRANT"

  database_name = var.my_database

  privilege = "USAGE"

  roles = [
    snowflake_role.my_role.name
  ]
}
```

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:47
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:47 UTC
Labels: bug
