### ISSUE TITLE
snowflake_schema is not idempotent

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#845] opened 2022-02-03 16:35 UTC
**Provider Version**

```
$ terraform version
Terraform v0.14.11
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.24
```
**Terraform Version**
```
$ terraform version
Terraform v0.14.11
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.24
```

**Describe the bug**

`snowflake_schema` is not idempotent.

**Expected behavior**

`snowflake_schema` is idempotent.

**Code samples and commands**

Create a `snowflake_schema` object managed by Terraform. 

Then delete or rename it out-of-band from Terraform. Eg. `ALTER SCHEMA "MY_DB"."MY_SCHEMA" RENAME TO "MY_DB"."MY_SCHEMA_BACKUP";`.

Then run a plan/apply. It will error out saying:
```
Error: 002003 (02000): SQL compilation error:
Schema 'MY_DB.MY_SCHEMA' does not exist or not authorized.
```

Terraform should instead understand that the schema no longer exists and should offer to recreate it.

**Comment by andrewcylaw** [comment] 2022-06-06 18:33
@MorganGellert were you able to find a workaround for the issue? I'm running into a similar problem but with pipe objects referencing a renamed schema

**Comment by andrewcylaw** [comment] 2022-06-08 16:23
I ended up working around this by:

1. Dropping all affected `STAGE`s and `PIPE`s from the Snowflake database
2. Removing resources from the Terraform state (eg `terraform state rm 'module.my_snowflake.snowflake_stage.my_stage`)
3. Rerunning my CICD pipeline to recreate and bring the resources back under Terraform's management.

However, this solution is not workable for everyone since it forces (extra) downtime due to having to delete and recreate resources. Destroying via Terraform also doesn't work because of this issue.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:49
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:49 UTC
Labels: bug
