### ISSUE TITLE
Issue with installing Snowflake plugin for darwin/arm64

### ISSUE THREAD

**Issue by smswamy** [Snowflake-Labs/terraform-provider-snowflake#1012] opened 2022-05-20 00:01 UTC
Hi,
I am always getting the below error 
chanzuckerberg/terraform-provider-snowflake crit platform darwin/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/new

Whenever I run the following curl command
curl https://raw.githubusercontent.com/chanzuckerberg/terraform-provider-snowflake/main/download.sh | bash -s -- -b $HOME/.terraform.d/plugins

I am using a Macbook Pro, not sure if that is causing any issues
MacBook Pro (16-inch, 2021)
Apple M1 Pro

**Comment by sfc-gh-swinkler** [comment] 2022-05-26 18:50
What version are you trying to install? All newer versions support darwin/arm64. From the provider registry protocol you can see that it is second on the list: https://registry.terraform.io/v1/providers/snowflake-labs/snowflake/versions

```
{
"version": "0.34.0",
"protocols": [
"5.0"
],
"platforms": [
{
"os": "darwin",
"arch": "amd64"
},
{
"os": "darwin",
"arch": "arm64"
},
{
"os": "freebsd",
"arch": "386"
},
{
"os": "freebsd",
"arch": "amd64"
},
{
"os": "freebsd",
"arch": "arm"
},
{
"os": "freebsd",
"arch": "arm64"
},
{
"os": "linux",
"arch": "386"
},
{
"os": "linux",
"arch": "amd64"
},
{
"os": "linux",
"arch": "arm"
},
{
"os": "linux",
"arch": "arm64"
},
{
"os": "openbsd",
"arch": "386"
},
{
"os": "openbsd",
"arch": "amd64"
},
{
"os": "solaris",
"arch": "amd64"
},
{
"os": "windows",
"arch": "386"
},
{
"os": "windows",
"arch": "amd64"
},
{
"os": "windows",
"arch": "arm"
},
{
"os": "windows",
"arch": "arm64"
}
]
}
],
```

**Comment by joncourt** [comment] 2022-05-29 22:47
Had the same problem for a while. Seem to have resolved it with `rm -rf .terraform*` then `terraform init -reconfigure -upgrade`.

**Comment by sfc-gh-swinkler** [comment] 2022-05-31 16:24
@joncourt thank you for your input on this issue. `-upgrade` will force Terraform to upgrade installed providers. https://www.terraform.io/cli/commands/init#upgrade-1 that is good to use. this can also be done but setting the version in the Terraform configuration block. I wouldn't recommend using `-reconfigure` since this will potentially change the backend you are using and could lead to some unexpected behavior. If you are running Terraform locally then this will have no effect.

@smswamy can you please let me know if `terraform init -upgrade` works for you?

**Comment by joncourt** [comment] 2022-05-31 21:34
Thanks @sfc-gh-swinkler. I was busy trying anything at the time and I think this was a red-herring. I since know more - I planned to come back here and comment as such but couldn't actually remember where it was I'd commented.

I believe it's a bit of confusion which happens when switching from the chanzuckerberg name to the snowflake-labs one.... the chanzuckerberg one doesn't support darwin_arm64 I think and when a `terraform -upgrade` occurs with a bound like `>= 0.29.1` then it attempts to load `0.34.0` which fails. You could subsequently switch to the snowflake-labs namespace which I thought should work but i had a leftover chanzuckerberg one hanging around somewhere (must be the state file i think - not local) which kept killing it.

I've found that going back to `chanzuckerberg/snowflake` `version = "0.33.1"` and doing an `init` `apply` cycle, then switching to `snowflake-labs/snowflake` `version = "0.33.1"` with another `init` `apply` cycle before finally arriving at `snowflake-labs/snowflake` `version = "0.34.0"` seems to work... (i.e. clean up by fixing to v0.33.1, change the namespace inside that version, then you can upgrade)

in essence switch to the snowflake labs namespace before going past version 0.33.1 seems to be the rule.

**Comment by elikschultz** [comment] 2022-06-27 14:26
I was getting a similar error when deploying, although things were working fine locally:

````
Provider [registry.terraform.io/chanzuckerberg/snowflake](http://registry.terraform.io/chanzuckerberg/snowflake) v0.36.0 does not
 have a package available for your current platform, linux_amd64.
```` 

It seems the issue in my case was that the remote state file still had the old provider version. When I ran `terraform state replace-provider chanzuckerberg/snowflake Snowflake-Labs/snowflake` with the appropriate backend selected, it fixed the issue.

**Comment by sfc-gh-swinkler** [comment] 2022-07-01 22:58
Can I close this issue? Or is there still a problem?

**Comment by joncourt** [comment] 2022-07-01 23:38
Ok by me to close. Doing a replace provider resolved it for me

**Closed** 2022-07-01 23:40 UTC
