### ISSUE TITLE
Oauth Access Token expires after 10 minutes

### ISSUE THREAD

**Issue by ddemara-indeed** [Snowflake-Labs/terraform-provider-snowflake#980] opened 2022-04-20 15:47 UTC
Provider Version - 0.31.0

Terraform Version - 1.1.8

Describe the bug - When Terrraform plan runs longer than 10 minutes while using OAtuh for authentication, plan fails as access token expires, life is only 10 minutes. 

Expected behavior - When Terraform Plan runs lnger than 10 minutes, OAuth should retreive new access tokens with Refresh token so that connection may be continuous.

**Comment by gjv9491** [comment] 2022-04-20 15:58
@ddemara-indeed  i am working on this thank you for creating this issue

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:47
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:47 UTC
Labels: bug

**Comment by tbsuper** [comment] 2025-05-14 04:15
This is still an issue on 0.92.0, token times out after 600 seconds during the plan phase, interesting that it doesn't fail in long running apply phases.

We're unable to upgrade because of this issue, will look to move to another form of auth.

**Comment by sfc-gh-jmichalak** [comment] 2025-05-14 10:09
Hi @tbsuper 👋 

Have you tried tweaking `timeout` [fields](https://registry.terraform.io/providers/snowflakedb/snowflake/latest/docs#optional) in the provider configuration? They are passed directly to the [Go driver](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Connection_Parameters). Could you also check the newest version? Now we use driver v1.13.3, maybe it has been solved there.
