### ISSUE TITLE
Applying plan to add grants caused default namespace for user to go missing

### ISSUE THREAD

**Issue by jshields** [Snowflake-Labs/terraform-provider-snowflake#882] opened 2022-03-02 17:32 UTC
**Provider Version**
0.25.9

**Terraform Version**
0.15.5

**Describe the bug**

After applying a plan to create a grant resource, we started seeing errors in our production Snowflake environment saying the following:
```
Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
```

We already had the default namespace set by resources in another Terraform project, and this error had been previously resolved  by these resources, before it came back after applying an unrelated plan as described above.

The plan output also included a lot of noise saying the roles had been removed from outside Terraform but were being re-added by the plan, which wasn't true, the roles still had the grants. (Only one grant resource was added, 50 resources were not actually changed.)

```
snowflake_file_format_grant.prd_csv_custom_file_format_grant: Creating...
snowflake_table_grant.redacted_dev_us_redacted_table_grant_future["REFERENCES"]: Modifying... [id=redacted_DEV|US_REDACTED||REFERENCES|true]
snowflake_schema_grant.redacted_prd_redacted_schema_grant["USAGE"]: Modifying... [id=redacted_PRD|REDACTED||USAGE|true]
snowflake_schema_grant.redacted_prd_ca_redacted_schema_grant_dev_rw["MONITOR"]: Modifying... [id=redacted_PRD|CA_REDACTED||MONITOR|false]
# ...  50 resources were listed here ...

Apply complete! Resources: 1 added, 50 changed, 0 destroyed.
```

Once the errors started happening, we manually ran SQL in the Snowflake web UI to re-add the default namespace setting that should have been coming from our users project in Terraform.

**Expected behavior**

When adding new grants, role and namespace settings on users should not go missing.

**Code samples and commands**

In grants project, the project that had the plan run which caused this issue was adding a file format grant:
```
resource "snowflake_file_format_grant" "prd_csv_custom_file_format_grant" {
  provider = snowflake.account_admin

  database_name     = data.terraform_remote_state.databases.outputs.redacted_prd_database_name
  schema_name       = data.terraform_remote_state.schemas.outputs.redacted_prd_insights_media_schema
  file_format_name  = data.terraform_remote_state.file_formats.outputs.prd_csv_custom_file_format_name

  privilege = "USAGE"

  roles = [
    "ACCOUNTADMIN",
    "DEV_RW",  # the new grant being added
    data.terraform_remote_state.roles.outputs.redacted_prd_role_name
  ]

  with_grant_option = false
}

```

In users project within the same repo:
```
resource "snowflake_user" "redacted" {
  provider = snowflake.account_admin
  # ... redacted

  default_role      = data.terraform_remote_state.roles.outputs.production_role_name
  default_namespace = data.terraform_remote_state.databases.outputs.production_database_name
}
```

Update: this issue happens whenever we added grants using the `chanzuckerberg` provider and we've started using `snowsql_exec` to run raw SQL grants from the `aidanmelen/snowsql` provider to avoid the issue.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:49
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:49 UTC
Labels: bug
