### ISSUE TITLE
Crash when using snowflake_stream

### ISSUE THREAD

**Issue by imanebenomar** [Snowflake-Labs/terraform-provider-snowflake#2672] opened 2024-04-03 15:02 UTC
### Terraform CLI and Provider Versions

1.1.0

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.87.2"
    }
  }
}
resource "snowflake_stream" "stream" {
  for_each = var.BRONZE_TABLES
  comment = "A stream."

  database = snowflake_database.bronze_layer.name
  schema   = each.value.schema
  name     = "stream-${each.value.table_name}"

  on_table    = each.value.table_name
  append_only = false
  insert_only = false
  show_initial_rows = false
  #owner = snowflake_role.ELT_ROLE.name
}
```

### Expected Behavior

to be able to crate stream on tables

### Actual Behavior

I get this error when executing terraform apply:
Plan: 2 to add, 0 to change, 0 to destroy.
module.snowflake.snowflake_stream.stream["companies"]: Creating...
module.snowflake.snowflake_stream.stream["subscriptions"]: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.87.2 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.SchemaObjectIdentifier

goroutine 48 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateStream(0x0?, {0x1cc21a0?, 0xc000c46068?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/stream.go:130 +0x1667
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x243d388?, {0x243d388?, 0xc000d55680?}, 0xd?, {0x1cc21a0?, 0xc000c46068?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b0ba40, {0x243d388, 0xc000d55680}, 0xc000d09040, 0xc000a8f500, {0x1cc21a0, 0xc000c46068})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000a2c558, {0x243d388?, 0xc000d554d0?}, 0xc0009cd1d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x24531a0?, 0xc000a2c558?}}, {0x243d388, 0xc000d554d0}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x54
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x243d3c0?, {0x243d388?, 0xc000d551d0?}, 0xc0009cd180)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000b5a500, {0x243d388?, 0xc000d547e0?}, 0xc000d00700)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x2014140?, 0xc000b5a500}, {0x243d388, 0xc000d547e0}, 0xc000a8ed00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000142d20, {0x243d388, 0xc000d54750}, {0x244e480, 0xc000682820}, 0xc000d4ed80, 0xc000266b10, 0x343edb8, 0x0)
        google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc000142d20, {0x244e480, 0xc000682820}, 0xc000d4ed80)
        google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
        google.golang.org/grpc@v1.60.0/server.go:1027 +0x115
panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.SchemaObjectIdentifier

goroutine 47 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateStream(0x0?, {0x1cc21a0?, 0xc000c46068?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/stream.go:130 +0x1667
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x243d388?, {0x243d388?, 0xc000ebe480?}, 0xd?, {0x1cc21a0?, 0xc000c46068?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b0ba40, {0x243d388, 0xc000ebe480}, 0xc000cf4340, 0xc000bc2a00, {0x1cc21a0, 0xc000c46068})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000a2c558, {0x243d388?, 0xc000ebe2d0?}, 0xc000840e10)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x24531a0?, 0xc000a2c558?}}, {0x243d388, 0xc000ebe2d0}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x54
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x243d3c0?, {0x243d388?, 0xc000a73fb0?}, 0xc000840dc0)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000b5a500, {0x243d388?, 0xc000ada690?}, 0xc000ac1dc0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x2014140?, 0xc000b5a500}, {0x243d388, 0xc000ada690}, 0xc000c1b880, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000142d20, {0x243d388, 0xc000ada5d0}, {0x244e480, 0xc000682820}, 0xc000d4ec60, 0xc000266b10, 0x343edb8, 0x0)
        google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc000142d20, {0x244e480, 0xc000682820}, 0xc000d4ec60)
        google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
        google.golang.org/grpc@v1.60.0/server.go:1027 +0x115

Error: The terraform-provider-snowflake_v0.87.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment] 2024-04-03 15:37
Hey @imanebenomar. Thanks for reaching out to us.

It seems that in your `var.BRONZE_TABLES` `table_name` is not a fully qualified name (that is expected in this context). You have to specify `"<db_name>"."<schema_name>"."<table_name>"` for each of the tables and use it for `on_table`.

Identifiers are the source of many issues we will be reworking them soon: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#identifiers-rework.

**Comment by imanebenomar** [comment] 2024-04-03 16:05
Thank you for your help. I replaced it with :
on_table    = "${snowflake_database.bronze_layer.name}.${each.value.schema}.${each.value.table_name}"
and now I have this error :

**Comment by sfc-gh-asawicki** [comment] 2024-04-04 07:35
Hey @imanebenomar. I will try to reproduce it in the upcoming days and will get back to you.

**Comment by imanebenomar** [comment] 2024-04-09 07:46
Hello, any news about this issue ?
FYI, even with the error the script creates my streams.
![Capture d’écran du 2024-04-09 09-45-41](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/135624822/e82039d0-9f52-4204-baf0-842d9fa0782d)
![Capture d’écran du 2024-04-09 09-46-09](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/135624822/1cba771e-9a99-4126-8b59-63492194e91b)

**Comment by sfc-gh-asawicki** [comment] 2024-04-09 09:47
Hey @imanebenomar. I haven't yet reproduced it, I will let you know once I will.

**Comment by sfc-gh-asawicki** [comment] 2024-04-11 08:37
Hey @imanebenomar. I've finally had some time to reproduce this behavior. I will create a PR with the fix today. It should land with the next release.

As a current workaround you can try `"${snowflake_database.bronze_layer.name}.${each.value.schema}.\"${each.value.table_name}\""` (the reason is that SHOW result in Snowflake puts quoting only where necessary, therefore for the small-caps it's needed but not for the uppercase, and you have db and schema uppercased and table lowercased). After the fix, we will suppress the diff for such cases.

**Comment by imanebenomar** [comment] 2024-04-11 08:53
Hello @sfc-gh-asawicki  . Thank you for your help.
it worked well for me with the workaround.

Have a good day.

**Comment by Hyurt** [comment] 2024-05-02 11:58
Hello, not trying to hijack this issue, but I'm facing the same issue with a similar configuration, even with the provider in 0.89.0

**Comment by sfc-gh-asawicki** [comment] 2024-05-02 12:16
Hey @Hyurt. Please provide your configuration and error logs then; I will take a look.

**Comment by Hyurt** [comment] 2024-05-02 12:41
To be fair, I think the documentation could be a bit clearer

The `snowflake_stream` resource requires a FQDN name for the table (unless the provider has a default DB/schema ?)
Making this more explicit would prevent user of just running 
```
on_table = snowflake_table.my_tbl.name
```
As it wouldn't work


## Configuration
```
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.89.0"
    }
  }
}

resource "snowflake_table" "my_table" {
  for_each = toset(var.database_environment)
  provider = snowflake.SYSADMIN
  database                    = each.value
  schema                      = "specific_schema"
  name                        = "MY_TABLE"
  change_tracking             = true
  column {
    name     = "VALUE"
    type     = "VARCHAR"
    nullable = true
  }
}

resource "snowflake_stream" "my_stream" {
  for_each = toset(var.database_environment)
  provider = snowflake.SYSADMIN
  database = each.value
  schema   = "PUBLIC"
  name     =  "MY_STREAM"
  on_table    = snowflake_table.my_table[each.value].name
  append_only = true
}

```

 
## Error
```
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).ValidateResourceConfig request was cancelled.
╵

Stack trace from the terraform-provider-snowflake_v0.89.0 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.SchemaObjectIdentifier

goroutine 78 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateStream(0x0?, {0x105aa0ac0?, 0x14000892200?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/stream.go:132 +0x123c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x105e89008?, {0x105e89008?, 0x14000b58fc0?}, 0xd?, {0x105aa0ac0?, 0x14000892200?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000cff340, {0x105e89008, 0x14000b58fc0}, 0x140009caea0, 0x14000b10980, {0x105aa0ac0, 0x14000892200})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140009a5c68, {0x105e89008?, 0x14000b58e10?}, 0x14000b46730)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xb08
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x105e9e718?, 0x140009a5c68?}}, {0x105e89008, 0x14000b58e10}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x105e89040?, {0x105e89008?, 0x14000b58b10?}, 0x14000b466e0)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x140009a20a0, {0x105e89008?, 0x14000b58300?}, 0x14000b52a10)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x105df1da0?, 0x140009a20a0}, {0x105e89008, 0x14000b58300}, 0x14000b10700, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000e2d20, {0x105e89008, 0x14000b58270}, {0x105e99ca0, 0x140001031e0}, 0x14000b39b00, 0x1400082e2a0, 0x106d4feb8, 0x0)
        google.golang.org/grpc@v1.60.0/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140000e2d20, {0x105e99ca0, 0x140001031e0}, 0x14000b39b00)
        google.golang.org/grpc@v1.60.0/server.go:1783 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.0/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 57
        google.golang.org/grpc@v1.60.0/server.go:1027 +0x138

Error: The terraform-provider-snowflake_v0.89.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by sfc-gh-asawicki** [comment] 2024-05-02 12:54
Hey @Hyurt. Yes, fully qualified name is required here, so the configuration you have provided is not expected to work.

We will be reworking identifiers (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#identifiers-rework) and each particular resource (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#supporting-all-snowflake-ga-features) - documentation included.

Before that, we will welcome a contribution (read more in https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2756).

**Comment by sfc-gh-asawicki** [comment] 2024-05-15 08:35
Closing as completed. Please open a new issue if the problem persists in the newest provider version.

**Closed by sfc-gh-asawicki** 2024-05-15 08:35 UTC
Labels: general-usage
