### ISSUE TITLE
Principal level resource grants instead of resource level

### ISSUE THREAD

**Issue by ndavies-om1** [Snowflake-Labs/terraform-provider-snowflake#847] opened 2022-02-07 14:47 UTC
**Is your feature request related to a problem? Please describe.**

The current implementation of grants, whether it be Database, Schema, Account etc prevent my from encapsulating grants within modules or alongside the terraform code that creates resources that need to be given grants at a database, schema, account level etc. This is because all grants are implemented as resource level grants, ie the unique identifier for the grants resource is based upon the resource and privilege. You need to know all the resources that need access to the resource and their level of access when you create your resource level grants.

**Describe the solution you'd like**

A far better solution and one that is more in line with how AWS does and recommends doing permissions, is to make the grants resource be strongly tied to the principal rather than the target resource. For example, a `snowflake_database_grant` resource would look like

```
resource snowflake_database_grant grant {
  principal = {
    type = "role" // could be role or share
    name = "myrole"
  }

  privilege = "USAGE"
  dbs     = ["db1", "db2"]
  with_grant_option = false
}

```

**Describe alternatives you've considered**

We are using the current implementation and it is restricting how we can leverage Terraform for Snowflake

**Additional context**

I have included a zipfile of the problem and how an ideal implementation would work
[terraform_example.zip](https://github.com/chanzuckerberg/terraform-provider-snowflake/files/8016141/terraform_example.zip)

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:49
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:49 UTC
Labels: feature-request
