### ISSUE TITLE
Terraformer support

### ISSUE THREAD

**Issue by ezeql** [Snowflake-Labs/terraform-provider-snowflake#689] opened 2021-09-24 04:54 UTC
Hi  devs@chanzuckerberg !

Thank you for this great provider.  I'm working for a company where we have a lot of existing infrastructure and we are evaluating ideas for generating the required code/state for start managing Snowflake using this provider; Manually is a possibility but, hey! we are hackers :)

I've used [Terraformer](https://github.com/GoogleCloudPlatform/terraformer) before with some sort of luck: I was wondering if someone actually tried to create a snowflake importer for this provider on Terraformer and I found out  [a fork in your organization containing some work towards it ](https://github.com/chanzuckerberg/terraformer/tree/snowflake).

Could you share the status of it? Are you looking for help/considering to continue this effort? Any hint or guide on this would be pretty much appreciated.

Thank you :)
-Ez

**Comment by edulop91** [comment] 2021-09-24 14:02
Hi @ezeql ! Thanks for reaching out. We used that fork to bootstrap our Snowflake environments into Terraform a couple of years ago. Unfortunately, to upstream those changes would've required a fair amount of work for which we didn't have capacity at the time. At this point I'm not sure how far behind did that fork fall wrt to both Terraformer and Snowflake Provider projects. 

Having said that, I think this would still be a valuable contribution to the Terraformer/Snowflake Provider projects! It definitely saved us a bunch of time/work while bootstrapping our environments.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:53
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:53 UTC
Labels: feature-request
