### ISSUE TITLE
Facing error during re-run the same terraform script

### ISSUE THREAD

**Issue by dasarisunil09** [Snowflake-Labs/terraform-provider-snowflake#776] opened 2021-12-03 08:34 UTC
**Provider Version**

0.22.0

**Terraform Version**

1.0.11

**Describe the bug**

Basically, Terraform script is assigning role(SYSADMIN) to the user, when I run the script for the first time, its executed successfully and the role(SYSADMIN) is assigned to user as expected, but when I re-run the same script its showing below error:

Error: 003042 (42501): SQL compilation error:
│ Role 'SYSADMIN' is a system object. REVOKE cannot be performed.
│ 
│   with snowflake_role_grants.grants,
│   on grants.tf line 1, in resource "snowflake_role_grants" "grants":
│    1: resource "snowflake_role_grants" "grants" {

**Expected behavior**

**Code samples and commands**

resource "snowflake_role_grants" "grants" {
        provider  = snowflake.security_admin
        role_name = "SYSADMIN"
        users     = [upper(var.username)]
    }

**Additional context**

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:51
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:51 UTC
Labels: bug
