### ISSUE TITLE
Stage resource doesn't support REFRESH_ON_CREATE directory option

### ISSUE THREAD

**Issue by wesleyhillyext** [Snowflake-Labs/terraform-provider-snowflake#989] opened 2022-05-02 20:37 UTC
**Is your feature request related to a problem? Please describe.**

The `snowflake_stage` resource takes a `"directory"` parameter, which is basically just a SQL string to include in the `CREATE STAGE` statement. If I include `"REFRESH_ON_CREATE = false"` in this string, then the code never aligns with the state pulled from Snowflake. Snowflake does not return the `REFRESH_ON_CREATE` option from `DESCRIBE STAGE`, since it has no meaning after the `CREATE STAGE` statement has completed.

Including `"REFRESH_ON_CREATE = false"` is important when creating external stages to paths which already contain a very large number of files. Otherwise, creating the stage can take a very long time. Better to create the stage without a populated directory via terraform, then manually refresh the stage in Snowflake.

**Describe the solution you'd like**

I think ideally the `"directory"` parameter wouldn't be a string, it would be a sub-object or something so that the provider could better understand what was happening. It could then know that the `refresh_on_create` sub-property should not be considered part of the state. But this ship may have sailed.

**Describe alternatives you've considered**

A `lifecycle { ignore_changes = ["directory"] }` directive would solve it, but would also mean the directory is not removed if the directory property is removed.

In the end I temporarily included `"REFRESH_ON_CREATE = false"` then removed it after I applied the terraform. But manual work to apply terraform is quite annoying in situations where the same change has to be made in multiple environments and multiple accounts. Or when trying to automate deployment of terraform changes.

--

In general, I suggest careful consideration before adding any resource parameters which like this are opaque SQL. I doubt we'd want to get into the business of parsing SQL in the provider.

**Comment by mqunbar** [comment] 2022-11-22 14:47
Appears to be the same issue if you pass `AUTO_REFRESH=FALSE` in the `"directory"` parameter

**Comment by sfc-gh-swinkler** [comment] 2023-07-25 18:14
I agree that `directory` should be an object or a nested block, not a string. Templating raw SQL is not user friendly, and also makes performing diffs more complicated. We will change this field in a future major release to not be a string. In the meantime, I believe your approach is correct.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:46
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:46 UTC
Labels: feature-request

**Comment by remi-f-artelia** [comment] 2024-05-17 12:52
This issue needs to be re-opened
