### ISSUE TITLE
Snowflake connection fails when Session ID cannot be unmarshaled

### ISSUE THREAD

**Issue by rschack-cedar** [Snowflake-Labs/terraform-provider-snowflake#2742] opened 2024-04-23 16:56 UTC
### Terraform CLI and Provider Versions

```
Terraform v1.8.1
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.89.0
```

### Terraform Configuration

```terraform
resource "snowflake_role" "role" {
  name    = "dev_read_only"
  comment = "Read only dev role"
}
```

### Expected Behavior

When running `terraform plan`, we expect to see the plan for the newly created role

### Actual Behavior

The following error was received:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: open snowflake connection: json: cannot unmarshal number 3.2984262213766e+16 into Go struct field authResponseMain.data.sessionId of type int64
│ 
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on terraformconfig.tf line 13, in provider "snowflake":
│   13: provider "snowflake" {
│ 
```

### Steps to Reproduce

Run `terraform plan` on a Snowflake account that has at least a 17-digit session ID

### How much impact is this issue causing?

High

### Logs

https://gist.github.com/rschack-cedar/6a75497f2b7b7ae7f5bde6637dbdeb56

### Additional Information

After looking at logs between 2 different Snowflake accounts (where one of them is working), the failure happens after the `SELECT CURRENT_SESSION() as CURRENT_SESSION` query is submitted.

The session ID when the failure occurs is much larger than on our account that's running successfully.

Example Session ID: `32984262213757226`

**Comment by sfc-gh-jcieslak** [comment] 2024-04-24 09:56
Hey @rschack-cedar 👋 
It seems it's failing, because `3.2984262213766e+16` is a floating-point number and the session id is expected to be an integer. If it's really `SELECT CURRENT_SESSION() as CURRENT_SESSION` that is failing then it may be Snowflake or https://github.com/snowflakedb/gosnowflake issue. Could you provide the gist logs with the `TF_LOG=DEBUG`, so we'll be able to see what SQLs are being run? If you can, please provide also another gist logs with the `TF_LOG=DEBUG` and `SF_TF_GOSNOWFLAKE_LOG_LEVEL=debug`, so we'll also get additional Snowflake driver logs.

**Comment by sfc-gh-jcieslak** [comment] 2024-04-25 07:35
What environment variables were set in the provided logs? (I'm guessing `TF_LOG=DEBUG`)
Is `SF_TF_GOSNOWFLAKE_LOG_LEVEL=debug` also set here? If not, please provide another gist with with `TF_LOG=DEBUG` and `SF_TF_GOSNOWFLAKE_LOG_LEVEL=debug` set.

**Comment by rschack-cedar** [comment] 2024-04-25 14:46
Yes, I set `TF_LOG=DEBUG` and `SF_TF_GOSNOWFLAKE_LOG_LEVEL=debug`

**Comment by sfc-gh-jcieslak** [comment] 2024-04-29 06:10
Sorry for the late answer, but in that case could you also send the logs with `TF_LOG=DEBUG`,  `SF_TF_GOSNOWFLAKE_LOG_LEVEL=trace`, and `SF_TF_NO_INSTRUMENTED_SQL=1`. For now, this looks like something may be wrong with the Snowflake driver and hopefully, additional logs will tell us more about the root cause of this issue. As you said, it looks like something with the session id, but I'm not sure why It would be returned as a floating-point number.

**Comment by rschack-cedar** [comment] 2024-05-06 14:06
@sfc-gh-jcieslak Sorry for the delay--I'm not seeing any difference to the logs when I add/update those environment variables. It appears that maybe our Snowflake session IDs are larger than expected, and they are being converted into scientific notation and/or string. The session IDs we are getting are 17-digit numbers like `32984262213757226`

**Comment by sfc-gh-jcieslak** [comment] 2024-05-07 05:26
Thank you, I'll follow up with the gosnowflake driver team.

**Comment by sfc-gh-jcieslak** [comment] 2024-05-08 11:57
We received a short instruction from the gosnowlfake driver's team to setup a proxy with Burp and see the exchanged information before the error occurs:
```text
1. Download [burp suite community](https://portswigger.net/burp/communitydownload), install and start.
2. From settings menu export certificate and add it to your OS cert store (or use any other mechanism to trust certificate).
3. Run app with HTTPS_PROXY=localhost:8080 env variable.
```
If that won't work the next steps are needed. As we are pretty sure that's not the error coming from the provider, please reach out to the gosnowflake driver Snowflake support or Snowflake support, because that's where the root cause seems to be. Unfortunately, there's nothing more we can do about retrieving more information about the root cause of this problem.

**Comment by sfc-gh-jcieslak** [comment] 2024-07-11 12:00
Closing as there's nothing else we can do here. The issue (if still persists) should be escalated to the mentioned teams.

**Closed by sfc-gh-jcieslak** 2024-07-11 12:00 UTC
Labels: bug, category:other
