### ISSUE TITLE
Typo in documentation for resource_monitor_grant

### ISSUE THREAD

**Issue by milldr** [Snowflake-Labs/terraform-provider-snowflake#455] opened 2021-02-17 22:47 UTC
**Provider Version**

0.23.2

**Describe the bug**

There is a typo in the name of the grant resource for resource monitoring. The documentation says "snowflake_monitor_grant", whereas this should be "snowflake_resource_monitor_grant". 

https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/resource_monitor_grant

**Comment by kpodkov** [comment] 2021-04-12 10:15
Can confirm. You get unsupported resource type error if you follow the example in the doc:

```
The provider provider.snowflake does not support resource type
"snowflake_monitor_grant".
```

As noted above, to fix it - replace the resource name as `snowflake_resource_monitor_grant`

**Comment by jacquiwuc** [comment] 2021-09-15 03:03
yup, I also met the same error today: The provider chanzuckerberg/snowflake does not support resource type "snowflake_monitor_grant".

Through changing snowflake_monitor_grant to snowflake_resource_monitor_grant can fix the error.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:00
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:00 UTC
Labels: bug
