### ISSUE TITLE
Can't set owner in snowflake_pipe

### ISSUE THREAD

**Issue by Dzvezdana** [Snowflake-Labs/terraform-provider-snowflake#793] opened 2021-12-21 09:29 UTC
**Provider Version**
0.25.30

**Terraform Version**
 0.14.6

**Describe the bug**

When running `terraform plan`, setting the owner in `snowflake_pipe`:

```
resource "snowflake_pipe" "pipe" { 
     ...
     owner = "ROLE1" 
}
```

fails with: 

```
Error: Value for unconfigurable attribute
on ../snowflake-pipe.tf line 65, in resource "snowflake_pipe" "pipe":
65:   owner             = "ROLE1"

Can't configure a value for "owner": its value will be decided automatically
based on the result of applying this configuration.
```

**Expected behavior**

According to the [documentation](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/pipe), it should be possible to set the owner of Snowpipe.

**Comment by senmm** [comment] 2022-07-15 06:21
I have the same issue.

**Provider Version**
v0.37.1

**Terraform Version**
v1.2.2

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:51
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:51 UTC
Labels: bug
