### ISSUE TITLE
Lack of function: `USE ROLE <role_name>`

### ISSUE THREAD

**Issue by KennethanCeyer** [Snowflake-Labs/terraform-provider-snowflake#794] opened 2021-12-21 10:32 UTC
**Is your feature request related to a problem? Please describe.**

There is an issue to create a role or user with the user who has `PUBLIC` as the default role.

For more details, check the following example.

**e.g)**

- I have `tf_user` in my snowflake account.
- `tf_user` has following roles
   - **PUBLIC (default)**
   - SYSADMIN
   - SECURITYADMIN

So, `tf_user` **can create user or role**.
However, `USE ROLE SECURITYADMIN` query is needed to execute in advance.

```sql
USE ROLE SECURITYADMIN
CREATE ROLE my_role -- ok
CREATE USER ... -- ok
```

Let's think about the case of Terraform.
We assume that the terraform env settings have been done, And Terraform <-> Snowflake connectivity is good.

```hcl
resource "snowflake_role" "test_role" {
  name    = "test_role"
  comment = "A role for testing"
}
```

Output

```plaintext
Error: error creating role: 003001 (42501): SQL access control error:
Insufficient privileges to operate on account 'ACCOUNT_NAME'
  with snowflake_role.test_role,
  on my_test.tf line 1, in resource "snowflake_role" "test_role":
  1: resource "snowflake_role" "test_role" {
```

However, If we change the default role of tf_user as follows.

```sql
ALTER USER "tf_user" SET default_role = SECURITYADMIN;
```

Then, The above terraform hcl code works well.

The point is that `USE ROLE xxx` in Snowflake terraform provider doesn't seem to be supported.

**Describe the solution you'd like**

The ability to set `USE ROLE xxx` in each resource allocation process should be provided.

**Comment by onelharrison** [comment] 2022-01-21 23:55
@KennethanCeyer This can be accomplished using terraform provider aliases.

```
provider "snowflake" {
   alias = "security_admin"
   role  = "SECURITYADMIN"
}

provider "snowflake" {
   alias = "sys_admin"
   role  = "SYSADMIN"
}

# USE ROLE SECURITYADMIN

resource "snowflake_role" "test_role" {
  provider   = snowflake.security_admin
  name        = "test_role"
  comment = "A role for testing"
}

# USE ROLE SYSADMIN

resource "snowflake_database" "test_db" {
  provider   = snowflake.sys_admin
  name        = "test_db"
}
```

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:50
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:50 UTC
Labels: feature-request
