### ISSUE TITLE
ERROR: return-type NUMBER(38,0) not recognised

### ISSUE THREAD

**Issue by timothygarza-dazn** [Snowflake-Labs/terraform-provider-snowflake#950] opened 2022-03-28 10:35 UTC
**Provider Version**

0.29.0

**Terraform Version**

0.13.0

**Describe the bug**
Using this provider to create a Snowflake External Function with 'integer' as the return_type:

Error: return_type NUMBER(38,0) not recognized.

Strangely, the Snowflake External Function DOES get deployed and also Snowflake External Functions DO allow return_type NUMBER(38,0) when created directly in Snowflake as seen below.

**Expected behaviour**

No false-flag error is returned, especially as the External Function does actually get deployed. However, that error is now preventing fix-forward or roll-back.

**Code samples and commands**

- Problematic resource:
resource "snowflake_external_function" "resource_name"
blah
  return_type               = "integer"   --<-- maps to Snowflake NUMBER(38,0)

- Create External Function directly using Snowflake UI (succeeds);

CREATE EXTERNAL FUNCTION MYDATABASE.MYSCHEMA."MyExternalFunction"(
PAYLOAD OBJECT
)
RETURNS NUMBER(38,0)  --<-- Allows Number!!

**Additional context**

I believe this error returned by the Provider is a false-flag.

FIX: Dropping the created External Function, manually updating the Terraform statefile to remove all External Function artefacts and then attempting again with different return_type value, succeeds.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:48
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:48 UTC
Labels: bug
