### ISSUE TITLE
Expose notification_channel of snowflake_external_table(s)

### ISSUE THREAD

**Issue by michael-robbins** [Snowflake-Labs/terraform-provider-snowflake#735] opened 2021-10-26 23:13 UTC
**Describe the solution you'd like**

When running `SHOW EXTERNAL TABLES` there is a `notification_channel` column that is the SQS queue needed to wire up 'auto refresh of external tables'.

Are we able to expose this as part of the data source and the resource? This would help when integrating an external table with an AWS S3 bucket using Terraform.

We would then be able to take this attribute and use that in the S3 Bucket Notification resource.

**Describe alternatives you've considered**

Currently this requires a multi-stage-deployment where we are executing terraform multiple times extracting the resource IDs inbetween.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:53
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:53 UTC
Labels: feature-request
