### ISSUE TITLE
 Error: Plugin did not respond

### ISSUE THREAD

**Issue by anikarunakaran** [Snowflake-Labs/terraform-provider-snowflake#984] opened 2022-04-26 07:07 UTC
Does anyone know the root cause of this error?.

C:\demo-terraform>terraform.exe -version
Terraform v1.1.9
on windows_386
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.22.0

C:\demo-terraform>

PS C:\demo-terraform> .\terraform.exe apply --auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # snowflake_database.UTIL_DB1 will be created
  + resource "snowflake_database" "UTIL_DB1" {
      + comment                     = "test database"
      + data_retention_time_in_days = (known after apply)
      + id                          = (known after apply)
      + name                        = "ABC"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
snowflake_database.UTIL_DB1: Creating...
╷
│ Error: Plugin did not respond
│
│   with snowflake_database.UTIL_DB1,
│   on main.tf line 23, in resource "snowflake_database" "UTIL_DB1":
│   23: resource "snowflake_database" "UTIL_DB1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.32.0.exe plugin:

panic: time: missing Location in call to Time.In

goroutine 20 [running]:
time.Time.In(...)
        time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc000121b90, {{0xc0001c38d0, 0xa}, 0x0, 0x0, {0xc0001c38e0, 0xd}, 0x0, 0x3, 0x1}, ...)
        github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc00048c840, {0xc000121b90, 0x9, 0xd})
        github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x1481240, 0xc0005bd030}, {0x14812a0, 0x1cca6f0}, 0x0, 0x0}, {0x14a4508, 0xc000054078}, {0x1490af8, 0xc00048c840}}, ...)
        github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc0005da800)
        database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
        database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x148f498, 0xc0005da830}, 0xc000177180)
        database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc0005da800)
        database/sql/sql.go:2944 +0x6f
github.com/jmoiron/sqlx.(*Row).Scan(0xc00025d680, {0xc000121a70, 0xc000526000, 0x9})
        github.com/jmoiron/sqlx@v1.3.4/sqlx.go:201 +0xb4
github.com/jmoiron/sqlx.(*Row).scanAny(0xc00025d680, {0x10a5180, 0xc000526000}, 0x1)
        github.com/jmoiron/sqlx@v1.3.4/sqlx.go:789 +0x605
github.com/jmoiron/sqlx.(*Row).StructScan(...)
        github.com/jmoiron/sqlx@v1.3.4/sqlx.go:794
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.ScanDatabase(0xc00011ac30)
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/database.go:93 +0x45
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadDatabase(0xc0005dac80, {0x126f0e0, 0xc00011ac30})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/database.go:152 +0x1bd
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.CreateResource.func1(0x1286fd7, {0x126f0e0, 0xc00011ac30})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/resource.go:53 +0x31a
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.CreateDatabase(0x0, {0x126f0e0, 0xc00011ac30})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/database.go:85 +0xfa
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1127020, {0x14a44d0, 0xc0007062c0}, 0x2, {0x126f0e0, 0xc00011ac30})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0006980e0, {0x14a44d0, 0xc0007062c0}, 0xc000287110, 0xc0005dab00, {0x126f0e0, 0xc00011ac30})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0004187b0, {0x14a44d0, 0xc0007062c0}, 0xc0002c88c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0007225a0, {0x14a4578, 0xc0002621b0}, 0xc000150000)
        github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:812 +0x5eb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x123e860, 0xc0007225a0}, {0x14a4578, 0xc0002621b0}, 0xc00048c540, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000709c00, {0x14b7d28, 0xc0006844e0}, 0xc00014a000, 0xc0001a2bd0, 0x1c62f00, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000709c00, {0x14b7d28, 0xc0006844e0}, 0xc00014a000, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.44.0/server.go:919 +0x294

Error: The terraform-provider-snowflake_v0.32.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

PS C:\demo-terraform>

**Comment by ericpar** [comment] 2022-04-26 22:20
I believe this is the same as 945.

**Comment by sfc-gh-jalin** [comment] 2022-06-02 21:31
Hi @anikarunakaran, are you still encountering this issue?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:46
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:46 UTC
Labels: bug
