### ISSUE TITLE
Error when running `terraform apply` - Snowflake region Australia East

### ISSUE THREAD

**Issue by allanw** [Snowflake-Labs/terraform-provider-snowflake#529] opened 2021-04-28 05:44 UTC
**Provider Version**

`terraform providers`: 0.22.0

**Terraform Version**

0.15.0

**Describe the bug**

When I run `terraform apply` I get the following error:

```
│ Error: error creating database: Post "https://xxxxx.AZURE_AUSTRALIAEAST.snowflakecomputing.com:443/session/v1/login-request?requestId=xxxxx&request_guid=xxxxx&roleName=SYSADMIN": x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.snowflakecomputing.com, *.global.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, *.us-west-2.aws.snowflakecomputing.com, not xxxxx.AZURE_AUSTRALIAEAST.snowflakecomputing.com
│ 
│   on main.tf line 14, in resource "snowflake_database" "db":
│   14: resource "snowflake_database" "db" {
```

**Expected behavior**

This should create a database in my Snowflake instance.

**Comment by yohei1126** [comment] 2021-04-29 01:19
```
error creating database: Post "https://xxxxx.AZURE_AUSTRALIAEAST.snowflakecomputing.com:443/session/v1/login-request?requestId=xxxxx&request_guid=xxxxx&roleName=SYSADMIN": x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.snowflakecomputing.com, *.global.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, *.us-west-2.aws.snowflakecomputing.com, not xxxxx.AZURE_AUSTRALIAEAST.snowflakecomputing.com
```

There is issue on your certificate not a bug on this terraform plugin

**Comment by leeadh** [comment] 2021-05-09 07:05
I got thes same issue as well by following this guide https://guides.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#4 

I followed the steps here exactly. Any help?

**Comment by derekpierce** [comment] 2021-05-17 21:21
I ran into the same issue and was able to temporarily work around but defining the region like this:
```
provider "snowflake" {
    username = "..."
  account  = "..."
  region   = "ca-central-1.aws"
  role     = "..."
}
```
Seems the format of the POST request doesn't match what snowflake is actually expecting:

 x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.snowflakecomputing.com, *.global.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, *.**us-west-2.aws.snowflakecomputing.com**, not xxxxxxx.**AWS_CA_CENTRAL_1.snowflakecomputing.com**

**Comment by JimMcKenzieSmith** [comment] 2021-06-05 00:04
For me, the region had to be set to "**us-west-2**".  Then it started working.  The tutorial says to use the output of "SELECT current_region();" which is "AWS_US_WEST_2"... but that does not work.

**Comment by realtimdunbar** [comment] 2021-06-19 20:46
I added the following as line 12 

region   = "us-east-1"

and everything worked like a champ

**Comment by caiolauro** [comment] 2021-10-21 15:52
> I ran into the same issue and was able to temporarily work around but defining the region like this:
> 
> ```
> provider "snowflake" {
>     username = "..."
>   account  = "..."
>   region   = "ca-central-1.aws"
>   role     = "..."
> }
> ```
> 
> Seems the format of the POST request doesn't match what snowflake is actually expecting:
> 
> x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.snowflakecomputing.com, *.global.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, *.**us-west-2.aws.snowflakecomputing.com**, not xxxxxxx.**AWS_CA_CENTRAL_1.snowflakecomputing.com**

Changing to region from "us-east-2" to "us-east-2.aws" also worked for me :D

**Comment by muideen** [comment] 2022-01-05 20:30
I also ran into this issue and I had to change my region from "us-east-2" to "us-east-2.aws".

thanks to everyone who contributed on this thread

**Comment by onelharrison** [comment] 2022-01-12 16:07
I also ran into this issue. However, changing my region from "us-east-2" to "us-east-2.aws" doesn't address the problem. Instead of getting the x509 error, I get `Error: error creating database: 390100 (08004): Incorrect username or password was specified.`

Terraform version: 1.1.3
Snowflake provider version: 0.25.33

**Comment by stuudmuffin** [comment] 2022-02-14 21:28
I ran into this issue today also. I finally realized that there is a link to a [reference table](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#snowflake-region-ids) in the guide. Solved my issue.

**Comment by froblesmartin** [comment] 2022-10-04 13:34
> ## Using an Account Name as an Identifier
> The account identifier for an account in your organization takes one of the following forms, depending on where and how the identifier is used:
> 
> `<orgname>-account_name` (for most URLs and other general purpose usage)
> 
> To resolve this issue, remove the Terraform environment variable `SNOWFLAKE_REGION` since it is optional and replace the environment value `SNOWFLAKE_ACCOUNT` using the taxonomy above instead of the generic account identifier
> 
> This will generate a URL in the format `MY_ORG-MY_ACCOUNT.snowflakecomputing.com` which will be covered by the pattern `*.snowflakecomputing.com`

It has worked for me in both, your way and also specifying the region with the format "region.cloud" (in my case west-europe.azure"). I have been able to see the organization name and account on the new UI at the left bottom of the website, just in case someone else struggles a bit searching that info while not being admin 😂

**Comment by cappadona** [comment] 2022-12-06 14:11
This has tripped us up as well. Just submitted a PR (#1398) that attempts to shed light on the [different Snowflake account identifier formats](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html) in hope that it may help future adopters when configuring this provider.

**Comment by ybressler** [comment] 2023-07-19 02:07
I did the following to get things to work for me:
1. `unset SNOWFLAKE_REGION`
2. `export SNOWFLAKE_ACCOUNT="ORG_ID-ACCOUNT_ID"`

The `SNOWFLAKE_ACCOUNT` should match the characters on your login URL.

**Comment by davesgonechina** [comment] 2023-08-28 18:55
> I ran into this issue today also. I finally realized that there is a link to a [reference table](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#snowflake-region-ids) in the guide. Solved my issue.

Ran into this problem doing the [tutorial](https://quickstarts.snowflake.com/guide/terraforming_snowflake/index.html?index=..%2F..index#0), would be great if that pointed to the reference guide so you can get it right manually rather than a query that produces a string that fails with an unhelpful message. This issue also seems to be the same thing: https://github.com/Snowflake-Labs/sfquickstarts/issues/799

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:58
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:58 UTC
Labels: bug

**Comment by mdelhaous** [comment] 2024-09-03 16:49
Hey team,

I'm encountering an issue while setting up a Snowflake warehouse using Terraform. Here's the relevant configuration:

**variables.tf**:

variable "snowflake_account" {
  description = "The Snowflake account name"
  type        = string
  default     = "XXXXX-XXXXX"
}

variable "snowflake_username" {
  description = "The Snowflake username"
  type        = string
  default     = "xxxxx"
}

variable "snowflake_password" {
  description = "The Snowflake password"
  type        = string
  sensitive   = true
  default     = "xxxxxx@123"
}

variable "snowflake_role" {
  description = "The Snowflake role to use"
  type        = string
  default     = "ACCOUNTADMIN"
}

variable "snowflake_region" {
  description = "The Snowflake region"
  type        = string
  default     = "eu-west-3.aws"
}

variable "warehouse_name" {
  description = "The name of the Snowflake warehouse"
  type        = string
  default     = "example_warehouse"
}

**main.tf:**

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.94.1"
    }
  }
}

provider "snowflake" {
  account  = var.snowflake_account
  user     = var.snowflake_username
  password = var.snowflake_password
  region   = var.snowflake_region
}

resource "snowflake_warehouse" "example_warehouse" {
  name           = var.warehouse_name
  warehouse_size = "SMALL"
}


However, I'm running into the following error:

**error: open snowflake connection: timeout after 5m0s and 8 retries. HTTP Status: 513. Hanging?with%20provider[%22registry.terraform.io/snowflake-labs/snowflake%22],on%20main.tf%20line%2010,%20in%20provider%20%22snowflake%22:10:%20provider%20%22snowflake%22**

It seems to be a connection timeout issue. Has anyone encountered this before, or does anyone have suggestions on how to resolve it?

Thanks!

**Comment by sfc-gh-jcieslak** [comment] 2024-09-04 07:29
Hey @mdelhaous 👋 
1. I don't think the region is needed, you can remove it.
2. Make sure your account is equal to `SELECT LOWER(current_organization_name() || '-' || current_account_name());`
3. You don't have the role assigned in the provider configuration.
Let me know if that helped.

**Comment by mdelhaous** [comment] 2024-09-04 10:15
Hey @sfc-gh-jcieslak ,

Thanks for the feedback! I’ve removed the region, updated the account to SELECT LOWER(current_organization_name() || '-' || current_account_name());, and checked the role assignment in the provider configuration. Everything is working perfectly now. Thank you so much for your help!

Thanks again! 🙌
