### ISSUE TITLE
Support default object tags

### ISSUE THREAD

**Issue by YuviGold** [Snowflake-Labs/terraform-provider-snowflake#951] opened 2022-03-28 10:52 UTC
**Is your feature request related to a problem? Please describe.**

Following https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/702 that provided setting https://docs.snowflake.com/en/user-guide/object-tagging.html for certain objects, I'd like to have the option to configure globally the tags for all the objects created by the Snowflake Terraform provider.

**Describe the solution you'd like**

Add an optional `default_tags` field to the provider configuration.

Similar behavior can be seen in the AWS Terraform provider https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags .
> [default_tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags) - (Optional) Configuration block with resource tag settings to apply across all resources handled by this provider (see the [Terraform multiple provider instances documentation](https://www.terraform.io/docs/configuration/providers.html?_ga=2.3763640.902751227.1648463934-512345456.1642407181#alias-multiple-provider-instances) for more information about additional provider configurations). This is designed to replace redundant per-resource tags configurations. Provider tags can be overridden with new values, but not excluded from specific resources. To override provider tag values, use the tags argument within a resource to configure new tag values for matching keys. See the [default_tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block) Configuration Block section below for example usage and available arguments. This functionality is supported in all resources that implement tags, with the exception of the aws_autoscaling_group resource.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:48
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:48 UTC
Labels: feature-request
