### ISSUE TITLE
In resource table, unable to define COLLATE for columns

### ISSUE THREAD

**Issue by prae04** [Snowflake-Labs/terraform-provider-snowflake#651] opened 2021-08-18 20:31 UTC
**Provider Version**

chanzuckerberg/snowflake 0.25.16

**Terraform Version**

Terraform 1.0.2

**Describe the bug**

When using a COLLATE declaration when defining a column, `ID VARCHAR(16777216) COLLATE 'en-ci'` in resource snowflake_table, using single quotes results in a conversion error when applying the plan to Snowflake after terraform successfully parses the syntax.

Using `$$` as a quote identifier instead of `'` results in terraform seeing a diff when comparing table columns that exist and not changing in the plan.  

Changing the quote identifier to `$$en-ci$$`, results in a successful `terraform apply`, but when applying any change after the success results in a diff when comparing resources that have been applied and not changed.

**Expected behavior**

When defining a column that needs COLLATION, you have to use a `'` or `$$`.  Single quotes result in terraform not able to apply, and double dollar results in terraform seeing a diff for columns that have `$$` in Terraform but `'` in Snowflake. (Snowflake converts to `'` when applied, apparently).

**Code samples and commands**
- Unsuccessful `apply`

```
resource snowflake_table dummytable {
  database = snowflake_database.odindummy.name
  schema = "STG"
  name = "DUMMYTABLE"

  column {
    name = "ID"
    type = "VARCHAR(16777216) COLLATE 'en-ci'"
  }
}
```

Results in 
```
Error: error creating table DUMMYTABLE: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 77 unexpected '\''.
│ parse error line 1 at position 85 near '39'.
│
│   with snowflake_table.dummytable,
│   on main.tf line 97, in resource "snowflake_table" "dummytable":
│   97: resource snowflake_table dummytable {
```

- Successfull `apply`

```
resource snowflake_table dummytable {
  database = snowflake_database.odindummy.name
  schema = "STG"
  name = "DUMMYTABLE"

  column {
    name = "ID"
    type = "VARCHAR(16777216) COLLATE $$en-ci$$"
  }
}
```
- On next plan not changing dummytable or anything at all
![image](https://user-images.githubusercontent.com/17893274/129966686-ea9e1463-07b3-44cc-bfc1-7b43c48a9d56.png)

**Additional context**

I am not sure if Snowflake allows changing how string identifiers are represented in `SHOW TABLES` or where that could happen in the provider module myself.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:55
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:55 UTC
Labels: bug
