### ISSUE TITLE
Improved use of snowflake_grant_account_role resource with list(string)

### ISSUE THREAD

**Issue by alvarosaavedrau** [Snowflake-Labs/terraform-provider-snowflake#2729] opened 2024-04-19 11:24 UTC
### Terraform CLI and Provider Versions

**terraform**: 1.7.5
**Snowflake provider**: 0.88.0

### Use Cases or Problem Statement

With the previous resource `snowflake_role_grants` [doc](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.88.0/docs/resources/role_grants) (now deprecated) you could assign one role to another by means of a list of strings, which made it very convenient.

Now with the new resource `snowflake_grant_account_role` [doc](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.88.0/docs/resources/grant_account_role) a string list is not allowed in the parameter **parent_role_name** and **user_name**, this makes it very complicated to use this resource in a comfortable way, neither a dynamic block can be used since it is not a block (string list).

### Proposal

It would be nice to be able to use a string list in the parameters **parent_role_name** and **user_name**.

### How much impact is this issue causing?

Medium

**Comment by sfc-gh-jcieslak** [comment] 2024-04-22 10:51
Hey @alvarosaavedrau, please take a look at this issue https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2668.

**Comment by sfc-gh-jcieslak** [comment] 2024-09-05 11:00
Closing as it's duplicate of mentioned issue.

**Closed by sfc-gh-jcieslak** 2024-09-05 11:00 UTC
Labels: category:grants
