### ISSUE TITLE
Error when executing terraform apply -refresh-only for a non existing user

### ISSUE THREAD

**Issue by israel** [Snowflake-Labs/terraform-provider-snowflake#955] opened 2022-03-30 08:07 UTC
**Provider Version**
0.29.0

**Terraform Version**
1.1.1

**Describe the bug**

Running a 'terraform apply -refresh-only' on an existing local state for a snowflake user resource while the actual user does not exist in Snowflake will result in error: 
`Error: 002003 (02000): SQL compilation error:
User '"user222"' does not exist or not authorized.` This is due to a bug in https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/f75f102f04d8587a393a6c304ea34ae8d999882d/pkg/resources/user.go#L155 and in https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/f75f102f04d8587a393a6c304ea34ae8d999882d/pkg/resources/user.go#L172
When describing a non existing user in Snowflake you get a SQL Compilation eror and not an empty result. Thus the check here https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/f75f102f04d8587a393a6c304ea34ae8d999882d/pkg/resources/user.go#L180 is wrong and the expectation for no error here https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/f75f102f04d8587a393a6c304ea34ae8d999882d/pkg/resources/user.go#L161 is wrong.
It seems that these two functions are not covered in the tests for a non existing user. 

**Expected behavior**

For non existing user, the SQL error should be expected and handled correctly.

**Code samples and commands**

To reproduce:
1. Create a new user resource using the provider.
2. update the user id in the local state file to a non existing user
3. run terraform apply -refresh-only

**Additional context**

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:47
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:47 UTC
Labels: bug
