### ISSUE TITLE
Incorrect documentation for snowflake_warehouse_grant

### ISSUE THREAD

**Issue by igorchernysh** [Snowflake-Labs/terraform-provider-snowflake#419] opened 2021-01-20 22:44 UTC
**Provider Version**

0.20.0

**Terraform Version**

v0.14.4

**Describe the bug**

Documentation says about ID format (3 fields):

\# format is warehouse name | privilege | true/false for with_grant_option
terraform import snowflake_warehouse_grant.example 'warehouseName|MODIFY|true'

**Expected behavior**

This command should work:

`terraform import 'snowflake_warehouse_grant.warehouse_grant' "QA_ENGINEER_WH|MONITOR|false"`

, but getting error instead:

```
snowflake_warehouse_grant.warehouse_grant: Import prepared!
Prepared snowflake_warehouse_grant for import
snowflake_warehouse_grant.warehouse_grant: Refreshing state... [id=QA_ENGINEER_WH|MONITOR|false]

Error: 4 or 5 fields allowed
```

**Additional context**

Specifying 5 fields (un-documented) works:
```
terraform import 'snowflake_warehouse_grant.warehouse_grant' "QA_ENGINEER_WH|||MONITOR|false"

snowflake_warehouse_grant.warehouse_grant: Importing from ID "QA_ENGINEER_WH|||MONITOR|false"...
snowflake_warehouse_grant.warehouse_grant: Import prepared!
  Prepared snowflake_warehouse_grant for import
snowflake_warehouse_grant.warehouse_grant: Refreshing state... [id=QA_ENGINEER_WH|||MONITOR|false]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

**Comment by ryanking** [comment] 2021-01-20 23:11
Can you try to reproduce in the latest release (0.22.0)? I think this might have been a regression in 0.20.0 that we reverted.

**Comment by igorchernysh** [comment] 2021-01-21 23:51
@ryanking : verified. Same behavior in 0.22.0

**Comment by kanata2** [comment] 2021-01-27 02:32
same case with #429

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:01
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:01 UTC
Labels: bug
