### ISSUE TITLE
Account level settings keeps the resource constantly updated

### ISSUE THREAD

**Issue by funes79** [Snowflake-Labs/terraform-provider-snowflake#474] opened 2021-02-25 10:40 UTC
**Provider Version**

The provider version you are using. 0.18, 0.19, 0.20 any

**Terraform Version**

The version of Terraform you were using when the bug was encountered. 0.13 and 0.14

**Describe the bug**

When a account level setting is defined on Snowflake account, the Snowflake task always gets re-created.
For example if you define ignore case and time zone for the account the the provider reads the task definition with these parameters and always tries to convert it back to the original value (empty).
```
      ~ session_parameters = {
          - "QUOTED_IDENTIFIERS_IGNORE_CASE" = "true" -> null
          - "TIMEZONE"                       = "Europe/Oslo" -> null
        }
```

The settings are the following:
```
use role accountadmin;
SHOW PARAMETERS LIKE 'TIMEZONE' 
-- key	        value	        default	                level	description	type
-- TIMEZONE	Europe/Oslo	America/Los_Angeles	ACCOUNT	time zone	STRING
SHOW PARAMETERS LIKE 'QUOTED_IDENTIFIERS_IGNORE_CASE' 
--key	                                value	default	level	description	                                        type
--QUOTED_IDENTIFIERS_IGNORE_CASE	true	false	ACCOUNT	If true, the case of quoted identifiers is ignored	BOOLEAN
```

**Expected behavior**

In ideal case the provider would be aware of these account level settings and not trigger change on every plan and apply run.

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

**Comment by funes79** [comment] 2021-02-25 10:46
@ryanking I was thinking hotfixing this here by adding a list of parameters to ignore (such as in my case timezone and quoted_identifiers_ignore_case). 

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/1a28b3710c04a6232f2e96325ca8e83082ac8a17/pkg/resources/task.go#L337

```
func stringInSlice(a string, list []string) bool {
    for _, b := range list {
        if b == a {
            return true
        }
    }
    return false
}
```

```
ignored_params:= []string{"TIMEZONE", "QUOTED_IDENTIFIERS_IGNORE_CASE"}

	if len(params) > 0 {
		paramMap := map[string]interface{}{}
		for _, param := range params {
			log.Printf("[TRACE] %+v\n", param)
			if param.Value == param.DefaultValue {
				continue
			}
                        if stringInSlice(param.Value, ignored_params) {
                                continue
                        }
			paramMap[param.Key] = param.Value
		}

		err := d.Set("session_parameters", paramMap)
		if err != nil {
			return err
		}
	}
```

But not sure about:
* if this is the right place to do the ignore
* how and where to store this configuration (what session params should be ignored)

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:00
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:00 UTC
Labels: bug
