### ISSUE TITLE
future grants should be recreated when a schema is recreated

### ISSUE THREAD

**Issue by jrobison-sb** [Snowflake-Labs/terraform-provider-snowflake#867] opened 2022-02-19 20:33 UTC
**Provider Version**

```
$ terraform version
Terraform v0.14.11
+ provider registry.terraform.io/aidanmelen/snowsql v0.2.0
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.36
```

**Describe the bug**

When a schema is changed in a way that causes the schema to be recreated, any dependent resources on that schema should also be recreated within the same plan/apply cycle. Currently they are not, and it requires two plan/apply cycles.

**Expected behavior**

When a schema is changed in a way that causes the schema to be recreated, any dependent resources on that schema should also be recreated within the same plan/apply cycle.

**Code samples and commands**

```
resource "snowflake_schema" "foo" {
  is_transient        = true
  ...
}

resource "snowflake_table_grant" "foo" {
  schema_name   = snowflake_schema.foo.name
  on_future           = true
  ...
}
```

1. Create the above infrastructure, which will be created as expected.
2. Change the schema so that `is_transient = false`.
3. Run a plan/apply, and see that the schema, and only the schema, will be recreated.
4. Look in the console and see that none of the future grants are present anymore. They should have been recreated in the above plan/apply, but they weren't.
5. Run another plan/apply and they will be created.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:49
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:49 UTC
Labels: bug
