### ISSUE TITLE
Error: 003115 (42601): SQL compilation error: Integration 'MY_INTEGRATION' is not enabled.

### ISSUE THREAD

**Issue by jtzero** [Snowflake-Labs/terraform-provider-snowflake#445] opened 2021-02-05 21:53 UTC
**Provider Version**

v0.23.2

**Terraform Version**

v0.12.29

**Describe the bug**

while running a plan with a `enabled=false` storage integration a sql compilation error occurs
this occurs even after importing the not enabled storage integration
and also occurs after removing the optional `enabled` 

**Expected behavior**

to show a plan with a diff if the integration is different than code or say everything is up to date

**Code samples and commands**

```Error: 003115 (42601): SQL compilation error: Integration 'MY_INTEGRATION' is not enabled.```

**Additional context**

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:00
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:00 UTC
Labels: bug
