### ISSUE TITLE
Invalid predecessor DB.SCHEMA."[]" was specified.

### ISSUE THREAD

**Issue by ezeql** [Snowflake-Labs/terraform-provider-snowflake#1088] opened 2022-06-29 15:05 UTC
**Provider Version**

snowflake-labs/snowflake v0.37.0

**Terraform Version**

Terraform v1.2.2

**Describe the bug**
terraform apply first time using 0.37.0 got to 
```bash
 Error: error removing old after dependency from task DATABASE|SCHEMA|TASK: 091085 (42601): Invalid predecessor DATABASE.SCHEMA."[]" was specified.
 
   with module.snowflake.snowflake_task.task,
   on ../../../modules/snowflake/tasks.tf line 1, in resource "snowflake_task" "task":
    1: resource "snowflake_task" "task {
```

**Expected behavior**

Should apply the changes correctly.

**Code samples and commands**

```terraform
resource "snowflake_task" "task" {
  database             = "DATABASE"
  name                 = "TASK"
  schema               = "SCHEMA"
  warehouse            = "WAREHOUSE"
  schedule             = "60 MINUTE"
  sql_statement        = "call merge()"
  enabled              = true
  user_task_timeout_ms = 86400000
}
```

**Additional context**

We experienced the issue described on https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1071 before the current problem.  Upgrading to 0.37.0 seemed to solve it, yet we're facing this new one.

UPDATE: It only showed once after the first `apply`.  Following plans seemed to work as expected. Will expand shortly.

**Comment by jodybuz** [comment] 2022-06-30 15:59
@ezeql We're also now seeing this problem. Hopefully gets sorted quickly. I'm sure there's some hacky way to get around it - but I've not quite figured it out yet!

**Comment by ezeql** [comment] 2022-06-30 16:03
hi @jodybuz, this issue only showed up once, the first apply after using 0.37.0. 
`terraform plan` worked correctly afterward.

**Comment by AidanHarveyNelson** [comment] 2022-07-05 03:17
I can confirm with @ezeql that this issue only occurred once after upgrading to 0.37.0. Stranger even that this issue only occured on 1 task out of 8 possible ones. Whatever changes it tried to make caused the task to become suspended.

**Comment by sfc-gh-jcieslak** [comment] 2024-11-25 09:51
Hey @ezeql 
Since 0.37.0 is a very old version, I have to close the issue. In the provider's v0.99.0 version, the tasks will be reworked and should not contain any of the reported issues and should be feature-complete (except for newly added parameters that appeared in the documentation a few days ago). In case of any problems, please create another issue (we are currently more responsive and try to fix or categorize the issues for future improvements as soon as possible)

**Closed by sfc-gh-jcieslak** 2024-11-25 09:51 UTC
Labels: bug, resource:task, category:resource
