### ISSUE TITLE
snowflake_share doesn't fetch correctly the accounts linked to a share when more than 3 shares

### ISSUE THREAD

**Issue by philkpler** [Snowflake-Labs/terraform-provider-snowflake#1066] opened 2022-06-20 09:32 UTC
**Provider Version**
0.25.34

**Terraform Version**
1.0.3

**Describe the bug**

snowflake_share doesn't fetch correctly the accounts linked to a share when more than 3 shares

ie : 

I have a share "my_share" with 4 accounts (ACCOUNT_1, ACCOUNT_2, ACCOUNT_3, ACCOUNT_4)

```
terraform state show snowflake_share.my_share
```
will return something like
```
resource "snowflake_share" "my_share" {
    accounts = [
        "ACCOUNT_1",
        "ACCOUNT_2",
        "ACCOUNT_3",
        "... (4 TOTAL)",
    ]
...
}
```
Here we can see that the 4th account is not displayed, instead of the id we have a `...(4 TOTAL)` string

**Expected behavior**

I expect the output to be something like 

```
resource "snowflake_share" "my_share" {
    accounts = [
        "ACCOUNT_1",
        "ACCOUNT_2",
        "ACCOUNT_3",
        "ACCOUNT_4",
    ]
...
}
```

**Code samples and commands**

see previous sections

**Additional context**

In addition to the miss leading output, I think it can have some bad impacts in the synchronization between the terraform state and the 'real' state of snowflake...

The issue might come from the usage of the column `to`, displayed in the output of the `show shares` snowflake command.
I had a reply from Snowflake team concerning that

> The behavior that you encounter where the 4th (or greater) account in a share's "to" field is not shown is actually a product limitation at the moment, and thus, it is expected behavior. This behavior is documented in the following article:
> https://docs.snowflake.com/en/sql-reference/sql/show-shares.html
> "The maximum number of accounts displayed in this column is three; however, there is no hard limit on the number of accounts that can be added to a share."

It's possible to get all the accounts from the UI 
ie : in the snowsight UI, `Data -> Private Sharings -> Shared By My Account`, then clicking on a share will list all the account
But for now, I don't know how to access that list in SQL, with snowflake's commands.

**Comment by philkpler** [comment] 2023-01-12 10:22
Hi, any update on that ?

**Comment by emancu** [comment] 2023-08-26 00:47
Me too, I'm having the same issue and I'm running `0.70.0`

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:45
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:45 UTC
Labels: bug
