### ISSUE TITLE
snowflake_view_grant - 'Objects have changed outside of Terraform' detected when no change occured.

### ISSUE THREAD

**Issue by deragon** [Snowflake-Labs/terraform-provider-snowflake#749] opened 2021-11-07 17:32 UTC
**Provider Version**

0.25.24 (latest)

**Terraform Version**

Terraform v1.0.10 (latest)

**Describe the bug**

Systematically get the following error when executing `terraform.exe apply -var-file="vars.tfvars"` again and again as soon as possible.  The problem occurs with `snowflake_view_grant`.

    Note: Objects have changed outside of Terraform

    Terraform detected the following changes made outside of Terraform since the last "terraform apply":

      # snowflake_view_grant.grant has been changed
      ~ resource "snowflake_view_grant" "grant" {
            id                = "TEST_DB_HANS|TEST_SCHEMA_HANS|TEST_VIEW_HANS|select|false"
          ~ roles             = [
              - "TERRAFORM_TEST_1_HANS",
            ]
            # (7 unchanged attributes hidden)
        }

**Expected behavior**

No change to be detected, nothing to update.

**Code samples and commands**

Download:

[chanzuckerberg-snowflake-issue-#749.zip](https://github.com/chanzuckerberg/terraform-provider-snowflake/files/7492787/chanzuckerberg-snowflake-issue-.749.zip)

Change to the directory, edit `variables.tf` and then execute `terraform.exe apply` multiple times.

**Comment by deragon** [comment] 2021-11-07 17:49
Maybe or maybe not related to issue #733.

**Comment by kvarnier** [comment] 2021-11-11 13:38
You have to write your select privilege in uppercase when you declare your resource snowflake_view_grant. 

`resource snowflake_view_grant test_view_grant_chanzuckerberg-snowflake-issue-749 {
  provider          = snowflake.securityadmin
  database_name     = "TEST_DB_CHANZUCKERBERG-SNOWFLAKE-ISSUE-749"
  schema_name       = "TEST_SCHEMA_CHANZUCKERBERG-SNOWFLAKE-ISSUE-749"
  view_name         = "TEST_VIEW_CHANZUCKERBERG-SNOWFLAKE-ISSUE-749"

  privilege         = "select"   # ------> SELECT 
  roles             = [ "TERRAFORM_TEST_CHANZUCKERBERG-SNOWFLAKE-ISSUE-749" ]

  with_grant_option = false

  depends_on = [
    snowflake_view.test_view_chanzuckerberg-snowflake-issue-749
  ]`

I get a similar issue with the resource grant on store procedure.  I write my argument type like: `varchar`, but Snowflake probably convert or read  it in `VARCHAR`. After my initial deployment, I was not able to update it and get this error message :

```

      ~ arguments {
            name = "ARG1"
          ~ type = "VARCHAR" -> "varchar"
        }
      ~ arguments {
            name = "ARG2"
          ~ type = "VARCHAR" -> "varchar"
        }
    }
2021-11-09T16:54:33.8812646Z 
Plan: 0 to add, 2 to change, 0 to destroy.
snowflake_procedure_grant.grant_procedure: Modifying... 
Error: doesn't support update
```

Probably need an uppercase() for all "Snowflake keyword" in the grants module
Also the documentation need to be updated with uppercase on type field : 
https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/view_grant
https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/procedure_grant

**Comment by deragon** [comment] 2021-11-15 15:24
Great find @kvarnier.  I concur, a uppercase() for all "Snowflake keyword" in the grants module (and probably other modules) is needed.  The Snowflake provider should take care of this automatically.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:52
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:52 UTC
Labels: bug
