### ISSUE TITLE
Snowpipe Creation Error ("Integration" field for Azure) should be required.

### ISSUE THREAD

**Issue by MavrickRody** [Snowflake-Labs/terraform-provider-snowflake#810] opened 2022-01-09 20:54 UTC
Guys for Azure Integration - Snowpipe

"**Integration**" should be a required field otherwise the creation of snowpipe fails.

**Comment by andreasportelliinfinity** [comment] 2022-02-10 14:33
@MavrickRody I have been having issues using snowpipe with Azure. This is my template:
```
resource "snowflake_pipe" "pipe" {
  provider = snowflake.sys_admin
  integration = "myintegration"
  database = "mydb"
  schema   = "PUBLIC"
  name     = "mypipe"

  comment = "A pipe."


  copy_statement = "copy into \"db\".\"schema\".\"table\" from (select $1,$2,$3,$4,$5, $6, $7, $8, $9, $10, metadata$filename, metadata$file_row_number, current_timestamp  from   @db.PUBLIC.stage (file_format => TEST.PUBLIC.CSV))"
  auto_ingest    = true

}
```
when I run it I get: ```An argument named "integration" is not expected here.```

if I remove integration I get: ``` Pipe Notifications bind failure "Integration cannot be null for Azure.```

have you got around to making this work?
thanks

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:50
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:50 UTC
Labels: bug
