### ISSUE TITLE
okta auth

### ISSUE THREAD

**Issue by ryanking** [Snowflake-Labs/terraform-provider-snowflake#37] opened 2019-06-12 18:13 UTC

**Comment by mhaley-miovision** [comment] 2020-05-08 11:26
In general snowflake provides the ability to use oauth tokens to authenticate when using command line tools or even connectors within programs.  We should support the ability to provide an oauth token as a form of authentication.

**Comment by ataki** [comment] 2020-06-07 19:57
@mhaley-miovision we have a potential use case for oauth access tokens - I just put out a PR for this. It's limited in scope since it requires you to have a valid, non-expired access token, but might satisfy your command line tool use case

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:03
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:03 UTC
Labels: feature-request
