### ISSUE TITLE
Support for CREATE / ALTER CONNECTION

### ISSUE THREAD

**Issue by rd-thomas-uhren** [Snowflake-Labs/terraform-provider-snowflake#965] opened 2022-04-07 09:21 UTC
We would like to manage connections for Client Redirect with the Snowflake Terraform Provider to avoid manual ressource management.

Here are the docs:

https://docs.snowflake.com/en/sql-reference/sql/create-connection.html

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:47
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:47 UTC
Labels: feature-request
