### ISSUE TITLE
Undocumented state drift blindness in network_policy_attachment

### ISSUE THREAD

**Issue by tabletcorry** [Snowflake-Labs/terraform-provider-snowflake#802] opened 2021-12-29 19:45 UTC
**Provider Version**

v0.25.19

**Terraform Version**

v1.0.5

**Describe the bug**

The code for network policy attachment states that it is unable to read the true state, which is not reflected in the documentation. As such, users may not realize that this resource is blind to drift.

https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/network_policy_attachment.go#L77

If this is still impossible to resolve, the documentation should have a very large warning that this resource is unable to observe drift, which is especially critical for a primary security control.

Currently no warning is present on https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/resources/network_policy_attachment

**Expected behavior**

Changes made to network policies in Snowflake would be corrected by later `terraform apply`.

**Code samples and commands**

Make any change in Snowflake to network policy attachments. Terraform is blind to them.

**Comment by lewdawson** [comment] 2022-05-24 23:17
Also seeing this. If we do a:

```sql
ALTER USER <user-name> UNSET network_policy;
```

After applying the network policy attachment, terraform says _No Changes_.

Thoughts on fixing this?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:50
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:50 UTC
Labels: bug
