### ISSUE TITLE
This is a bug in the provider, which should be reported in the provider's own issue tracker.

### ISSUE THREAD

**Issue by KrishnaVishwakarma27101999** [Snowflake-Labs/terraform-provider-snowflake#2572] opened 2024-02-29 06:39 UTC
### Terraform CLI and Provider Versions

Version : 
- provider registry.terraform.io/snowflake-labs/snowflake v0.87.0
- Terraform v1.7.4

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.76"

    }
  }
}


provider "snowflake" {
 # the Snowflake account identifier
}

resource "snowflake_database" "db" {
  name = "new_database_ts"

}
```

### Expected Behavior

Should create Database in snowflake and generate .Tfstate file

### Actual Behavior

(base) krishna@krishnas-MacBook-Air Snowflake-terraform % terraform apply    

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # snowflake_database.db will be created
  + resource "snowflake_database" "db" {
      + data_retention_time_in_days = -1
      + id                          = (known after apply)
      + is_transient                = false
      + name                        = "new_database_ts"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

snowflake_database.db: Creating...

Error: Provider produced inconsistent result after apply
 
When applying changes to snowflake_database.db, provider
"provider[\"registry.terraform.io/snowflake-labs/snowflake\"]" produced an
unexpected new value: Root object was present, but now absent.
 
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Logs

https://gist.github.com/KrishnaVishwakarma27101999/847298582d087ee5d165b5a58cecd4cf

### Additional Information

after terraform apply run .The database gets created in snowflake but tfstate file is not updating the current state. 

terraform.tfstate
{
  "version": 4,
  "terraform_version": "1.7.4",
  "serial": 6,
  "lineage": "91a31be1-6cc9-e8e4-7be1-c0a4128585a0",
  "outputs": {},
  "resources": [],
  "check_results": null
}

**Comment by sfc-gh-jcieslak** [comment] 2024-02-29 10:19
Hey @KrishnaVishwakarma27101999 👋 
It looks like the plugin created a database, but then couldn't retrieve it after it was created. Terraform essentially ran:
```sql
CREATE DATABASE "new_database_ts";
SHOW DATABASES LIKE 'new_database_ts';
```
Could you try to manually run those with the Terraform account and see if the database is returned by SHOW command?
We couldn't reproduce the error on our side, so could you provide the exact steps on how to reproduce this issue?

**Comment by KrishnaVishwakarma27101999** [comment] 2024-02-29 11:01
I am new to terraform 
Its very difficult to explain. If you want, I can share the snowflake dummy account details where I was testing the Terraform.

<img width="566" alt="Screenshot 2024-02-29 at 4 24 10 PM" src="https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/54256061/05d69985-7733-4509-abd5-6aec0d9e1f9b">

main.tf

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.76"

    }
  }
}


provider "snowflake" {
# the Snowflake account identifier

}

resource "snowflake_database" "db" {
  name = "new_database_ts"

}

data "snowflake_databases" "this" {

}


output "password" {
  sensitive = true
  value     = data.snowflake_databases.this
}


tfstate file.
{
  "version": 4,
  "terraform_version": "1.7.4",
  "serial": 16,
  "lineage": "91a31be1-6cc9-e8e4-7be1-c0a4128585a0",
  "outputs": {
    "password": {
      "value": {
        "databases": [
          {
            "comment": "",
            "created_on": "2024-02-29 06:44:09.403 +0000 UTC",
            "is_current": false,
            "is_default": false,
            "name": "NEW_DATABASE_TS",
            "options": "",
            "origin": "",
            "owner": "ACCOUNTADMIN",
            "replication_configuration": [],
            "retention_time": 1
          },
          {
            "comment": "",
            "created_on": "2024-02-14 11:07:05.669 +0000 UTC",
            "is_current": false,
            "is_default": false,
            "name": "SNOWFLAKE",
            "options": "",
            "origin": "SNOWFLAKE.ACCOUNT_USAGE",
            "owner": "",
            "replication_configuration": [],
            "retention_time": 0
          },
          {
            "comment": "Provided by Snowflake during account provisioning",
            "created_on": "2024-02-14 11:07:09.857 +0000 UTC",
            "is_current": false,
            "is_default": false,
            "name": "SNOWFLAKE_SAMPLE_DATA",
            "options": "",
            "origin": "SFSALESSHARED.SFC_SAMPLES_AWS_AP_SOUTH_1.SAMPLE_DATA",
            "owner": "ACCOUNTADMIN",
            "replication_configuration": [],
            "retention_time": 0
          }
        ],
        "history": false,
        "id": "databases_read",
        "pattern": null,
        "starts_with": null,
        "terse": false
      },
      "type": [
        "object",
        {
          "databases": [
            "list",
            [
              "object",
              {
                "comment": "string",
                "created_on": "string",
                "is_current": "bool",
                "is_default": "bool",
                "name": "string",
                "options": "string",
                "origin": "string",
                "owner": "string",
                "replication_configuration": [
                  "list",
                  [
                    "object",
                    {
                      "accounts": [
                        "list",
                        "string"
                      ],
                      "ignore_edition_check": "bool"
                    }
                  ]
                ],
                "retention_time": "number"
              }
            ]
          ],
          "history": "bool",
          "id": "string",
          "pattern": "string",
          "starts_with": "string",
          "terse": "bool"
        }
      ],
      "sensitive": true
    }
  },
  "resources": [
    {
      "mode": "data",
      "type": "snowflake_databases",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/snowflake-labs/snowflake\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "databases": [
              {
                "comment": "",
                "created_on": "2024-02-29 06:44:09.403 +0000 UTC",
                "is_current": false,
                "is_default": false,
                "name": "NEW_DATABASE_TS",
                "options": "",
                "origin": "",
                "owner": "ACCOUNTADMIN",
                "replication_configuration": [],
                "retention_time": 1
              },
              {
                "comment": "",
                "created_on": "2024-02-14 11:07:05.669 +0000 UTC",
                "is_current": false,
                "is_default": false,
                "name": "SNOWFLAKE",
                "options": "",
                "origin": "SNOWFLAKE.ACCOUNT_USAGE",
                "owner": "",
                "replication_configuration": [],
                "retention_time": 0
              },
              {
                "comment": "Provided by Snowflake during account provisioning",
                "created_on": "2024-02-14 11:07:09.857 +0000 UTC",
                "is_current": false,
                "is_default": false,
                "name": "SNOWFLAKE_SAMPLE_DATA",
                "options": "",
                "origin": "SFSALESSHARED.SFC_SAMPLES_AWS_AP_SOUTH_1.SAMPLE_DATA",
                "owner": "ACCOUNTADMIN",
                "replication_configuration": [],
                "retention_time": 0
              }
            ],
            "history": false,
            "id": "databases_read",
            "pattern": null,
            "starts_with": null,
            "terse": false
          },
          "sensitive_attributes": []
        }
      ]
    }
  ],
  "check_results": null
}

**Comment by sfc-gh-jcieslak** [comment] 2024-02-29 11:58
@KrishnaVishwakarma27101999 If you ran those commands manually
```sql
CREATE DATABASE "new_database_ts";
SHOW DATABASES LIKE 'new_database_ts';
```
It means you created the database in Snowflake and Terraform won't know about the existence of this database and will throw an error that `Object "new_database_ts" already exists`, because it wants to create one but it already exists. To come back to the previous state of Snowflake remove the manually created database with:
```sql
DROP DATABASE "new_database_ts";
```
After that you shouldn't get the `already exists` error when running `terraform plan` or `terraform apply`, but you should see the original one. 

I don't think there's anything wrong with the Snowflake provider when executing the config you posted:
```terraform
resource "snowflake_database" "db" {
  name = "new_database_ts"
}
```
We tested this example in different ways, but couldn't get the error you've got. Unfortunately, we cannot help without being able to reproduce your error. As far as I can tell from the logs you provided, It seems like the database got created and SHOW DATABASE was run, but no database was found for some reason. As I proposed I can recommend you running this:
```sql
CREATE DATABASE "new_database_ts";
SHOW DATABASES LIKE 'new_database_ts';
```
and please post the result of SHOW DATABASES command. Important thing is to use the same account you're using for Terraform so it will have the same privileges.

**Comment by KrishnaVishwakarma27101999** [comment] 2024-03-01 09:12
Hi is there any chance we can connect over the meet

**Comment by sfc-gh-jcieslak** [comment] 2024-03-05 07:39
Hey @KrishnaVishwakarma27101999 👋 
Please contact your account team at Snowflake for the quickest response. The Product and Engineering teams are available for issues that cannot be resolved by the account team and documentation.

**Comment by sfc-gh-jcieslak** [comment] 2024-04-09 09:09
Closing due to long inactivity, please create another issue if the problem persists

**Closed by sfc-gh-jcieslak** 2024-04-09 09:09 UTC
Labels: bug
