### ISSUE TITLE
Error message: Actual statement count 2 did not match the desired statement count 1

### ISSUE THREAD

**Issue by aroder** [Snowflake-Labs/terraform-provider-snowflake#648] opened 2021-08-17 11:34 UTC
**Provider Version**

The provider version you are using.
```
provider registry.terraform.io/chanzuckerberg/snowflake v0.22.0
```

**Terraform Version**

The version of Terraform you were using when the bug was encountered.
```
Terraform v1.0.0
```

**Describe the bug**

I have created a basic setup with some users, roles, and grants. When I try to remove them by changing their count to 0 and running `terraform apply`, I get the error message 

```
Error: 000008 (0A000): Actual statement count 2 did not match the desired statement count 1
```

**Expected behavior**

I expect the resources to be deleted.

**Code samples and commands**
The main.tf has a block that adds my snowflake module:

```
module "snowflake_instance" {
  source = "./modules/snowflake_instance"
  count = var.enable_snowflake_instance ? 1 : 0
  reader_users = var.reader_users
}
```

where `reader_users` is defined as
```
variable "reader_users" {
    type = set(string)
    default = []
}
```

with a value of
```
reader_users = ["jsmith"]
```

The snowflake module adds users, roles and grants such as the following:
```
resource snowflake_user reader_users {
  for_each = var.reader_users
  name = each.value
  comment = "A user with access to read the public schema in the dw database"
}
resource snowflake_role_grants reader_users_role_grants {
  for_each = var.reader_users
  role_name = snowflake_role.reporter.name
  users = [each.value]
}```

**Additional context**

Add any other context about the problem here.

**Comment by aroder** [comment] 2021-08-17 12:12
I can reproduce this issue anytime I change the list of roles in a grant. It appears that this forces a replacement, or a drop and then a create. This corroborates the message that there are 2 statements attempting to execute. I don't know if this is useful, but here is an example error message in this case:

![image](https://user-images.githubusercontent.com/23650/129723425-254707d9-894d-4a58-9f68-b9223d712427.png)

**Comment by abdoulsn** [comment] 2022-06-28 12:52
Having this issue while deployment on Snowflake using liquibase? Any solution?

**Comment by praveenkandasamy** [comment] 2022-12-05 11:27
Hi had this issue on Power bi while running a query on snowflake. Checked out the query history and there the error was highlighted with further details there

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:55
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:55 UTC
Labels: bug

**Comment by frankschmitt** [comment] 2024-11-21 13:11
> Having this issue while deployment on Snowflake using liquibase? Any solution?

We ran into the same issue with Snowflake / Liquibase. For us, the solution was to include the Liquibase-specific changeset markes in the SQL file. So instead of

`
create stage schema1.stage1 DIRECTORY = (ENABLE = TRUE);
put  file://${CI_PROJECT_DIR}/lib/jar/gson-2.10.1.jar @schema1.stage1 auto_compress=false;
`

we now have

`
--liquibase formatted sql

--changeset user:1
create stage schema1.stage1 DIRECTORY = (ENABLE = TRUE);
--rollback none;

--changeset user:2
put  file://${CI_PROJECT_DIR}/lib/jar/gson-2.10.1.jar @schema1.stage1 auto_compress=false;
--rollback empty;
`

and apparently, Liquibase is now executing each statement separately.
