### ISSUE TITLE
SNOWFLAKE STORED PROCEDURE GRANTS/PERMISSION ARE GETTING REMOVED WHENEVER STORED PROCEDURE IS GETTING UPDATED

### ISSUE THREAD

**Issue by kvenugopal** [Snowflake-Labs/terraform-provider-snowflake#998] opened 2022-05-06 19:26 UTC
**Provider Version**

chanzuckerberg/snowflake v0.33.1

**Terraform Version**

terraform/0.14.8

**Describe the bug**

We are deploying stored procedure using "snowflake_procedure" resource and the permission/grants is provided through "snowflake_procedure_grant" resource. Any time we make a change to procedure and deploy the permissions/grants are getting removed as the procedure is dropped and recreated(new version). However the grants are not getting applied.  So as a work around we apply the change one more time and now the terraform generates the plan to apply the procedure grants

**Expected behavior**

When procedure undergoes change the grants mentioned should be reapplied.

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:46
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:46 UTC
Labels: bug
