### ISSUE TITLE
`snowflake_role` should be defined as `data`and not only `resource`

### ISSUE THREAD

**Issue by thomasschaller1** [Snowflake-Labs/terraform-provider-snowflake#566] opened 2021-06-10 09:51 UTC
**Is your feature request related to a problem? Please describe.**

Yet, this is not possible to define a `snowflake_role` as `data`, so we cannot define existing role such as `SYSADMIN`. This can be useful to grant parent role of new role to an existing role.

The goal is to be able to do something like that:
```
resource "snowflake_role_grants" "grants_sysadmin_loader" {
  role_name = "${snowflake_role.loader.name}"

  roles = [
    "${data.snowflake_role.sysadmin.name}",
  ]
}
```

**Describe the solution you'd like**

Be able to define `snowflake_role` as `data` and not only `resource`. So instead of that (this will not work because `SYSADMIN` already exists): 
```
resource "snowflake_role" "sysadmin" {
  name = "SYSADMIN"
}
```
We should be able to do that:
```
data "snowflake_role" "sysadmin" {
  name = "SYSADMIN"
}
```

**Comment by fonsecalink** [comment] 2021-06-11 13:27
You can [import](https://www.terraform.io/docs/cli/commands/import.html) existing roles into a resource.

**Comment by solak647** [comment] 2021-06-14 13:20
Hi @fonsecalink, thanks for you response.

Can you explain a bit more how to do it automatically using `.tf` files? Import is a cli command no?

**Comment by solak647** [comment] 2021-06-14 13:31
@fonsecalink Thanks it works !

**Comment by solak647** [comment] 2021-06-15 10:27
Reopening this issue. Import is working fine, but then when doing the destroy, it will try to remove the `SYSADMIN` role, which is not possible.

**Comment by alldoami** [comment] 2021-06-15 21:06
What are you trying to destroy that removes the `SYSADMIN` role?

**Comment by solak647** [comment] 2021-06-16 06:10
@alldoami the whole workspace. `terraform destroy`. This is not a big problem, because except the error message in the console, the process succeeds at the end. So that's fine, but it would be better to be able to use `data` instead of import. Because `import` will then manage the resource, which we don't want for the `SYSADMIN` role, because it is a base role on snowflake that should not change.

**Comment by fonsecalink** [comment] 2021-06-16 10:10
Yes, that is a workaround. You can attach a [`prevent_destroy`](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#prevent_destroy)

**Comment by solak647** [comment] 2021-06-21 09:01
@fonsecalink I want to destroy everything except this snowflake role which is a default role. The `prevent_destroy` stuff will just rejected the destroy, but will not do what I want to do (which is destroy everything on `terraform destroy` except the `SYSADMIN` role on snowflake)

**Comment by HughZurname** [comment] 2021-07-02 13:09
@fonsecalink Using `prevent_destroy` or hitting the error @solak647 mentioned is an issue if the destroy on the workspace happens to try and destroy snowflake first. This is because in either scenario it causes the process to exit and will leave any resources that would have been destroyed afterwards behind. The only way round this is to remove the imported `SYSADMIN` from state prior to running the destroy.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:57
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:57 UTC
Labels: feature-request
