### ISSUE TITLE
add `data source` "current_role"

### ISSUE THREAD

**Issue by hkak03key** [Snowflake-Labs/terraform-provider-snowflake#684] opened 2021-09-15 16:40 UTC
### Is your feature request related to a problem? Please describe.
Now, I have 2 roles ( ACCCOUNTADMIN, SOME_ROLE in this time) and use both as follow:

```
provider "snowflake" {
  alias = "accountadmin"
  role  = "ACCOUNTADMIN"
  ...
}

provider "snowflake" {
  alias = "some_role"
  role  = "SOME_ROLE"
  ...
}
```

And I'll `GRANT OWNERSHIP` resource monitor to SOME_ROLE.
I want to write as follow:
```
resource "snowflake_resource_monitor" "this" {
  provider = snowflake.accountadmin
  ...
}

data "snowflake_current_role" "this" {
  provider = snowflake.some_role
}

resource "snowflake_monitor_grant" "this" {
  provider = snowflake.accountadmin

  monitor_name = snowflake_resource_monitor.this.name

  privilege = "OWNERSHIP"
  roles     = [data.snowflake_current_role.this.role]

  with_grant_option = false
}
```

### Describe the solution you'd like
Create `data "snowflake_current_role"` .
This is wrapper of `CURRENT_ROLE()` and get role name with `data.snowflake_current_role.hoge.name` .

#### specify role name directly
Of course, we can write as follow:
```
resource "snowflake_monitor_grant" "this" {
  provider = snowflake.accountadmin

  monitor_name = snowflake_resource_monitor.this.name

  privilege = "OWNERSHIP"
  roles     = ["SOME_ROLE"]

  with_grant_option = false
}
```
But in this code, user is required to know role name.
In my case, this code will be used in module so it's possible not to know role name.

### Additional context
I came up with this solution when see [current_account](https://registry.terraform.io/providers/chanzuckerberg/snowflake/latest/docs/data-sources/current_account) .

Or, there is also a strategy to create common `data source` for getting values using `CURRENT_*()` functions.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:54
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:54 UTC
Labels: feature-request
