### ISSUE TITLE
snowflake_role_grants failures should error with Grant not executed: Insufficient privileges.

### ISSUE THREAD

**Issue by tekumara** [Snowflake-Labs/terraform-provider-snowflake#737] opened 2021-10-27 12:15 UTC
**Provider Version**

0.25.23

**Terraform Version**

1.0.9

**Describe the bug**
```
resource "snowflake_role" "prod_jaffles_admin" {
  provider = snowflake.SECURITYADMIN
  name     = "PROD_JAFFLES_ADMIN"
}

resource "snowflake_role_grants" "prod_jaffles_admin" {
  # default provider is snowflake.SYSADMIN
  role_name = snowflake_role.prod_jaffles_admin.name

  roles = [
    "SYSADMIN",
  ]

  users = []
}
```

will always be recreated on every apply:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # snowflake_role_grants.prod_jaffles_admin has been changed
  ~ resource "snowflake_role_grants" "prod_jaffles_admin" {
        id        = "PROD_JAFFLES_ADMIN"
      ~ roles     = [
          - "SYSADMIN",
        ]
        # (2 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to
undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # snowflake_role_grants.prod_jaffles_admin will be updated in-place
  ~ resource "snowflake_role_grants" "prod_jaffles_admin" {
        id        = "PROD_JAFFLES_ADMIN"
      ~ roles     = [
          + "SYSADMIN",
        ]
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Expected behavior**

Because SYSADMIN does not have sufficient privileges to apply the grant, we should receive a failure message, eg:

```
Grant not executed: Insufficient privileges.
```

**Comment by tampajohn** [comment] 2021-11-05 14:31
While I agree with this, I believe the underlying issue is that snowflake itself treats this as a success.  To replicate the issue, run the following SQL on a vanilla snowflake account:

```sql
use role sysadmin;
grant create user to role sysadmin;
```

you'll notice the query is treated as a success, although the output indicates a failure (you can view it in query history and see this)

While I know this has been a known issue at snowflake for a few months at least, I'm not sure if they're planning on fixing it...

**Comment by krishbox** [comment] 2021-11-15 02:37
We'll let our Snowflake representative know to look into this and see if they can change it to an error condition if a permission is not granted.  Maybe there's a reason why it is this way in Snowflake.

**Comment by jas-grover** [comment] 2021-11-25 21:58
An update from Snowflake support 🎉 
> There is a fix that is tentatively planned for release sometime in the middle of the month of Jan 2022.

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:53
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:53 UTC
Labels: bug
