### ISSUE TITLE
Importing snowflake_database_grant

### ISSUE THREAD

**Issue by jholkGL** [Snowflake-Labs/terraform-provider-snowflake#225] opened 2020-07-23 16:41 UTC
Trying to import existing grants on a database called DB_NAME:
```
terraform import -var-file=../environments/prod.tfvars -provider=snowflake snowflake_database_grant.db_name_grant "DB_NAME"
snowflake_database_grant.db_name_grant: Importing from ID "DB_NAME"...
snowflake_database_grant.db_name_grant: Import prepared!
  Prepared snowflake_database_grant for import
snowflake_database_grant.db_name_grant: Refreshing state... [id=DB_NAME]

Error: 4 fields allowed
```
Looks like the error happens in the call to grantIDFromString here: https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/master/pkg/resources/database_grant.go#L91

The format it's expecting is "resourceName|schemaName|ObjectName|Privilege".  How would that correspond to the `snowflake_database_grant` resource?  

I tried leaving the other fields blank like "DB_NAME|||".  And the import was successful, but I ended up with this in my state:
```
# snowflake_database_grant.db_name_grant:
resource "snowflake_database_grant" "db_name_grant" {
    database_name = "DB_NAME"
    id            = "DB_NAME|||"
    roles         = []
    shares        = []
}
```
So with just the database name, it doesn't ready any existing grants.  

What would be the strategy for importing all the existing grants for a database?  Would it involve running `import` once for each grant?  What about grants that don't have a schemaName and/or ObjectName? For example, `GRANT USAGE ON DATABASE TO [role]`

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:04
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:04 UTC
Labels: bug
