### ISSUE TITLE
Feature Request: to be able to modify a grant without re-creating it

### ISSUE THREAD

**Issue by pwnage101** [Snowflake-Labs/terraform-provider-snowflake#137] opened 2020-02-10 15:27 UTC
The ability to modify grants (database grants, schema grants, warehouse grants etc.) without completely re-creating them.

Motivation: As our Snowflake userbase grows, more people (and automation users) are running queries at any given time.  More and more often, people complain that they don't have permission to access certain resources that they should have access to.  This is typically caused by the temporarily loss of some grants while we are applying a terraform plan due to grant resources that have `ForceNew` enabled on the roles list.

Via the Snowflake web UI, I believe it is technically possible to modify individual grants to users/roles without affecting other users/roles which share that same grant object.

**Comment by ryanking** [comment] 2020-02-10 17:20
@pwnage101 Yeah that sounds painful.

I spent some time looking through the [snowflake docs](https://docs.snowflake.net/manuals/sql-reference/sql-all.html) and can't figure out how one would do this. Is is possible that the snowflake web ui is doing as revoke followed by a grant?

**Comment by pwnage101** [comment] 2020-02-10 18:09
Perhaps introducing the Web UI into the conversation was confusing---lets just talk about just pure snow-SQL.  For instance, I can grant to a bunch of roles:
```sql
GRANT USAGE ON SCHEMA myschema TO ROLE role1;
GRANT USAGE ON SCHEMA myschema TO ROLE role2;
```
Then, later I can grant the same permissions to another role:
```sql
GRANT USAGE ON SCHEMA myschema TO ROLE role3;
```
The last statement does not revoke (even temporarily) usage on myschema to role1 or role2.  However, If I were to do the last step via terraform, I'd get a diff that looked something like this:
```diff
  # snowflake_schema_grant.foo must be replaced
-/+ resource "snowflake_schema_grant" "foo" {
        database_name = "BAR"
      ~ id            = "BAR|||USAGE" -> (known after apply)
        privilege     = "USAGE"
      ~ roles         = [ # forces replacement
            "ROLE1",
            "ROLE2",
          + "ROLE3",
        ]
      - shares        = [] -> null
    }
```
role1 and role2 would have their permissions interrupted by the apply.

**Comment by ryanking** [comment] 2020-02-10 19:31
@pwnage101 got it and that makes sense and seems like something that could be implemented.

**Comment by jstachowiak** [comment] 2020-07-05 20:25
@ryanking, any idea how we could go about implementing this?

**Comment by md5** [comment] 2021-04-19 21:20
@igungor @edulop91 @alldoami Is there remaining work to be done for this issue? It seems that `database`, `table`, `view`, `warehouse`, `schema`, and `role` grants have been addressed, but perhaps not `stream` or `stage` grants?

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 17:03
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 17:03 UTC
Labels: feature-request
