### ISSUE TITLE
Grant ownership on database role

### ISSUE THREAD

**Issue by pauldraper** [Snowflake-Labs/terraform-provider-snowflake#2611] opened 2024-03-11 15:05 UTC
### Terraform CLI and Provider Versions

Terraform v1.5.7
on darwin_arm64

### Terraform Configuration

```terraform
snowflake_database_role_ownership_grant "example" {
  on_database_role_name: "EXAMPLE_DB.EXAMPLE_DB_ROLE"
  to_role_name: "EXAMPLE_ACCOUNT_ROLE"
}
```

### Expected Behavior

It worked

### Actual Behavior

snowflake_database_role_ownership_grant doesn't exist 

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Additional Information

I've tried every other incantation I can think of.

I can *create* database roles, I can *grant* database roles, I can *grant privileges* to database roles, but I cannot grant ownership.

**Comment by sfc-gh-asawicki** [comment] 2024-03-11 15:36
Hey @pauldraper.

The answer is almost the same as in the previous issue you are participating in: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2610#issuecomment-1988029679. In short: we are introducing grant ownership resource in #2604 (and probably 1-2 more PRs after that). It is a part of https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#redesigning-grants communicated almost two months ago.

Also, it is possible to run any SQL statement by using https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/unsafe_execute. This is a dangerous resource, though, so I would advise waiting for the grant ownership.

**Comment by pauldraper** [comment] 2024-03-13 02:51
@sfc-gh-asawicki , no #2610 is about `snowflake_database_grant`, `snowflake_stream_grant`, etc being deprecated without suitable replacements.

This issue is that database role ownership is completely unsupported, even ignoring deprecated resource.

Thanks for suggesting `unsafe_execute`. The primary problem with that resource is that it offers no drift detection like other Terraform resources.

**Comment by sfc-gh-asawicki** [comment] 2024-03-13 10:03
> @sfc-gh-asawicki , no https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2610 is about snowflake_database_grant, snowflake_stream_grant, etc being deprecated without suitable replacements.

Well... It's about `grant_privileges_to_account_role Unsupported privilege 'OWNERSHIP'`. It's also true for the `grant_privileges_to_database_role` if you use it with the `OWNERSHIP` privilege. Database roles were not supported earlier, so there was no old dedicated ownership resource then.

>This issue is that database role ownership is completely unsupported, even if using deprecated resources.

There are workarounds. Also, in such cases (missing features) please create the feature-request and not a bug ticket.

> Thanks for suggesting unsafe_execute. The primary problem with that resource is that it offers no drift detection like other Terraform resources.

It's not meant to be a fully-fledged terraform resource. It's a workaround for the urgent needs when the feature is not yet supported.

**Comment by sfc-gh-jcieslak** [comment] 2024-04-09 15:38
Hey 👋
Closing, as the issue was about the deprecated/not allowed functionality. Recently, we released [a new grant resource](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/grant_ownership) which is capable of granting ownership. Please, give it a try. If there will be any issues with it, create another GitHub issue. Also, please check our [technical documentation section](https://github.com/Snowflake-Labs/terraform-provider-snowflake/tree/main/docs/technical-documentation) where you can find a migration guide that can help you with upgrading to the latest grant resources and our newly added design decision doc (regarding new grant resources).

**Closed by sfc-gh-jcieslak** 2024-04-09 15:38 UTC
Labels: general-usage

**Comment by pauldraper** [comment] 2024-04-09 22:30
> Also, in such cases (missing features) please create the feature-request and not a bug ticket.

FWIW feature (grant ownership on db role) was not missing, but it was deprecated without replacement.
