### ISSUE TITLE
Snowflake provider 0.84 - Unable to instantiate schema / failed to read provider configuration schema

### ISSUE THREAD

**Issue by vthelu** [Snowflake-Labs/terraform-provider-snowflake#2384] opened 2024-01-19 23:13 UTC
### Terraform CLI and Provider Versions

snowflake-labs/snowflake v0.84.0

### Terraform Configuration

```terraform
Terraform v1.3.1
```

### Expected Behavior

Success! The configuration is valid.

### Actual Behavior

Error: failed to read provider configuration schema for registry.terraform.io/snowflake-labs/snowflake: failed to instantiate provider "registry.terraform.io/snowflake-labs/snowflake" to obtain schema: Unrecognized remote plugin message:

### Steps to Reproduce

1. `terraform plan`

### How much impact is this issue causing?

High

### Additional Information

Resolved by lower to one version down 

terraform {
   required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.76, !=0.84 "
    }
  }
}

**Comment by sfc-gh-jcieslak** [comment] 2024-01-22 09:06
Hey @vthelu 
Could you try to upgrade with the environment variable `TF_LOG=trace` set and paste the logs here, so we'll be able to diagnose what is happening during the upgrade?

**Comment by sandeepravi84** [comment] 2024-01-22 15:30
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/aidanmelen/snowsql v1.3.3
+ provider registry.terraform.io/snowflake-labs/snowflake v0.84.0



terraform validate

2024-01-22T10:28:15.983-0500 [INFO]  Terraform version: 1.3.9
2024-01-22T10:28:15.984-0500 [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2024-01-22T10:28:15.984-0500 [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.0
2024-01-22T10:28:15.984-0500 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2024-01-22T10:28:15.984-0500 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734       
2024-01-22T10:28:15.984-0500 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2024-01-22T10:28:15.984-0500 [INFO]  Go runtime version: go1.19.6
2024-01-22T10:28:15.984-0500 [INFO]  CLI args: []string{"terraform", "validate"}
2024-01-22T10:28:15.984-0500 [TRACE] Stdout is a terminal of width 224
2024-01-22T10:28:15.984-0500 [TRACE] Stderr is a terminal of width 224
2024-01-22T10:28:15.984-0500 [TRACE] Stdin is a terminal
2024-01-22T10:28:15.984-0500 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2024-01-22T10:28:15.984-0500 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2024-01-22T10:28:15.984-0500 [INFO]  Loading CLI configuration from /root/.terraform.d/credentials.tfrc.json
2024-01-22T10:28:15.985-0500 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-01-22T10:28:15.985-0500 [DEBUG] ignoring non-existing provider search directory /root/.terraform.d/plugins
2024-01-22T10:28:15.985-0500 [DEBUG] ignoring non-existing provider search directory /root/.local/share/terraform/plugins    
2024-01-22T10:28:15.985-0500 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins      
2024-01-22T10:28:15.985-0500 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2024-01-22T10:28:15.985-0500 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2024-01-22T10:28:15.987-0500 [INFO]  CLI command args: []string{"validate"}
2024-01-22T10:28:16.086-0500 [TRACE] providercache.fillMetaCache: scanning directory .terraform/providers
2024-01-22T10:28:16.168-0500 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/aidanmelen/snowsql v1.3.3 for linux_amd64 at .terraform/providers/registry.terraform.io/aidanmelen/snowsql/1.3.3/linux_amd642024-01-22T10:28:16.273-0500 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/snowflake-labs/snowflake v0.84.0 for linux_amd64 at .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64
2024-01-22T10:28:16.336-0500 [TRACE] providercache.fillMetaCache: including .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64 as a candidate package for registry.terraform.io/snowflake-labs/snowflake 0.84.0
2024-01-22T10:28:16.336-0500 [TRACE] providercache.fillMetaCache: including .terraform/providers/registry.terraform.io/aidanmelen/snowsql/1.3.3/linux_amd64 as a candidate package for registry.terraform.io/aidanmelen/snowsql 
1.3.3
2024-01-22T10:28:16.676-0500 [TRACE] providercache.fillMetaCache: using cached result from previous scan of .terraform/providers
2024-01-22T10:28:17.475-0500 [DEBUG] checking for provisioner in "."
2024-01-22T10:28:17.479-0500 [DEBUG] checking for provisioner in "/usr/bin"
2024-01-22T10:28:17.480-0500 [TRACE] terraform.NewContext: starting
2024-01-22T10:28:17.480-0500 [TRACE] terraform.NewContext: complete
2024-01-22T10:28:17.480-0500 [DEBUG] Building and walking validate graph
2024-01-22T10:28:17.480-0500 [TRACE] building graph for walkValidate
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.ConfigTransformer
2024-01-22T10:28:17.480-0500 [TRACE] ConfigTransformer: Starting for path:
2024-01-22T10:28:17.480-0500 [TRACE] ConfigTransformer: Starting for path: module.roles    
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.ConfigTransformer with new graph:
  module.roles.snowflake_role.role - *terraform.NodeValidatableResource
  ------
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.RootVariableTransformer
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.RootVariableTransformer (no changes)
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.ModuleVariableTransformer
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.ModuleVariableTransformer with new graph:
  module.roles.snowflake_role.role - *terraform.NodeValidatableResource
  module.roles.var.config_yaml (expand) - *terraform.nodeExpandModuleVariable
  ------
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.LocalTransformer
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.LocalTransformer with new graph:
  module.roles.local.roles (expand) - *terraform.nodeExpandLocal
  module.roles.local.roles_map (expand) - *terraform.nodeExpandLocal
  module.roles.local.variables (expand) - *terraform.nodeExpandLocal
  module.roles.local.yamlFile (expand) - *terraform.nodeExpandLocal
  module.roles.snowflake_role.role - *terraform.NodeValidatableResource
  module.roles.var.config_yaml (expand) - *terraform.nodeExpandModuleVariable
  ------
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.OutputTransformer
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.OutputTransformer (no changes)
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.OrphanResourceInstanceTransformer
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.OrphanResourceInstanceTransformer (no changes)
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.StateTransformer
2024-01-22T10:28:17.480-0500 [TRACE] StateTransformer: pointless no-op call, creating no nodes at all
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.StateTransformer (no changes)
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.AttachStateTransformer
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.AttachStateTransformer (no changes)
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.OrphanOutputTransformer
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.OrphanOutputTransformer (no changes)
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.AttachResourceConfigTransformer
2024-01-22T10:28:17.480-0500 [TRACE] AttachResourceConfigTransformer: attaching to "module.roles.snowflake_role.role" (*terraform.NodeValidatableResource) config from ../roles/main.tf:1,1-33
2024-01-22T10:28:17.480-0500 [TRACE] AttachResourceConfigTransformer: attaching provider meta configs to module.roles.snowflake_role.role
2024-01-22T10:28:17.480-0500 [TRACE] Completed graph transform *terraform.AttachResourceConfigTransformer (no changes)
2024-01-22T10:28:17.480-0500 [TRACE] Executing graph transform *terraform.graphTransformerMulti
2024-01-22T10:28:17.480-0500 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.ProviderConfigTransformer
2024-01-22T10:28:17.480-0500 [TRACE] ProviderConfigTransformer: attaching to "provider[\"registry.terraform.io/snowflake-labs/snowflake\"].devopsadmin" provider configuration from version.tf:21,1-21
2024-01-22T10:28:17.480-0500 [TRACE] ProviderConfigTransformer: attaching to "provider[\"registry.terraform.io/aidanmelen/snowsql\"].devopssql" provider configuration from version.tf:25,1-19
2024-01-22T10:28:17.480-0500 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.ProviderConfigTransformer with new graph:
  module.roles.local.roles (expand) - *terraform.nodeExpandLocal
  module.roles.local.roles_map (expand) - *terraform.nodeExpandLocal
  module.roles.local.variables (expand) - *terraform.nodeExpandLocal
  module.roles.local.yamlFile (expand) - *terraform.nodeExpandLocal
  module.roles.provider["registry.terraform.io/aidanmelen/snowsql"].devopssql (proxy) - *terraform.graphNodeProxyProvider
  module.roles.provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin (proxy) - *terraform.graphNodeProxyProvider
  module.roles.snowflake_role.role - *terraform.NodeValidatableResource
  module.roles.var.config_yaml (expand) - *terraform.nodeExpandModuleVariable
  provider["registry.terraform.io/aidanmelen/snowsql"] - *terraform.NodeApplyableProvider
  provider["registry.terraform.io/aidanmelen/snowsql"].devopssql - *terraform.NodeApplyableProvider
  provider["registry.terraform.io/snowflake-labs/snowflake"] - *terraform.NodeApplyableProvider
  provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin - *terraform.NodeApplyableProvider
  ------
2024-01-22T10:28:17.480-0500 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.MissingProviderTransformer
2024-01-22T10:28:17.480-0500 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.MissingProviderTransformer (no changes)
2024-01-22T10:28:17.480-0500 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.ProviderTransformer
2024-01-22T10:28:17.480-0500 [TRACE] ProviderTransformer: exact match for module.roles.provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin serving module.roles.snowflake_role.role
2024-01-22T10:28:17.480-0500 [DEBUG] ProviderTransformer: "module.roles.snowflake_role.role" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin
2024-01-22T10:28:17.481-0500 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.ProviderTransformer with new graph:
  module.roles.local.roles (expand) - *terraform.nodeExpandLocal
  module.roles.local.roles_map (expand) - *terraform.nodeExpandLocal
  module.roles.local.variables (expand) - *terraform.nodeExpandLocal
  module.roles.local.yamlFile (expand) - *terraform.nodeExpandLocal
  module.roles.provider["registry.terraform.io/aidanmelen/snowsql"].devopssql (proxy) - *terraform.graphNodeProxyProvider
  module.roles.snowflake_role.role - *terraform.NodeValidatableResource
    provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin - *terraform.NodeApplyableProvider
  module.roles.var.config_yaml (expand) - *terraform.nodeExpandModuleVariable
  provider["registry.terraform.io/aidanmelen/snowsql"] - *terraform.NodeApplyableProvider
  provider["registry.terraform.io/aidanmelen/snowsql"].devopssql - *terraform.NodeApplyableProvider
  provider["registry.terraform.io/snowflake-labs/snowflake"] - *terraform.NodeApplyableProvider
  provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin - *terraform.NodeApplyableProvider
  ------
2024-01-22T10:28:17.481-0500 [TRACE] (graphTransformerMulti) Executing graph transform *terraform.PruneProviderTransformer
2024-01-22T10:28:17.481-0500 [DEBUG] pruning unused provider["registry.terraform.io/snowflake-labs/snowflake"]
2024-01-22T10:28:17.481-0500 [DEBUG] pruning unused provider["registry.terraform.io/aidanmelen/snowsql"]
2024-01-22T10:28:17.481-0500 [DEBUG] pruning proxy module.roles.provider["registry.terraform.io/aidanmelen/snowsql"].devopssql (proxy)
2024-01-22T10:28:17.481-0500 [DEBUG] pruning unused module.roles.provider["registry.terraform.io/aidanmelen/snowsql"].devopssql (proxy)
2024-01-22T10:28:17.481-0500 [DEBUG] pruning unused provider["registry.terraform.io/aidanmelen/snowsql"].devopssql
2024-01-22T10:28:17.481-0500 [TRACE] (graphTransformerMulti) Completed graph transform *terraform.PruneProviderTransformer with new graph:
  module.roles.local.roles (expand) - *terraform.nodeExpandLocal
  module.roles.local.roles_map (expand) - *terraform.nodeExpandLocal
  module.roles.local.variables (expand) - *terraform.nodeExpandLocal
  module.roles.local.yamlFile (expand) - *terraform.nodeExpandLocal
  module.roles.snowflake_role.role - *terraform.NodeValidatableResource
    provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin - *terraform.NodeApplyableProvider
  module.roles.var.config_yaml (expand) - *terraform.nodeExpandModuleVariable
  provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin - *terraform.NodeApplyableProvider
  ------
2024-01-22T10:28:17.481-0500 [TRACE] Completed graph transform *terraform.graphTransformerMulti with new graph:
  module.roles.local.roles (expand) - *terraform.nodeExpandLocal
  module.roles.local.roles_map (expand) - *terraform.nodeExpandLocal
  module.roles.local.variables (expand) - *terraform.nodeExpandLocal
  module.roles.local.yamlFile (expand) - *terraform.nodeExpandLocal
  module.roles.snowflake_role.role - *terraform.NodeValidatableResource
    provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin - *terraform.NodeApplyableProvider
  module.roles.var.config_yaml (expand) - *terraform.nodeExpandModuleVariable
  provider["registry.terraform.io/snowflake-labs/snowflake"].devopsadmin - *terraform.NodeApplyableProvider
  ------
2024-01-22T10:28:17.481-0500 [TRACE] Executing graph transform *terraform.RemovedModuleTransformer
2024-01-22T10:28:17.481-0500 [TRACE] Completed graph transform *terraform.RemovedModuleTransformer (no changes)
2024-01-22T10:28:17.481-0500 [TRACE] Executing graph transform *terraform.AttachSchemaTransformer
2024-01-22T10:28:17.481-0500 [TRACE] terraform.contextPlugins: Initializing provider "registry.terraform.io/snowflake-labs/snowflake" to read its schema
2024-01-22T10:28:17.504-0500 [DEBUG] created provider logger: level=trace
2024-01-22T10:28:17.504-0500 [INFO]  provider: configuring client automatic mTLS
2024-01-22T10:28:17.528-0500 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0 args=[.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0]
2024-01-22T10:28:17.538-0500 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0 pid=523
2024-01-22T10:28:17.538-0500 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0
2024-01-22T10:28:17.565-0500 [DEBUG] provider.terraform-provider-snowflake_v0.84.0: .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0: **/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found** (required by .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0)
2024-01-22T10:28:17.565-0500 [DEBUG] provider.terraform-provider-snowflake_v0.84.0: .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0: **/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found** (required by .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0)
2024-01-22T10:28:17.565-0500 [TRACE] Completed graph transform *terraform.AttachSchemaTransformer (no changes)
╷
│ Error: failed to read schema for module.roles.snowflake_role.role in registry.terraform.io/snowflake-labs/snowflake: failed to instantiate provider "registry.terraform.io/snowflake-labs/snowflake" to obtain schema: Unrecognized remote plugin message:
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
│
│
╵
2024-01-22T10:28:17.565-0500 [WARN]  provider: plugin failed to exit gracefully
2024-01-22T10:28:17.568-0500 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0 pid=523 error="exit status 1"

**Comment by grzegorzb1990** [comment] 2024-01-22 15:53
Same here.

`
...
2024-01-22T15:58:15.252+0100 [DEBUG] created provider logger: level=trace
2024-01-22T15:58:15.252+0100 [INFO]  provider: configuring client automatic mTLS
2024-01-22T15:58:15.266+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0 args=[.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0]
2024-01-22T15:58:15.266+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0 pid=358
2024-01-22T15:58:15.266+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0
2024-01-22T15:58:15.267+0100 [DEBUG] provider.terraform-provider-snowflake_v0.84.0: .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0)
2024-01-22T15:58:15.268+0100 [DEBUG] provider.terraform-provider-snowflake_v0.84.0: .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by .terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0)
2024-01-22T15:58:15.268+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/snowflake-labs/snowflake/0.84.0/linux_amd64/terraform-provider-snowflake_v0.84.0 pid=358 error="exit status 1"
2024-01-22T15:58:15.270+0100 [TRACE] Completed graph transform *terraform.AttachSchemaTransformer (no changes)
╷
│ Error: failed to read schema for module.a.snowflake_grant_privileges_to_role.b in registry.terraform.io/snowflake-labs/snowflake: failed to instantiate provider "registry.terraform.io/snowflake-labs/snowflake" to obtain schema: Unrecognized remote plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
│ 
│ 
╵
2024-01-22T15:58:15.270+0100 [WARN]  provider: plugin failed to exit gracefully
##[error]Bash exited with code '1'.
Finishing: terraform plan

`

**Comment by lbourdages** [comment] 2024-01-22 16:14
For what it's worth, the issue doesn't seem to be present when running on arm64. I can't reproduce it on my Mac (running terraform in an arm64 docker), but the same set of files will produce the error shown above when running in our dev environment on amd64.

**Comment by sfc-gh-jcieslak** [comment] 2024-01-22 17:29
Hi all, the new release binary may not work on certain devices, because we suspect the `CGO_ENABLED` flag was wrongly specified in the `.goreleaser.yml` configuration. As goreleaser skips invalid env variables, all releases have been built with the default `CGO_ENABLED=1`. We prepared a fix for it [here](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2388), which should be released in v0.84.1. Please try to use the next version (v0.84.1) and let us know if there are any issues with any of the builds. Sorry for the inconvenience :(

**Comment by philippeboyd** [comment] 2024-01-23 02:10
I had the same issue with `v0.84.0` on OSX Intel, but upgrading to `v0.84.1` did the trick 👍

**Comment by sfc-gh-swinkler** [comment] 2024-01-23 06:21
Closing this as completed. The fix @sfc-gh-jcieslak mentioned did not work, we will need to develop another strategy for enabling CGO in Github actions for WIndows and Darwin binaries. For example, using [this project](https://github.com/goreleaser/goreleaser-cross). Rolling back the change altogether for now

**Closed by sfc-gh-swinkler** 2024-01-23 06:21 UTC
Labels: bug
