### ISSUE TITLE
Add query lifetime attributes to snowflake user

### ISSUE THREAD

**Issue by achierighini** [Snowflake-Labs/terraform-provider-snowflake#981] opened 2022-04-20 15:47 UTC
**Is your feature request related to a problem? Please describe.**

I need to add a few changes to snowflake users regarding the lifetime of queries, more specifically: CLIENT_SESSION_KEEP_ALIVE, ABORT_DETACHED_QUERY, CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY. Those are not available as user attributes in the provider and all external solutions I found wouldn't work for me.

**Describe the solution you'd like**

I suggest adding those attributes to the snowflake users so any automated accounts can be modified to support long queries.

**Describe alternatives you've considered**

I've taken into consideration using the [snowsql](https://registry.terraform.io/providers/aidanmelen/snowsql/latest) provider to run queries such as `alter user SNOWFLAKE_USER set CLIENT_SESSION_KEEP_ALIVE = TRUE;` from terraform, but it would be too much of a hassle, given how it's implemented.

**Additional context**

An example of what I would like to see implemented would look like this:
```
resource "snowflake_user" "my_user" {
  name         = "name"
  password     = "password"
  default_role = "role
  client_session_keep_alive = true
  abort_detached_query = true
  client_session_keep_alive_heartbeat_frequency = 1000
}
```

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:46
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:46 UTC
Labels: feature-request
