### ISSUE TITLE
Add foreign key parameter to column

### ISSUE THREAD

**Issue by tolik93** [Snowflake-Labs/terraform-provider-snowflake#683] opened 2021-09-15 10:28 UTC
**Is your feature request related to a problem? Please describe.**

It would be great if there was a column attribute foreign_key that references the specific tables. 

A possible solution could look like this:
```hcl
resource "snowflake_table" "table" {
  database            = snowflake_schema.schema.database
  schema              = snowflake_schema.schema.name
  name                = "table"

  column {
    name     = "my_id"
    type     = "int"
    nullable = true
  }


  column {
    name     = "foreign_id"
    type     = "int"

    # reference to another table
    references {
        table = "foreign_table"
        schema = "schema"
        column = "id"
    }
  }

  primary_key {
      keys = ["my_id"]
  }

}
```

We need this immediately

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:54
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:54 UTC
Labels: feature-request
