### ISSUE TITLE
View statement updated but depended view not update

### ISSUE THREAD

**Issue by toughrogrammer** [Snowflake-Labs/terraform-provider-snowflake#977] opened 2022-04-16 19:22 UTC
**Provider Version**

0.31.0

**Terraform Version**

1.1.8

**Describe the bug**

Here is sample terraform codes.

```
resource "snowflake_table" "table" {
  database = snowflake_database.db.name
  schema   = "PUBLIC"
  name     = "TF_DEMO_TABLE"
  comment  = "A table."

  column {
    name     = "DATE"
    type     = "TIMESTAMP_NTZ(9)"
    nullable = true
  }

  column {
    name     = "ID"
    type     = "NUMBER(38,0)"
    nullable = true
  }

  column {
    name     = "EXTRA"
    type     = "VARCHAR(16777216)"
    nullable = true
    comment  = "extra data"
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "snowflake_view" "view_depth1" {
  database = snowflake_database.db.name
  schema   = "PUBLIC"
  name     = "TF_DEMO_VIEW_DEPTH1"
  comment  = "A table."

  statement  = <<-SQL
SELECT 
  DATE,
  ID * 10 AS ID,
  ID * 20 AS ID_MUL_20,
  EXTRA
FROM 
  TF_DEMO_TABLE
SQL
  or_replace = true

  depends_on = [
    snowflake_table.table,
  ]
}

resource "snowflake_view" "view_depth2" {
  database = snowflake_database.db.name
  schema   = "PUBLIC"
  name     = "TF_DEMO_VIEW_DEPTH2"
  comment  = "A table."

  statement  = <<-SQL
SELECT 
  *
FROM
  ${snowflake_view.view_depth1.name}
SQL
  or_replace = true

  # not work
  depends_on = [
    snowflake_view.view_depth1,
  ]
}
```

When `ID * 20 AS ID_MUL_20` is changed to `ID * 30 AS ID_MUL_30`, `TF_DEMO_VIEW_DEPTH1` will be re-created.
In that case, `TF_DEMO_VIEW_DEPTH2` must be re-created also.
But when I tested it, `TF_DEMO_VIEW_DEPTH2` is not re-created.

**Expected behavior**

`snowflake_view.view_depth2` resource must be re-created.

**Code samples and commands**

There is sample code above.

**Additional context**

...

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:47
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:47 UTC
Labels: bug
