### ISSUE TITLE
A data source for the current user

### ISSUE THREAD

**Issue by tekumara** [Snowflake-Labs/terraform-provider-snowflake#744] opened 2021-11-02 01:21 UTC
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use the current user in local-exec.

**Describe the solution you'd like**

A data source for the current user, eg:

```
data "snowflake_current_user" "this" {}

resource "aws_secretsmanager_secret" "snowflake_user" {
  depends_on = [
    snowflake_user.user
  ]
  name = "snowflakeuser/${snowflake_user.user.name}"
  description = "Snowflake user password"

  // set password for snowflake and store it in the secret
  // this is done in local-exec so its not stored in the tf statefile
  provisioner "local-exec" {
      command = "sfpassman ${self.name} ${data.snowflake_current_user.this.username} ${data.snowflake_current_account.this.account} ${data.snowflake_current_account.this.region}"
  }
}

```

**Describe alternatives you've considered**

Passing the current user in as a variable to my module.

**Additional context**

**Comment by sfc-gh-asawicki** [comment] 2024-04-30 16:52
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.

**Closed by sfc-gh-asawicki** 2024-04-30 16:52 UTC
Labels: feature-request
