### ISSUE TITLE
[Bug]: storage integration with storage_aws_external_id

### ISSUE THREAD

**Issue by jsantora-uom** [Snowflake-Labs/terraform-provider-snowflake#2812] opened 2024-05-16 01:21 UTC
### Terraform CLI Version

>=1.0

### Terraform Provider Version

>=1.0

### Terraform Configuration

```terraform
resource "snowflake_storage_integration" "edw_storage_integration" {
  provider = snowflake.EDW_SYSADMIN
  name     = "xx"
  type     = "EXTERNAL_STAGE"
  enabled  = true
  storage_allowed_locations = [
    "xx"
  ]
  storage_provider        = "S3"
  storage_aws_role_arn    = local.workspace.storage_aws_role_arn
  storage_aws_external_id = "xxxxx"
}
```

### Category

category:other

### Object type(s)

resource:storage_integration

### Expected Behavior

I would expect that storage integration will be created with the provided storage_aws_external_id. In snowflake I can run create or replace storage integration with specific storage_aws_external_id.

### Actual Behavior

Can't configure a value for "storage_aws_external_id": its value will be
│ decided automatically based on the result of applying this configuration.

### Steps to Reproduce

1. create storage integration specifying storage_aws_external_id
2. terraform plan

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by jsantora-uom** [comment] 2024-05-16 01:56
Reading through the go code, I believe the attribute storage_aws_external_id is computed. I wonder if this could be changed depending if the storage_aws_external_id attribute is specified in the resource. If it is use that string, if it is not, compute.

**Comment by sfc-gh-asawicki** [comment] 2024-05-16 08:11
Hey @jsantora-uom. Thanks for reaching out to us.

I believe this is a duplicate of #2624. Please confirm.

**Comment by jsantora-uom** [comment] 2024-05-30 06:59
That is correct, thanks @sfc-gh-asawicki, feel free to close this one, I'll watch the other ticket.

**Closed** 2024-05-31 07:28 UTC
Labels: bug, resource:storage_integration, category:resource
